import type { LandingSpec } from "@/lib/seo-catalog/types";

export const CATALOG_LANDING_SPECS_EXTRA: LandingSpec[] = [
  {
    category: "automation",
    slug: "order-processing",
    contentKey: "extra_order_processing",
    cluster: "automation",
    serviceSlug: "sales-ai-agent",
    coverImage: "/diagrams/sales-pipeline.svg",
    keywords: ["обработка заказов","заказы crm"],
    related: [
      { href: "/automation/sales", labelRu: "Автоматизация продаж", labelEn: "Sales automation" },
      { href: "/integrations/crm", labelRu: "Внедрение CRM", labelEn: "CRM implementation" },
      { href: "/integrations/1c", labelRu: "Интеграция 1С", labelEn: "1C integration" }
    ],
    ru: {
      h1: "Автоматизация обработки заказов",
      subtitle: "Автоматизация обработки заказов: меньше ручной работы, данные в системах учёта, измеримый ROI.",
      problems: ["Процесс держится на людях и чатах","Нет единого статуса задачи","Ошибки из-за ручного переноса","Руководитель видит результат слишком поздно"],
      deliverables: ["Карта процесса и KPI","Рабочий контур в production","Интеграции с CRM/документами","Регламент и обучение"],
      intro: ["Автоматизация обработки заказов — практический сценарий автоматизации под спрос Wordstat.","Сначала процесс и данные, затем интеграции и AI-слой.","Пилот обычно занимает 2–6 недель."],
      faq: [{"q":"С чего начать?","a":"С аудита одного узкого сценария и расчёта часов/денег."},{"q":"Нужен ли AI?","a":"Не всегда. Часто хватает workflow и интеграций."},{"q":"Какой бюджет?","a":"Пилот — от 150–400 тыс. ₽ в зависимости от интеграций."}],
    },
    en: {
      h1: "Order processing automation",
      subtitle: "Order processing automation: less manual work, data in systems of record, measurable ROI.",
      problems: ["The process depends on people and chats","No single task status","Errors from manual transfer","Leaders see results too late"],
      deliverables: ["Process map and KPIs","Production workflow","CRM/document integrations","Playbook and training"],
      intro: ["Order processing automation is a practical automation scenario.","Process and data first, then integrations and optional AI.","Pilots usually take 2–6 weeks."],
      faq: [{"q":"Where to start?","a":"Audit one narrow scenario and calculate hours/money."},{"q":"Is AI required?","a":"Not always. Workflow and integrations are often enough."},{"q":"Budget?","a":"Pilots typically start from a fixed mid-market scope."}],
    },
  },
  {
    category: "automation",
    slug: "payment-control",
    contentKey: "extra_payment_control",
    cluster: "automation",
    serviceSlug: "business-process-automation",
    coverImage: "/diagrams/erp-sync.svg",
    keywords: ["контроль оплат","дебиторская задолженность"],
    related: [
      { href: "/integrations/1c", labelRu: "Интеграция 1С", labelEn: "1C integration" },
      { href: "/automation/management", labelRu: "Для руководителя", labelEn: "Management AI" }
    ],
    ru: {
      h1: "Контроль оплат и дебиторки",
      subtitle: "Контроль оплат и дебиторки: меньше ручной работы, данные в системах учёта, измеримый ROI.",
      problems: ["Процесс держится на людях и чатах","Нет единого статуса задачи","Ошибки из-за ручного переноса","Руководитель видит результат слишком поздно"],
      deliverables: ["Карта процесса и KPI","Рабочий контур в production","Интеграции с CRM/документами","Регламент и обучение"],
      intro: ["Контроль оплат и дебиторки — практический сценарий автоматизации под спрос Wordstat.","Сначала процесс и данные, затем интеграции и AI-слой.","Пилот обычно занимает 2–6 недель."],
      faq: [{"q":"С чего начать?","a":"С аудита одного узкого сценария и расчёта часов/денег."},{"q":"Нужен ли AI?","a":"Не всегда. Часто хватает workflow и интеграций."},{"q":"Какой бюджет?","a":"Пилот — от 150–400 тыс. ₽ в зависимости от интеграций."}],
    },
    en: {
      h1: "Payment and receivables control",
      subtitle: "Payment and receivables control: less manual work, data in systems of record, measurable ROI.",
      problems: ["The process depends on people and chats","No single task status","Errors from manual transfer","Leaders see results too late"],
      deliverables: ["Process map and KPIs","Production workflow","CRM/document integrations","Playbook and training"],
      intro: ["Payment and receivables control is a practical automation scenario.","Process and data first, then integrations and optional AI.","Pilots usually take 2–6 weeks."],
      faq: [{"q":"Where to start?","a":"Audit one narrow scenario and calculate hours/money."},{"q":"Is AI required?","a":"Not always. Workflow and integrations are often enough."},{"q":"Budget?","a":"Pilots typically start from a fixed mid-market scope."}],
    },
  },
  {
    category: "automation",
    slug: "inventory-requests",
    contentKey: "extra_inventory_requests",
    cluster: "automation",
    serviceSlug: "business-process-automation",
    coverImage: "/diagrams/workflow-automation.svg",
    keywords: ["заявки на склад","заявки на закупку"],
    related: [
      { href: "/automation/processes", labelRu: "Автоматизация процессов", labelEn: "Process automation" },
      { href: "/integrations/1c", labelRu: "Интеграция 1С", labelEn: "1C integration" }
    ],
    ru: {
      h1: "Заявки на склад и закупки",
      subtitle: "Заявки на склад и закупки: меньше ручной работы, данные в системах учёта, измеримый ROI.",
      problems: ["Процесс держится на людях и чатах","Нет единого статуса задачи","Ошибки из-за ручного переноса","Руководитель видит результат слишком поздно"],
      deliverables: ["Карта процесса и KPI","Рабочий контур в production","Интеграции с CRM/документами","Регламент и обучение"],
      intro: ["Заявки на склад и закупки — практический сценарий автоматизации под спрос Wordstat.","Сначала процесс и данные, затем интеграции и AI-слой.","Пилот обычно занимает 2–6 недель."],
      faq: [{"q":"С чего начать?","a":"С аудита одного узкого сценария и расчёта часов/денег."},{"q":"Нужен ли AI?","a":"Не всегда. Часто хватает workflow и интеграций."},{"q":"Какой бюджет?","a":"Пилот — от 150–400 тыс. ₽ в зависимости от интеграций."}],
    },
    en: {
      h1: "Warehouse and purchase requests",
      subtitle: "Warehouse and purchase requests: less manual work, data in systems of record, measurable ROI.",
      problems: ["The process depends on people and chats","No single task status","Errors from manual transfer","Leaders see results too late"],
      deliverables: ["Process map and KPIs","Production workflow","CRM/document integrations","Playbook and training"],
      intro: ["Warehouse and purchase requests is a practical automation scenario.","Process and data first, then integrations and optional AI.","Pilots usually take 2–6 weeks."],
      faq: [{"q":"Where to start?","a":"Audit one narrow scenario and calculate hours/money."},{"q":"Is AI required?","a":"Not always. Workflow and integrations are often enough."},{"q":"Budget?","a":"Pilots typically start from a fixed mid-market scope."}],
    },
  },
  {
    category: "automation",
    slug: "meeting-notes",
    contentKey: "extra_meeting_notes",
    cluster: "automation",
    serviceSlug: "enterprise-ai-assistant",
    coverImage: "/diagrams/system-architecture.svg",
    keywords: ["протоколы встреч","задачи из встреч"],
    related: [
      { href: "/automation/knowledge-base", labelRu: "База знаний", labelEn: "Knowledge base" },
      { href: "/automation/processes", labelRu: "Автоматизация процессов", labelEn: "Process automation" }
    ],
    ru: {
      h1: "Протоколы встреч и задачи из созвонов",
      subtitle: "Протоколы встреч и задачи из созвонов: меньше ручной работы, данные в системах учёта, измеримый ROI.",
      problems: ["Процесс держится на людях и чатах","Нет единого статуса задачи","Ошибки из-за ручного переноса","Руководитель видит результат слишком поздно"],
      deliverables: ["Карта процесса и KPI","Рабочий контур в production","Интеграции с CRM/документами","Регламент и обучение"],
      intro: ["Протоколы встреч и задачи из созвонов — практический сценарий автоматизации под спрос Wordstat.","Сначала процесс и данные, затем интеграции и AI-слой.","Пилот обычно занимает 2–6 недель."],
      faq: [{"q":"С чего начать?","a":"С аудита одного узкого сценария и расчёта часов/денег."},{"q":"Нужен ли AI?","a":"Не всегда. Часто хватает workflow и интеграций."},{"q":"Какой бюджет?","a":"Пилот — от 150–400 тыс. ₽ в зависимости от интеграций."}],
    },
    en: {
      h1: "Meeting notes to tasks",
      subtitle: "Meeting notes to tasks: less manual work, data in systems of record, measurable ROI.",
      problems: ["The process depends on people and chats","No single task status","Errors from manual transfer","Leaders see results too late"],
      deliverables: ["Process map and KPIs","Production workflow","CRM/document integrations","Playbook and training"],
      intro: ["Meeting notes to tasks is a practical automation scenario.","Process and data first, then integrations and optional AI.","Pilots usually take 2–6 weeks."],
      faq: [{"q":"Where to start?","a":"Audit one narrow scenario and calculate hours/money."},{"q":"Is AI required?","a":"Not always. Workflow and integrations are often enough."},{"q":"Budget?","a":"Pilots typically start from a fixed mid-market scope."}],
    },
  },
  {
    category: "automation",
    slug: "email-triage",
    contentKey: "extra_email_triage",
    cluster: "automation",
    serviceSlug: "enterprise-ai-assistant",
    coverImage: "/diagrams/system-architecture.svg",
    keywords: ["разбор почты","маршрутизация писем"],
    related: [
      { href: "/automation/support", labelRu: "Поддержка", labelEn: "Support automation" },
      { href: "/automation/sales", labelRu: "Автоматизация продаж", labelEn: "Sales automation" }
    ],
    ru: {
      h1: "Разбор и маршрутизация рабочей почты",
      subtitle: "Разбор и маршрутизация рабочей почты: меньше ручной работы, данные в системах учёта, измеримый ROI.",
      problems: ["Процесс держится на людях и чатах","Нет единого статуса задачи","Ошибки из-за ручного переноса","Руководитель видит результат слишком поздно"],
      deliverables: ["Карта процесса и KPI","Рабочий контур в production","Интеграции с CRM/документами","Регламент и обучение"],
      intro: ["Разбор и маршрутизация рабочей почты — практический сценарий автоматизации под спрос Wordstat.","Сначала процесс и данные, затем интеграции и AI-слой.","Пилот обычно занимает 2–6 недель."],
      faq: [{"q":"С чего начать?","a":"С аудита одного узкого сценария и расчёта часов/денег."},{"q":"Нужен ли AI?","a":"Не всегда. Часто хватает workflow и интеграций."},{"q":"Какой бюджет?","a":"Пилот — от 150–400 тыс. ₽ в зависимости от интеграций."}],
    },
    en: {
      h1: "Business email triage",
      subtitle: "Business email triage: less manual work, data in systems of record, measurable ROI.",
      problems: ["The process depends on people and chats","No single task status","Errors from manual transfer","Leaders see results too late"],
      deliverables: ["Process map and KPIs","Production workflow","CRM/document integrations","Playbook and training"],
      intro: ["Business email triage is a practical automation scenario.","Process and data first, then integrations and optional AI.","Pilots usually take 2–6 weeks."],
      faq: [{"q":"Where to start?","a":"Audit one narrow scenario and calculate hours/money."},{"q":"Is AI required?","a":"Not always. Workflow and integrations are often enough."},{"q":"Budget?","a":"Pilots typically start from a fixed mid-market scope."}],
    },
  },
  {
    category: "automation",
    slug: "contract-registry",
    contentKey: "extra_contract_registry",
    cluster: "automation",
    serviceSlug: "document-processing",
    coverImage: "/diagrams/document-flow.svg",
    keywords: ["реестр договоров","учёт договоров"],
    related: [
      { href: "/automation/documents", labelRu: "Документооборот", labelEn: "Document automation" },
      { href: "/integrations/1c", labelRu: "Интеграция 1С", labelEn: "1C integration" }
    ],
    ru: {
      h1: "Реестр договоров компании",
      subtitle: "Реестр договоров компании: меньше ручной работы, данные в системах учёта, измеримый ROI.",
      problems: ["Процесс держится на людях и чатах","Нет единого статуса задачи","Ошибки из-за ручного переноса","Руководитель видит результат слишком поздно"],
      deliverables: ["Карта процесса и KPI","Рабочий контур в production","Интеграции с CRM/документами","Регламент и обучение"],
      intro: ["Реестр договоров компании — практический сценарий автоматизации под спрос Wordstat.","Сначала процесс и данные, затем интеграции и AI-слой.","Пилот обычно занимает 2–6 недель."],
      faq: [{"q":"С чего начать?","a":"С аудита одного узкого сценария и расчёта часов/денег."},{"q":"Нужен ли AI?","a":"Не всегда. Часто хватает workflow и интеграций."},{"q":"Какой бюджет?","a":"Пилот — от 150–400 тыс. ₽ в зависимости от интеграций."}],
    },
    en: {
      h1: "Company contract registry",
      subtitle: "Company contract registry: less manual work, data in systems of record, measurable ROI.",
      problems: ["The process depends on people and chats","No single task status","Errors from manual transfer","Leaders see results too late"],
      deliverables: ["Process map and KPIs","Production workflow","CRM/document integrations","Playbook and training"],
      intro: ["Company contract registry is a practical automation scenario.","Process and data first, then integrations and optional AI.","Pilots usually take 2–6 weeks."],
      faq: [{"q":"Where to start?","a":"Audit one narrow scenario and calculate hours/money."},{"q":"Is AI required?","a":"Not always. Workflow and integrations are often enough."},{"q":"Budget?","a":"Pilots typically start from a fixed mid-market scope."}],
    },
  },
  {
    category: "automation",
    slug: "access-requests",
    contentKey: "extra_access_requests",
    cluster: "automation",
    serviceSlug: "business-process-automation",
    coverImage: "/diagrams/workflow-automation.svg",
    keywords: ["заявки на доступы","itil автоматизация"],
    related: [
      { href: "/automation/support", labelRu: "Поддержка", labelEn: "Support automation" },
      { href: "/automation/processes", labelRu: "Автоматизация процессов", labelEn: "Process automation" }
    ],
    ru: {
      h1: "Заявки на доступы и IT-сервисы",
      subtitle: "Заявки на доступы и IT-сервисы: меньше ручной работы, данные в системах учёта, измеримый ROI.",
      problems: ["Процесс держится на людях и чатах","Нет единого статуса задачи","Ошибки из-за ручного переноса","Руководитель видит результат слишком поздно"],
      deliverables: ["Карта процесса и KPI","Рабочий контур в production","Интеграции с CRM/документами","Регламент и обучение"],
      intro: ["Заявки на доступы и IT-сервисы — практический сценарий автоматизации под спрос Wordstat.","Сначала процесс и данные, затем интеграции и AI-слой.","Пилот обычно занимает 2–6 недель."],
      faq: [{"q":"С чего начать?","a":"С аудита одного узкого сценария и расчёта часов/денег."},{"q":"Нужен ли AI?","a":"Не всегда. Часто хватает workflow и интеграций."},{"q":"Какой бюджет?","a":"Пилот — от 150–400 тыс. ₽ в зависимости от интеграций."}],
    },
    en: {
      h1: "IT access request automation",
      subtitle: "IT access request automation: less manual work, data in systems of record, measurable ROI.",
      problems: ["The process depends on people and chats","No single task status","Errors from manual transfer","Leaders see results too late"],
      deliverables: ["Process map and KPIs","Production workflow","CRM/document integrations","Playbook and training"],
      intro: ["IT access request automation is a practical automation scenario.","Process and data first, then integrations and optional AI.","Pilots usually take 2–6 weeks."],
      faq: [{"q":"Where to start?","a":"Audit one narrow scenario and calculate hours/money."},{"q":"Is AI required?","a":"Not always. Workflow and integrations are often enough."},{"q":"Budget?","a":"Pilots typically start from a fixed mid-market scope."}],
    },
  },
  {
    category: "automation",
    slug: "partner-leads",
    contentKey: "extra_partner_leads",
    cluster: "automation",
    serviceSlug: "sales-ai-agent",
    coverImage: "/diagrams/sales-pipeline.svg",
    keywords: ["заявки партнёров","партнёрский канал"],
    related: [
      { href: "/automation/sales", labelRu: "Автоматизация продаж", labelEn: "Sales automation" },
      { href: "/integrations/crm", labelRu: "Внедрение CRM", labelEn: "CRM implementation" }
    ],
    ru: {
      h1: "Обработка заявок от партнёров",
      subtitle: "Обработка заявок от партнёров: меньше ручной работы, данные в системах учёта, измеримый ROI.",
      problems: ["Процесс держится на людях и чатах","Нет единого статуса задачи","Ошибки из-за ручного переноса","Руководитель видит результат слишком поздно"],
      deliverables: ["Карта процесса и KPI","Рабочий контур в production","Интеграции с CRM/документами","Регламент и обучение"],
      intro: ["Обработка заявок от партнёров — практический сценарий автоматизации под спрос Wordstat.","Сначала процесс и данные, затем интеграции и AI-слой.","Пилот обычно занимает 2–6 недель."],
      faq: [{"q":"С чего начать?","a":"С аудита одного узкого сценария и расчёта часов/денег."},{"q":"Нужен ли AI?","a":"Не всегда. Часто хватает workflow и интеграций."},{"q":"Какой бюджет?","a":"Пилот — от 150–400 тыс. ₽ в зависимости от интеграций."}],
    },
    en: {
      h1: "Partner lead processing",
      subtitle: "Partner lead processing: less manual work, data in systems of record, measurable ROI.",
      problems: ["The process depends on people and chats","No single task status","Errors from manual transfer","Leaders see results too late"],
      deliverables: ["Process map and KPIs","Production workflow","CRM/document integrations","Playbook and training"],
      intro: ["Partner lead processing is a practical automation scenario.","Process and data first, then integrations and optional AI.","Pilots usually take 2–6 weeks."],
      faq: [{"q":"Where to start?","a":"Audit one narrow scenario and calculate hours/money."},{"q":"Is AI required?","a":"Not always. Workflow and integrations are often enough."},{"q":"Budget?","a":"Pilots typically start from a fixed mid-market scope."}],
    },
  },
  {
    category: "automation",
    slug: "field-reports",
    contentKey: "extra_field_reports",
    cluster: "automation",
    serviceSlug: "business-process-automation",
    coverImage: "/diagrams/workflow-automation.svg",
    keywords: ["полевые отчёты","отчёты агентов"],
    related: [
      { href: "/automation/processes", labelRu: "Автоматизация процессов", labelEn: "Process automation" },
      { href: "/automation/management", labelRu: "Для руководителя", labelEn: "Management AI" }
    ],
    ru: {
      h1: "Отчёты полевых сотрудников",
      subtitle: "Отчёты полевых сотрудников: меньше ручной работы, данные в системах учёта, измеримый ROI.",
      problems: ["Процесс держится на людях и чатах","Нет единого статуса задачи","Ошибки из-за ручного переноса","Руководитель видит результат слишком поздно"],
      deliverables: ["Карта процесса и KPI","Рабочий контур в production","Интеграции с CRM/документами","Регламент и обучение"],
      intro: ["Отчёты полевых сотрудников — практический сценарий автоматизации под спрос Wordstat.","Сначала процесс и данные, затем интеграции и AI-слой.","Пилот обычно занимает 2–6 недель."],
      faq: [{"q":"С чего начать?","a":"С аудита одного узкого сценария и расчёта часов/денег."},{"q":"Нужен ли AI?","a":"Не всегда. Часто хватает workflow и интеграций."},{"q":"Какой бюджет?","a":"Пилот — от 150–400 тыс. ₽ в зависимости от интеграций."}],
    },
    en: {
      h1: "Field employee reports",
      subtitle: "Field employee reports: less manual work, data in systems of record, measurable ROI.",
      problems: ["The process depends on people and chats","No single task status","Errors from manual transfer","Leaders see results too late"],
      deliverables: ["Process map and KPIs","Production workflow","CRM/document integrations","Playbook and training"],
      intro: ["Field employee reports is a practical automation scenario.","Process and data first, then integrations and optional AI.","Pilots usually take 2–6 weeks."],
      faq: [{"q":"Where to start?","a":"Audit one narrow scenario and calculate hours/money."},{"q":"Is AI required?","a":"Not always. Workflow and integrations are often enough."},{"q":"Budget?","a":"Pilots typically start from a fixed mid-market scope."}],
    },
  },
  {
    category: "automation",
    slug: "quality-checklists",
    contentKey: "extra_quality_checklists",
    cluster: "automation",
    serviceSlug: "business-process-automation",
    coverImage: "/diagrams/workflow-automation.svg",
    keywords: ["чеклисты качества","аудиты процессов"],
    related: [
      { href: "/automation/processes", labelRu: "Автоматизация процессов", labelEn: "Process automation" },
      { href: "/automation/management", labelRu: "Для руководителя", labelEn: "Management AI" }
    ],
    ru: {
      h1: "Чеклисты качества и аудитов",
      subtitle: "Чеклисты качества и аудитов: меньше ручной работы, данные в системах учёта, измеримый ROI.",
      problems: ["Процесс держится на людях и чатах","Нет единого статуса задачи","Ошибки из-за ручного переноса","Руководитель видит результат слишком поздно"],
      deliverables: ["Карта процесса и KPI","Рабочий контур в production","Интеграции с CRM/документами","Регламент и обучение"],
      intro: ["Чеклисты качества и аудитов — практический сценарий автоматизации под спрос Wordstat.","Сначала процесс и данные, затем интеграции и AI-слой.","Пилот обычно занимает 2–6 недель."],
      faq: [{"q":"С чего начать?","a":"С аудита одного узкого сценария и расчёта часов/денег."},{"q":"Нужен ли AI?","a":"Не всегда. Часто хватает workflow и интеграций."},{"q":"Какой бюджет?","a":"Пилот — от 150–400 тыс. ₽ в зависимости от интеграций."}],
    },
    en: {
      h1: "Quality and audit checklists",
      subtitle: "Quality and audit checklists: less manual work, data in systems of record, measurable ROI.",
      problems: ["The process depends on people and chats","No single task status","Errors from manual transfer","Leaders see results too late"],
      deliverables: ["Process map and KPIs","Production workflow","CRM/document integrations","Playbook and training"],
      intro: ["Quality and audit checklists is a practical automation scenario.","Process and data first, then integrations and optional AI.","Pilots usually take 2–6 weeks."],
      faq: [{"q":"Where to start?","a":"Audit one narrow scenario and calculate hours/money."},{"q":"Is AI required?","a":"Not always. Workflow and integrations are often enough."},{"q":"Budget?","a":"Pilots typically start from a fixed mid-market scope."}],
    },
  },
  {
    category: "integrations",
    slug: "whatsapp-crm",
    contentKey: "extra_whatsapp_crm",
    cluster: "integrations",
    serviceSlug: "crm-integration",
    coverImage: "/diagrams/crm-integration.svg",
    keywords: ["whatsapp crm","заявки из whatsapp"],
    related: [
      { href: "/integrations/crm", labelRu: "Внедрение CRM", labelEn: "CRM implementation" },
      { href: "/automation/support", labelRu: "Поддержка", labelEn: "Support automation" }
    ],
    ru: {
      h1: "Интеграция WhatsApp с CRM",
      subtitle: "Интеграция WhatsApp с CRM: меньше ручной работы, данные в системах учёта, измеримый ROI.",
      problems: ["Процесс держится на людях и чатах","Нет единого статуса задачи","Ошибки из-за ручного переноса","Руководитель видит результат слишком поздно"],
      deliverables: ["Карта процесса и KPI","Рабочий контур в production","Интеграции с CRM/документами","Регламент и обучение"],
      intro: ["Интеграция WhatsApp с CRM — практический сценарий автоматизации под спрос Wordstat.","Сначала процесс и данные, затем интеграции и AI-слой.","Пилот обычно занимает 2–6 недель."],
      faq: [{"q":"С чего начать?","a":"С аудита одного узкого сценария и расчёта часов/денег."},{"q":"Нужен ли AI?","a":"Не всегда. Часто хватает workflow и интеграций."},{"q":"Какой бюджет?","a":"Пилот — от 150–400 тыс. ₽ в зависимости от интеграций."}],
    },
    en: {
      h1: "WhatsApp to CRM integration",
      subtitle: "WhatsApp to CRM integration: less manual work, data in systems of record, measurable ROI.",
      problems: ["The process depends on people and chats","No single task status","Errors from manual transfer","Leaders see results too late"],
      deliverables: ["Process map and KPIs","Production workflow","CRM/document integrations","Playbook and training"],
      intro: ["WhatsApp to CRM integration is a practical automation scenario.","Process and data first, then integrations and optional AI.","Pilots usually take 2–6 weeks."],
      faq: [{"q":"Where to start?","a":"Audit one narrow scenario and calculate hours/money."},{"q":"Is AI required?","a":"Not always. Workflow and integrations are often enough."},{"q":"Budget?","a":"Pilots typically start from a fixed mid-market scope."}],
    },
  },
  {
    category: "integrations",
    slug: "avito-leads",
    contentKey: "extra_avito_leads",
    cluster: "integrations",
    serviceSlug: "crm-integration",
    coverImage: "/diagrams/crm-integration.svg",
    keywords: ["авито crm","лиды с авито"],
    related: [
      { href: "/integrations/crm", labelRu: "Внедрение CRM", labelEn: "CRM implementation" },
      { href: "/automation/sales", labelRu: "Автоматизация продаж", labelEn: "Sales automation" }
    ],
    ru: {
      h1: "Лиды с Авито в CRM",
      subtitle: "Лиды с Авито в CRM: меньше ручной работы, данные в системах учёта, измеримый ROI.",
      problems: ["Процесс держится на людях и чатах","Нет единого статуса задачи","Ошибки из-за ручного переноса","Руководитель видит результат слишком поздно"],
      deliverables: ["Карта процесса и KPI","Рабочий контур в production","Интеграции с CRM/документами","Регламент и обучение"],
      intro: ["Лиды с Авито в CRM — практический сценарий автоматизации под спрос Wordstat.","Сначала процесс и данные, затем интеграции и AI-слой.","Пилот обычно занимает 2–6 недель."],
      faq: [{"q":"С чего начать?","a":"С аудита одного узкого сценария и расчёта часов/денег."},{"q":"Нужен ли AI?","a":"Не всегда. Часто хватает workflow и интеграций."},{"q":"Какой бюджет?","a":"Пилот — от 150–400 тыс. ₽ в зависимости от интеграций."}],
    },
    en: {
      h1: "Avito leads into CRM",
      subtitle: "Avito leads into CRM: less manual work, data in systems of record, measurable ROI.",
      problems: ["The process depends on people and chats","No single task status","Errors from manual transfer","Leaders see results too late"],
      deliverables: ["Process map and KPIs","Production workflow","CRM/document integrations","Playbook and training"],
      intro: ["Avito leads into CRM is a practical automation scenario.","Process and data first, then integrations and optional AI.","Pilots usually take 2–6 weeks."],
      faq: [{"q":"Where to start?","a":"Audit one narrow scenario and calculate hours/money."},{"q":"Is AI required?","a":"Not always. Workflow and integrations are often enough."},{"q":"Budget?","a":"Pilots typically start from a fixed mid-market scope."}],
    },
  },
  {
    category: "integrations",
    slug: "google-sheets-sync",
    contentKey: "extra_google_sheets_sync",
    cluster: "integrations",
    serviceSlug: "crm-integration",
    coverImage: "/diagrams/crm-integration.svg",
    keywords: ["google sheets crm","таблицы в crm"],
    related: [
      { href: "/integrations/crm", labelRu: "Внедрение CRM", labelEn: "CRM implementation" },
      { href: "/automation/processes", labelRu: "Автоматизация процессов", labelEn: "Process automation" }
    ],
    ru: {
      h1: "Синхронизация Google Sheets с CRM",
      subtitle: "Синхронизация Google Sheets с CRM: меньше ручной работы, данные в системах учёта, измеримый ROI.",
      problems: ["Процесс держится на людях и чатах","Нет единого статуса задачи","Ошибки из-за ручного переноса","Руководитель видит результат слишком поздно"],
      deliverables: ["Карта процесса и KPI","Рабочий контур в production","Интеграции с CRM/документами","Регламент и обучение"],
      intro: ["Синхронизация Google Sheets с CRM — практический сценарий автоматизации под спрос Wordstat.","Сначала процесс и данные, затем интеграции и AI-слой.","Пилот обычно занимает 2–6 недель."],
      faq: [{"q":"С чего начать?","a":"С аудита одного узкого сценария и расчёта часов/денег."},{"q":"Нужен ли AI?","a":"Не всегда. Часто хватает workflow и интеграций."},{"q":"Какой бюджет?","a":"Пилот — от 150–400 тыс. ₽ в зависимости от интеграций."}],
    },
    en: {
      h1: "Google Sheets to CRM sync",
      subtitle: "Google Sheets to CRM sync: less manual work, data in systems of record, measurable ROI.",
      problems: ["The process depends on people and chats","No single task status","Errors from manual transfer","Leaders see results too late"],
      deliverables: ["Process map and KPIs","Production workflow","CRM/document integrations","Playbook and training"],
      intro: ["Google Sheets to CRM sync is a practical automation scenario.","Process and data first, then integrations and optional AI.","Pilots usually take 2–6 weeks."],
      faq: [{"q":"Where to start?","a":"Audit one narrow scenario and calculate hours/money."},{"q":"Is AI required?","a":"Not always. Workflow and integrations are often enough."},{"q":"Budget?","a":"Pilots typically start from a fixed mid-market scope."}],
    },
  },
  {
    category: "integrations",
    slug: "yandex-metrica-crm",
    contentKey: "extra_yandex_metrica_crm",
    cluster: "integrations",
    serviceSlug: "crm-integration",
    coverImage: "/diagrams/crm-integration.svg",
    keywords: ["сквозная аналитика","метрика crm"],
    related: [
      { href: "/integrations/crm", labelRu: "Внедрение CRM", labelEn: "CRM implementation" },
      { href: "/automation/management", labelRu: "Для руководителя", labelEn: "Management AI" }
    ],
    ru: {
      h1: "Яндекс Метрика и CRM: сквозная аналитика",
      subtitle: "Яндекс Метрика и CRM: сквозная аналитика: меньше ручной работы, данные в системах учёта, измеримый ROI.",
      problems: ["Процесс держится на людях и чатах","Нет единого статуса задачи","Ошибки из-за ручного переноса","Руководитель видит результат слишком поздно"],
      deliverables: ["Карта процесса и KPI","Рабочий контур в production","Интеграции с CRM/документами","Регламент и обучение"],
      intro: ["Яндекс Метрика и CRM: сквозная аналитика — практический сценарий автоматизации под спрос Wordstat.","Сначала процесс и данные, затем интеграции и AI-слой.","Пилот обычно занимает 2–6 недель."],
      faq: [{"q":"С чего начать?","a":"С аудита одного узкого сценария и расчёта часов/денег."},{"q":"Нужен ли AI?","a":"Не всегда. Часто хватает workflow и интеграций."},{"q":"Какой бюджет?","a":"Пилот — от 150–400 тыс. ₽ в зависимости от интеграций."}],
    },
    en: {
      h1: "Yandex Metrica and CRM analytics",
      subtitle: "Yandex Metrica and CRM analytics: less manual work, data in systems of record, measurable ROI.",
      problems: ["The process depends on people and chats","No single task status","Errors from manual transfer","Leaders see results too late"],
      deliverables: ["Process map and KPIs","Production workflow","CRM/document integrations","Playbook and training"],
      intro: ["Yandex Metrica and CRM analytics is a practical automation scenario.","Process and data first, then integrations and optional AI.","Pilots usually take 2–6 weeks."],
      faq: [{"q":"Where to start?","a":"Audit one narrow scenario and calculate hours/money."},{"q":"Is AI required?","a":"Not always. Workflow and integrations are often enough."},{"q":"Budget?","a":"Pilots typically start from a fixed mid-market scope."}],
    },
  },
  {
    category: "integrations",
    slug: "telephony-crm",
    contentKey: "extra_telephony_crm",
    cluster: "integrations",
    serviceSlug: "crm-integration",
    coverImage: "/diagrams/crm-integration.svg",
    keywords: ["телефония crm","запись звонков"],
    related: [
      { href: "/integrations/crm", labelRu: "Внедрение CRM", labelEn: "CRM implementation" },
      { href: "/automation/sales", labelRu: "Автоматизация продаж", labelEn: "Sales automation" }
    ],
    ru: {
      h1: "Телефония и запись звонков в CRM",
      subtitle: "Телефония и запись звонков в CRM: меньше ручной работы, данные в системах учёта, измеримый ROI.",
      problems: ["Процесс держится на людях и чатах","Нет единого статуса задачи","Ошибки из-за ручного переноса","Руководитель видит результат слишком поздно"],
      deliverables: ["Карта процесса и KPI","Рабочий контур в production","Интеграции с CRM/документами","Регламент и обучение"],
      intro: ["Телефония и запись звонков в CRM — практический сценарий автоматизации под спрос Wordstat.","Сначала процесс и данные, затем интеграции и AI-слой.","Пилот обычно занимает 2–6 недель."],
      faq: [{"q":"С чего начать?","a":"С аудита одного узкого сценария и расчёта часов/денег."},{"q":"Нужен ли AI?","a":"Не всегда. Часто хватает workflow и интеграций."},{"q":"Какой бюджет?","a":"Пилот — от 150–400 тыс. ₽ в зависимости от интеграций."}],
    },
    en: {
      h1: "Telephony and call logging in CRM",
      subtitle: "Telephony and call logging in CRM: less manual work, data in systems of record, measurable ROI.",
      problems: ["The process depends on people and chats","No single task status","Errors from manual transfer","Leaders see results too late"],
      deliverables: ["Process map and KPIs","Production workflow","CRM/document integrations","Playbook and training"],
      intro: ["Telephony and call logging in CRM is a practical automation scenario.","Process and data first, then integrations and optional AI.","Pilots usually take 2–6 weeks."],
      faq: [{"q":"Where to start?","a":"Audit one narrow scenario and calculate hours/money."},{"q":"Is AI required?","a":"Not always. Workflow and integrations are often enough."},{"q":"Budget?","a":"Pilots typically start from a fixed mid-market scope."}],
    },
  },
  {
    category: "integrations",
    slug: "messengers-hub",
    contentKey: "extra_messengers_hub",
    cluster: "integrations",
    serviceSlug: "sales-ai-agent",
    coverImage: "/diagrams/sales-pipeline.svg",
    keywords: ["мессенджеры продажи","чат продажи"],
    related: [
      { href: "/automation/sales", labelRu: "Автоматизация продаж", labelEn: "Sales automation" },
      { href: "/automation/support", labelRu: "Поддержка", labelEn: "Support automation" }
    ],
    ru: {
      h1: "Единый хаб мессенджеров для продаж",
      subtitle: "Единый хаб мессенджеров для продаж: меньше ручной работы, данные в системах учёта, измеримый ROI.",
      problems: ["Процесс держится на людях и чатах","Нет единого статуса задачи","Ошибки из-за ручного переноса","Руководитель видит результат слишком поздно"],
      deliverables: ["Карта процесса и KPI","Рабочий контур в production","Интеграции с CRM/документами","Регламент и обучение"],
      intro: ["Единый хаб мессенджеров для продаж — практический сценарий автоматизации под спрос Wordstat.","Сначала процесс и данные, затем интеграции и AI-слой.","Пилот обычно занимает 2–6 недель."],
      faq: [{"q":"С чего начать?","a":"С аудита одного узкого сценария и расчёта часов/денег."},{"q":"Нужен ли AI?","a":"Не всегда. Часто хватает workflow и интеграций."},{"q":"Какой бюджет?","a":"Пилот — от 150–400 тыс. ₽ в зависимости от интеграций."}],
    },
    en: {
      h1: "Unified messengers hub for sales",
      subtitle: "Unified messengers hub for sales: less manual work, data in systems of record, measurable ROI.",
      problems: ["The process depends on people and chats","No single task status","Errors from manual transfer","Leaders see results too late"],
      deliverables: ["Process map and KPIs","Production workflow","CRM/document integrations","Playbook and training"],
      intro: ["Unified messengers hub for sales is a practical automation scenario.","Process and data first, then integrations and optional AI.","Pilots usually take 2–6 weeks."],
      faq: [{"q":"Where to start?","a":"Audit one narrow scenario and calculate hours/money."},{"q":"Is AI required?","a":"Not always. Workflow and integrations are often enough."},{"q":"Budget?","a":"Pilots typically start from a fixed mid-market scope."}],
    },
  },
  {
    category: "solutions",
    slug: "employee-assistant",
    contentKey: "extra_employee_assistant",
    cluster: "solutions",
    serviceSlug: "enterprise-ai-assistant",
    coverImage: "/diagrams/system-architecture.svg",
    keywords: ["ассистент сотрудников","корпоративный ассистент"],
    related: [
      { href: "/automation/knowledge-base", labelRu: "База знаний", labelEn: "Knowledge base" },
      { href: "/automation/hr", labelRu: "HR-автоматизация", labelEn: "HR automation" }
    ],
    ru: {
      h1: "Корпоративный ассистент для сотрудников",
      subtitle: "Корпоративный ассистент для сотрудников: меньше ручной работы, данные в системах учёта, измеримый ROI.",
      problems: ["Процесс держится на людях и чатах","Нет единого статуса задачи","Ошибки из-за ручного переноса","Руководитель видит результат слишком поздно"],
      deliverables: ["Карта процесса и KPI","Рабочий контур в production","Интеграции с CRM/документами","Регламент и обучение"],
      intro: ["Корпоративный ассистент для сотрудников — практический сценарий автоматизации под спрос Wordstat.","Сначала процесс и данные, затем интеграции и AI-слой.","Пилот обычно занимает 2–6 недель."],
      faq: [{"q":"С чего начать?","a":"С аудита одного узкого сценария и расчёта часов/денег."},{"q":"Нужен ли AI?","a":"Не всегда. Часто хватает workflow и интеграций."},{"q":"Какой бюджет?","a":"Пилот — от 150–400 тыс. ₽ в зависимости от интеграций."}],
    },
    en: {
      h1: "Employee corporate assistant",
      subtitle: "Employee corporate assistant: less manual work, data in systems of record, measurable ROI.",
      problems: ["The process depends on people and chats","No single task status","Errors from manual transfer","Leaders see results too late"],
      deliverables: ["Process map and KPIs","Production workflow","CRM/document integrations","Playbook and training"],
      intro: ["Employee corporate assistant is a practical automation scenario.","Process and data first, then integrations and optional AI.","Pilots usually take 2–6 weeks."],
      faq: [{"q":"Where to start?","a":"Audit one narrow scenario and calculate hours/money."},{"q":"Is AI required?","a":"Not always. Workflow and integrations are often enough."},{"q":"Budget?","a":"Pilots typically start from a fixed mid-market scope."}],
    },
  },
  {
    category: "solutions",
    slug: "manager-copilot",
    contentKey: "extra_manager_copilot",
    cluster: "solutions",
    serviceSlug: "sales-ai-agent",
    coverImage: "/diagrams/sales-pipeline.svg",
    keywords: ["копилот продаж","помощник менеджера"],
    related: [
      { href: "/automation/sales", labelRu: "Автоматизация продаж", labelEn: "Sales automation" },
      { href: "/integrations/crm", labelRu: "Внедрение CRM", labelEn: "CRM implementation" }
    ],
    ru: {
      h1: "Копилот для менеджера по продажам",
      subtitle: "Копилот для менеджера по продажам: меньше ручной работы, данные в системах учёта, измеримый ROI.",
      problems: ["Процесс держится на людях и чатах","Нет единого статуса задачи","Ошибки из-за ручного переноса","Руководитель видит результат слишком поздно"],
      deliverables: ["Карта процесса и KPI","Рабочий контур в production","Интеграции с CRM/документами","Регламент и обучение"],
      intro: ["Копилот для менеджера по продажам — практический сценарий автоматизации под спрос Wordstat.","Сначала процесс и данные, затем интеграции и AI-слой.","Пилот обычно занимает 2–6 недель."],
      faq: [{"q":"С чего начать?","a":"С аудита одного узкого сценария и расчёта часов/денег."},{"q":"Нужен ли AI?","a":"Не всегда. Часто хватает workflow и интеграций."},{"q":"Какой бюджет?","a":"Пилот — от 150–400 тыс. ₽ в зависимости от интеграций."}],
    },
    en: {
      h1: "Sales manager copilot",
      subtitle: "Sales manager copilot: less manual work, data in systems of record, measurable ROI.",
      problems: ["The process depends on people and chats","No single task status","Errors from manual transfer","Leaders see results too late"],
      deliverables: ["Process map and KPIs","Production workflow","CRM/document integrations","Playbook and training"],
      intro: ["Sales manager copilot is a practical automation scenario.","Process and data first, then integrations and optional AI.","Pilots usually take 2–6 weeks."],
      faq: [{"q":"Where to start?","a":"Audit one narrow scenario and calculate hours/money."},{"q":"Is AI required?","a":"Not always. Workflow and integrations are often enough."},{"q":"Budget?","a":"Pilots typically start from a fixed mid-market scope."}],
    },
  },
  {
    category: "solutions",
    slug: "document-qa",
    contentKey: "extra_document_qa",
    cluster: "solutions",
    serviceSlug: "document-processing",
    coverImage: "/diagrams/document-flow.svg",
    keywords: ["qa по договорам","вопросы по документам"],
    related: [
      { href: "/automation/documents", labelRu: "Документооборот", labelEn: "Document automation" },
      { href: "/automation/knowledge-base", labelRu: "База знаний", labelEn: "Knowledge base" }
    ],
    ru: {
      h1: "Q&A по договорам и вложениям сделки",
      subtitle: "Q&A по договорам и вложениям сделки: меньше ручной работы, данные в системах учёта, измеримый ROI.",
      problems: ["Процесс держится на людях и чатах","Нет единого статуса задачи","Ошибки из-за ручного переноса","Руководитель видит результат слишком поздно"],
      deliverables: ["Карта процесса и KPI","Рабочий контур в production","Интеграции с CRM/документами","Регламент и обучение"],
      intro: ["Q&A по договорам и вложениям сделки — практический сценарий автоматизации под спрос Wordstat.","Сначала процесс и данные, затем интеграции и AI-слой.","Пилот обычно занимает 2–6 недель."],
      faq: [{"q":"С чего начать?","a":"С аудита одного узкого сценария и расчёта часов/денег."},{"q":"Нужен ли AI?","a":"Не всегда. Часто хватает workflow и интеграций."},{"q":"Какой бюджет?","a":"Пилот — от 150–400 тыс. ₽ в зависимости от интеграций."}],
    },
    en: {
      h1: "Deal document Q&A",
      subtitle: "Deal document Q&A: less manual work, data in systems of record, measurable ROI.",
      problems: ["The process depends on people and chats","No single task status","Errors from manual transfer","Leaders see results too late"],
      deliverables: ["Process map and KPIs","Production workflow","CRM/document integrations","Playbook and training"],
      intro: ["Deal document Q&A is a practical automation scenario.","Process and data first, then integrations and optional AI.","Pilots usually take 2–6 weeks."],
      faq: [{"q":"Where to start?","a":"Audit one narrow scenario and calculate hours/money."},{"q":"Is AI required?","a":"Not always. Workflow and integrations are often enough."},{"q":"Budget?","a":"Pilots typically start from a fixed mid-market scope."}],
    },
  },
  {
    category: "solutions",
    slug: "onboarding-bot",
    contentKey: "extra_onboarding_bot",
    cluster: "solutions",
    serviceSlug: "enterprise-ai-assistant",
    coverImage: "/diagrams/system-architecture.svg",
    keywords: ["онбординг клиентов","бот онбординга"],
    related: [
      { href: "/automation/support", labelRu: "Поддержка", labelEn: "Support automation" },
      { href: "/automation/sales", labelRu: "Автоматизация продаж", labelEn: "Sales automation" }
    ],
    ru: {
      h1: "Бот онбординга клиентов",
      subtitle: "Бот онбординга клиентов: меньше ручной работы, данные в системах учёта, измеримый ROI.",
      problems: ["Процесс держится на людях и чатах","Нет единого статуса задачи","Ошибки из-за ручного переноса","Руководитель видит результат слишком поздно"],
      deliverables: ["Карта процесса и KPI","Рабочий контур в production","Интеграции с CRM/документами","Регламент и обучение"],
      intro: ["Бот онбординга клиентов — практический сценарий автоматизации под спрос Wordstat.","Сначала процесс и данные, затем интеграции и AI-слой.","Пилот обычно занимает 2–6 недель."],
      faq: [{"q":"С чего начать?","a":"С аудита одного узкого сценария и расчёта часов/денег."},{"q":"Нужен ли AI?","a":"Не всегда. Часто хватает workflow и интеграций."},{"q":"Какой бюджет?","a":"Пилот — от 150–400 тыс. ₽ в зависимости от интеграций."}],
    },
    en: {
      h1: "Customer onboarding bot",
      subtitle: "Customer onboarding bot: less manual work, data in systems of record, measurable ROI.",
      problems: ["The process depends on people and chats","No single task status","Errors from manual transfer","Leaders see results too late"],
      deliverables: ["Process map and KPIs","Production workflow","CRM/document integrations","Playbook and training"],
      intro: ["Customer onboarding bot is a practical automation scenario.","Process and data first, then integrations and optional AI.","Pilots usually take 2–6 weeks."],
      faq: [{"q":"Where to start?","a":"Audit one narrow scenario and calculate hours/money."},{"q":"Is AI required?","a":"Not always. Workflow and integrations are often enough."},{"q":"Budget?","a":"Pilots typically start from a fixed mid-market scope."}],
    },
  }
];
