import type { LandingSpec } from "@/lib/seo-catalog/types";

const IMG = {
  architecture: "/diagrams/system-architecture.svg",
  crm: "/diagrams/crm-integration.svg",
  sales: "/diagrams/sales-pipeline.svg",
  workflow: "/diagrams/workflow-automation.svg",
  docs: "/diagrams/document-flow.svg",
} as const;

const PRICING = { href: "/pricing", labelRu: "Цены", labelEn: "Pricing" };
const AI_BIZ = { href: "/ai/vnedrenie-iskusstvennogo-intellekta-v-biznes", labelRu: "Внедрение ИИ в бизнес", labelEn: "AI implementation" };
const AI_COST = { href: "/ai/stoimost-vnedreniya-ii", labelRu: "Стоимость внедрения ИИ", labelEn: "AI implementation cost" };
const PRIVATE_LLM = { href: "/ai/private-llm", labelRu: "Приватный LLM", labelEn: "Private LLM" };
const RAG = { href: "/solutions/rag-sistema-dlya-biznesa", labelRu: "RAG-система для бизнеса", labelEn: "RAG system for business" };

/**
 * Wordstat 2026-09-16 (data/wordstat-ai-it-buy-2026-09.csv): AI development and
 * IT-services queries with buy intent that had no dedicated page.
 */
export const CATALOG_LANDING_SPECS_AI_IT_BUY: LandingSpec[] = [
  {
    category: "ai",
    slug: "razrabotka-ii-reshenij",
    contentKey: "aib_ai_solutions_dev",
    cluster: "ai-corporate",
    serviceSlug: "enterprise-ai-assistant",
    coverImage: IMG.architecture,
    keywords: [
      "разработка ии решений",
      "разработка ии решений для бизнеса",
      "разработка решений на основе ии",
      "разработка ии систем",
      "заказная разработка ии",
      "разработка искусственного интеллекта на заказ",
      "компания разработчик ии решений",
      "разработка ии под ключ",
    ],
    caseStudySlugs: ["kaspersky-ai-assistant", "yandex-telemost-agent", "kp-llm-automation"],
    related: [
      { href: "/ai/razrabotka-ai-agentov", labelRu: "Разработка AI-агентов", labelEn: "AI agent development" },
      RAG,
      PRIVATE_LLM,
      { href: "/ai/kompanii-po-vnedreniyu-ii-moskva", labelRu: "Компании по внедрению ИИ в Москве", labelEn: "AI companies in Moscow" },
      AI_COST,
      PRICING,
    ],
    ru: {
      h1: "Разработка ИИ-решений для бизнеса под ключ: от идеи до production",
      subtitle:
        "Заказная разработка ИИ-систем на ваших данных: ассистенты, агенты, RAG, обработка документов, речевая аналитика, компьютерное зрение. Архитектура, модель, интеграции, развёртывание в вашем контуре. Discovery 2 недели, пилот 4–8 недель от 400 000 ₽.",
      problems: [
        "Готовые SaaS-инструменты не закрывают задачу: нужна логика под ваш процесс и ваши данные",
        "Внутренняя команда пробовала «сделать на ChatGPT» — прототип есть, в production не выходит",
        "Подрядчики предлагают «внедрить нейросеть» без архитектуры, метрик и ответственности за результат",
        "Данные нельзя отдавать во внешние API — нужно решение в закрытом контуре",
      ],
      deliverables: [
        "Discovery: постановка задачи, данные, метрика успеха, архитектура, смета с фиксированной ценой",
        "Разработка: модели (открытые, YandexGPT/GigaChat или API), пайплайны, RAG, агенты, интерфейсы, интеграции с CRM/1С/API",
        "Production: развёртывание on-premise или в российском облаке, мониторинг качества, журналирование, документация",
        "Передача: код, инфраструктура как код, обучение команды, сопровождение по SLA или передача in-house",
      ],
      intro: [
        "Разработка ИИ-решений — это инженерный проект, а не «подключить нейросеть». Результат зависит от данных, метрики и интеграции в процесс, поэтому мы начинаем с discovery: что именно должно измениться в бизнесе, на каких данных, как это проверить.",
        "Что разрабатываем: корпоративные ассистенты и RAG по документам, ИИ-агенты для продаж и поддержки, обработка документов (OCR + LLM), речевая аналитика, классификация и извлечение данных, компьютерное зрение для контроля качества, прогнозные модели на данных 1С и CRM.",
        "Стек: Python, open-source LLM (Qwen, Llama, Mistral), YandexGPT, GigaChat, vLLM, LangGraph, PostgreSQL/pgvector, Kubernetes, Yandex Cloud / Selectel / Cloud.ru / on-premise. Кейсы: ассистент для Kaspersky, агент для Яндекс Телемоста, генерация КП на LLM.",
      ],
      howWeSolve: [
        { title: "Discovery (2 недели)", text: "Интервью, аудит данных, прототип на выборке, метрика, архитектура, смета. Если ИИ не нужен — скажем и предложим классическую автоматизацию." },
        { title: "Пилот (4–8 недель)", text: "Рабочая версия на реальных данных в вашем контуре, приёмка по метрике (точность, время, доля автоматизации)." },
        { title: "Production и сопровождение", text: "Масштабирование, интеграции, мониторинг дрейфа качества, обновления моделей, SLA." },
      ],
      faq: [
        { q: "Сколько стоит разработка ИИ-решения?", a: "Discovery — от 150 000 ₽, пилот — от 400 000 ₽, production-система — от 1 000 000 ₽ в зависимости от объёма. Смета фиксируется после discovery." },
        { q: "Кому принадлежит код и модель?", a: "Заказчику. Передаём репозиторий, инфраструктуру и документацию; используемые открытые модели — по их лицензиям." },
        { q: "Можете доработать наш прототип?", a: "Да: аудит текущего решения, план доведения до production, оценка. Часто прототип остаётся, меняются данные, ретривер и интеграции." },
        { q: "Сроки?", a: "Discovery 2 недели, пилот 4–8 недель, production 2–4 месяца. Зависит от данных и количества интеграций." },
      ],
    },
    en: {
      h1: "Custom AI solution development: from idea to production",
      subtitle: "Bespoke AI systems on your data: assistants, agents, RAG, document processing, speech analytics, computer vision. Architecture, model, integrations, deployment in your perimeter. Discovery 2 weeks, pilot 4–8 weeks.",
      problems: ["SaaS tools do not fit the process", "In-house ChatGPT prototype never reaches production", "Vendors offer “a neural net” without metrics", "Data cannot leave the perimeter"],
      deliverables: ["Discovery: task, data, metric, architecture, fixed estimate", "Development: models, pipelines, RAG, agents, integrations", "Production: private deployment, monitoring, docs", "Handover: code, IaC, training, SLA"],
      intro: ["An engineering project, not “plug in a neural net”.", "Assistants, agents, document processing, speech analytics, CV, forecasting.", "Python, open LLMs, YandexGPT, GigaChat, vLLM, LangGraph, pgvector, Kubernetes."],
      howWeSolve: [{ title: "Discovery", text: "Interviews, data audit, prototype, metric, estimate." }, { title: "Pilot", text: "Working version on real data, acceptance by metric." }, { title: "Production", text: "Scale, integrations, monitoring, SLA." }],
      faq: [{ q: "Cost?", a: "Discovery, then pilot, then production; fixed after discovery." }, { q: "Who owns the code?", a: "The client." }, { q: "Timeline?", a: "2 weeks + 4–8 weeks + 2–4 months." }],
    },
  },
  {
    category: "ai",
    slug: "razrabotka-ai-agentov",
    contentKey: "aib_ai_agents_dev",
    cluster: "ai-corporate",
    serviceSlug: "sales-ai-agent",
    coverImage: IMG.workflow,
    keywords: [
      "разработка ai агентов",
      "разработка ии агентов",
      "разработка ai агентов для бизнеса",
      "ai агент для продаж",
      "ии агент для бизнеса заказать",
      "заказать разработку ии агента",
      "ai агент под ключ",
      "мультиагентные системы для бизнеса",
    ],
    caseStudySlugs: ["yandex-telemost-agent", "kp-llm-automation", "ai-sales-loop"],
    related: [
      { href: "/ai/ai-agents", labelRu: "ИИ-агенты для процессов", labelEn: "AI agents for processes" },
      { href: "/ai-agents", labelRu: "Что такое ИИ-агенты", labelEn: "What AI agents are" },
      { href: "/integrations/amocrm-ai-agent", labelRu: "ИИ-агент в amoCRM", labelEn: "AI agent in amoCRM" },
      { href: "/ai/razrabotka-ii-reshenij", labelRu: "Разработка ИИ-решений", labelEn: "AI solution development" },
      AI_COST,
      PRICING,
    ],
    ru: {
      h1: "Разработка AI-агентов для бизнеса: агент, который сам делает шаги в CRM, 1С и мессенджерах",
      subtitle:
        "Проектируем и разрабатываем ИИ-агентов, которые не просто отвечают, а выполняют процесс: квалифицируют лид и назначают встречу, собирают КП, заводят заявку в 1С, эскалируют инцидент. Инструменты, память, контроль и логи. Пилот 4–6 недель от 400 000 ₽.",
      problems: [
        "Чат-бот отвечает, но дальше всё руками: перенести в CRM, создать задачу, отправить КП",
        "Агенты из конструкторов ломаются на реальных данных и не имеют контроля действий",
        "Непонятно, где границы автономности: что агент может делать сам, а где нужен человек",
        "Нужен агент в своём контуре — без отправки данных клиентов и сделок в зарубежные API",
      ],
      deliverables: [
        "Проектирование агента: цель, инструменты (CRM, 1С, почта, календарь, API), правила и границы автономности, точки подтверждения человеком",
        "Разработка: оркестрация (LangGraph или собственный рантайм), память, вызов инструментов, обработка ошибок, тесты на сценариях",
        "Интеграции: amoCRM, Bitrix24, 1С, Telegram/WhatsApp, телефония, почта, Jira, внутренние API",
        "Эксплуатация: журнал действий, метрики, откат, мониторинг; развёртывание on-premise или в российском облаке",
      ],
      intro: [
        "AI-агент отличается от чат-бота тем, что у него есть инструменты и цель: он читает контекст, решает, какой шаг сделать, вызывает CRM или 1С, проверяет результат и идёт дальше — до завершения задачи или до точки, где нужен человек.",
        "Типовые агенты, которые мы разрабатываем: агент продаж (квалификация, встреча, КП, дожим), агент поддержки (тикет, база знаний, эскалация), агент бэк-офиса (заявки в 1С, согласования, документы), агент руководителя (сводки, протоколы, поручения), SOC-агент (разбор алертов, тикеты).",
        "Ключевое — контроль: каждое действие агента журналируется, критичные шаги (отправка КП, изменение суммы сделки, платёж) требуют подтверждения. Кейс — агент для Яндекс Телемоста и генерация КП на LLM в портфолио.",
      ],
      howWeSolve: [
        { title: "Проектирование", text: "Сценарий, инструменты, правила, метрика. Прототип на 10–20 реальных кейсах за 1–2 недели." },
        { title: "Пилот", text: "Агент в вашем контуре на одном процессе с подтверждением критичных действий. Метрика — доля задач, доведённых до конца без человека." },
        { title: "Production", text: "Расширение инструментов и сценариев, снятие подтверждений по мере доверия, мониторинг, SLA." },
      ],
      faq: [
        { q: "Сколько стоит разработка AI-агента?", a: "Пилот одного агента с 2–3 инструментами — от 400 000 ₽. Мультиагентная система с несколькими процессами — от 1 000 000 ₽." },
        { q: "На каких моделях работают агенты?", a: "Открытые модели в контуре (Qwen, Llama), YandexGPT/GigaChat или зарубежные API — по вашей политике данных. Модель можно заменить без переписывания агента." },
        { q: "Что если агент ошибётся?", a: "Критичные действия подтверждает человек, все шаги журналируются, есть откат. Автономность расширяем постепенно по метрикам." },
      ],
    },
    en: {
      h1: "AI agent development for business: an agent that acts in CRM, 1C and messengers",
      subtitle: "We design and build AI agents that execute a process: qualify a lead and book a meeting, assemble a proposal, create a 1C request, escalate an incident. Tools, memory, control and logs. Pilot in 4–6 weeks.",
      problems: ["Chatbot answers, the rest is manual", "No-code agents break on real data", "Unclear autonomy boundaries", "Need an agent inside the perimeter"],
      deliverables: ["Agent design: goal, tools, rules, human checkpoints", "Development: orchestration, memory, tool calls, tests", "Integrations: amoCRM, Bitrix24, 1C, messengers, telephony, Jira", "Operations: action log, metrics, rollback, private deployment"],
      intro: ["An agent has tools and a goal: read context, decide, act, verify, continue.", "Sales, support, back-office, executive and SOC agents.", "Control: every action logged, critical steps confirmed."],
      howWeSolve: [{ title: "Design", text: "Scenario, tools, rules, prototype on real cases." }, { title: "Pilot", text: "One process with confirmations, metric — tasks completed end-to-end." }, { title: "Production", text: "More tools, fewer confirmations, monitoring, SLA." }],
      faq: [{ q: "Cost?", a: "Single agent pilot first; multi-agent system after." }, { q: "Models?", a: "Open models, YandexGPT/GigaChat or foreign APIs per policy." }, { q: "Mistakes?", a: "Confirmations, logs, rollback." }],
    },
  },
  {
    category: "solutions",
    slug: "ii-bot-dlya-biznesa",
    contentKey: "aib_ai_bot_business",
    cluster: "chat-assistant",
    serviceSlug: "enterprise-ai-assistant",
    coverImage: IMG.crm,
    keywords: [
      "ии бот для бизнеса",
      "ии чат бот для бизнеса",
      "чат бот с ии для бизнеса",
      "ии бот для сайта",
      "ии бот для телеграм бизнес",
      "умный чат бот для бизнеса",
      "нейросетевой чат бот для компании",
      "разработка ии бота",
    ],
    caseStudySlugs: ["support-knowledge-base", "ai-sales-loop", "kaspersky-ai-assistant"],
    related: [
      { href: "/automation/first-line-chatbot", labelRu: "Чат-бот первой линии", labelEn: "First-line chatbot" },
      { href: "/solutions/knowledge-chatbot", labelRu: "Чат-бот по базе знаний", labelEn: "Knowledge chatbot" },
      { href: "/integrations/telegram-crm", labelRu: "Telegram + CRM", labelEn: "Telegram + CRM" },
      { href: "/integrations/whatsapp-crm", labelRu: "WhatsApp + CRM", labelEn: "WhatsApp + CRM" },
      RAG,
      PRICING,
    ],
    ru: {
      h1: "ИИ-бот для бизнеса: отвечает по вашей базе, квалифицирует и передаёт в CRM",
      subtitle:
        "Не бот по кнопкам, а ИИ-чат-бот на ваших документах, каталоге и правилах: сайт, Telegram, WhatsApp, VK, Авито. Понимает вопрос своими словами, отвечает с источником, записывает, создаёт сделку в amoCRM/Bitrix24, передаёт оператору. Запуск 3–4 недели от 250 000 ₽.",
      problems: [
        "Кнопочный бот раздражает: клиент пишет вопрос — получает меню",
        "Операторы отвечают на одни и те же 50 вопросов, ночью и в выходные — никто",
        "Бот на ChatGPT «из коробки» выдумывает цены и условия, которых нет",
        "Переписка в мессенджерах не попадает в CRM — лиды теряются",
      ],
      deliverables: [
        "ИИ-бот на RAG по вашей базе: услуги, цены, условия, FAQ, регламенты — ответы с источником, «не знаю» вместо выдумки",
        "Каналы: сайт, Telegram, WhatsApp, VK, Авито, Max — единая логика, передача оператору с историей",
        "Действия: квалификация, запись/бронирование, заявка, статус заказа из 1С/CRM, создание сделки в amoCRM/Bitrix24",
        "Панель: диалоги, доля закрытых без оператора, частые вопросы без ответа — для пополнения базы",
      ],
      intro: [
        "«ИИ-бот для бизнеса» окупается, если он снимает нагрузку с людей и не портит впечатление клиента. Для этого он должен знать ваш бизнес (база знаний), уметь делать действия (запись, заявка, статус) и честно передавать человеку, когда не уверен.",
        "Мы строим ботов на RAG-индексе по вашим материалам и подключаем к CRM, учёту и календарю. Модель — YandexGPT, GigaChat или открытая в вашем контуре; данные клиентов не уходят в зарубежные API.",
        "Типовые внедрения: поддержка интернет-магазина, запись в клинику/салон/автосервис, первичная консультация в B2B, HR-бот для сотрудников. Кейс — CRM + Telegram + Google Sheets для малого бизнеса в портфолио.",
      ],
      howWeSolve: [
        { title: "База и сценарии", text: "Собираем материалы, разбираем 200–500 реальных диалогов, определяем действия и точки передачи оператору." },
        { title: "Запуск на 1–2 каналах", text: "Бот, интеграции, панель. Тест на реальном трафике с оператором «за спиной». Метрика — доля закрытых и CSAT." },
        { title: "Масштабирование", text: "Все каналы, новые действия, пополнение базы по вопросам без ответа, отчёты." },
      ],
      faq: [
        { q: "Сколько стоит ИИ-чат-бот для бизнеса?", a: "От 250 000 ₽ за бота на 1–2 каналах с базой знаний и CRM. С действиями (запись, статус заказа из 1С) и несколькими каналами — от 450 000 ₽. Плюс стоимость модели/хостинга — от 5 000 ₽ в месяц." },
        { q: "Чем это лучше конструктора ботов?", a: "Конструктор — кнопки и сценарии. ИИ-бот понимает свободный вопрос, отвечает по вашей базе с источником и умеет действия в CRM/1С. Конструкторы используем для простых случаев." },
        { q: "Как бот не будет выдумывать?", a: "Отвечает только по индексу ваших материалов, каждый ответ с источником; при отсутствии данных — передача оператору. Проверяем на контрольных вопросах." },
      ],
    },
    en: {
      h1: "AI bot for business: answers from your base, qualifies and hands over to CRM",
      subtitle: "Not a button bot: an AI chatbot on your documents, catalogue and rules across website, Telegram, WhatsApp, VK, Avito. Answers with a source, books, creates deals in amoCRM/Bitrix24, hands over to an operator. Launch in 3–4 weeks.",
      problems: ["Button bots annoy customers", "Same 50 questions, nobody at night", "Out-of-the-box ChatGPT invents prices", "Messenger chats never reach CRM"],
      deliverables: ["RAG bot with sourced answers", "All channels with operator handover", "Actions: qualification, booking, order status, CRM deals", "Dashboard: dialogs, resolution rate, unanswered questions"],
      intro: ["Pays off when it removes load and keeps the experience good.", "RAG over your materials, connected to CRM, inventory and calendar.", "Typical: e-commerce support, clinic booking, B2B first contact, HR bot."],
      howWeSolve: [{ title: "Base and scenarios", text: "Materials, 200–500 real dialogs, actions, handover points." }, { title: "Launch on 1–2 channels", text: "Real traffic with an operator behind." }, { title: "Scale", text: "All channels, more actions, reports." }],
      faq: [{ q: "Cost?", a: "Base bot first; actions and more channels after; plus hosting." }, { q: "Vs bot builders?", a: "Free-form questions, sourced answers, CRM/1C actions." }, { q: "Hallucinations?", a: "Index-only answers, sources, handover." }],
    },
  },
  {
    category: "ai",
    slug: "gpt-dlya-biznesa",
    contentKey: "aib_gpt_business",
    cluster: "ai-corporate",
    serviceSlug: "private-llm-gigachat",
    coverImage: IMG.architecture,
    keywords: [
      "gpt для бизнеса",
      "yandexgpt для бизнеса",
      "gigachat для бизнеса",
      "внедрение gpt в бизнес",
      "chatgpt для бизнеса внедрение",
      "gpt для компании",
      "yandexgpt внедрение",
      "gigachat внедрение в компании",
      "корпоративный gpt",
    ],
    caseStudySlugs: ["kp-llm-automation", "erp-moysklad-chatgpt-ux", "kaspersky-ai-assistant"],
    related: [
      PRIVATE_LLM,
      { href: "/ai/corporate-neural-net", labelRu: "Корпоративная нейросеть", labelEn: "Corporate neural net" },
      { href: "/claude", labelRu: "Claude для бизнеса", labelEn: "Claude for business" },
      { href: "/ai/ii-pomoshchnik-na-qwen", labelRu: "ИИ-помощник на Qwen", labelEn: "Qwen AI assistant" },
      RAG,
      { href: "/ai/doobuchenie-llm", labelRu: "Дообучение LLM", labelEn: "LLM fine-tuning" },
      PRICING,
    ],
    ru: {
      h1: "GPT для бизнеса: внедрение YandexGPT, GigaChat, ChatGPT или открытой модели в процессы компании",
      subtitle:
        "Подбираем модель под задачу и политику данных (YandexGPT, GigaChat, Claude/GPT через API или Qwen/Llama в контуре), подключаем к вашим документам, CRM и 1С, встраиваем в процессы: КП, документы, поддержка, аналитика. Пилот 3–5 недель от 300 000 ₽.",
      problems: [
        "Сотрудники уже пользуются ChatGPT с личных аккаунтов — данные компании уходят наружу",
        "Купили доступ к YandexGPT/GigaChat, но «в чате» пользы мало: модель не знает ваших документов и процессов",
        "Непонятно, какую модель выбрать: российскую, зарубежную или открытую — и что разрешает ИБ",
        "Хотят «внедрить GPT», но нет метрики: где именно и сколько это сэкономит",
      ],
      deliverables: [
        "Выбор модели: сравнение YandexGPT, GigaChat, Claude/GPT, Qwen/Llama на ваших задачах — качество, цена, требования ИБ",
        "Корпоративный доступ: единый интерфейс для сотрудников с вашими документами (RAG), ролями, журналом и лимитами",
        "Встраивание в процессы: генерация КП и писем из CRM, разбор документов, ответы поддержки, отчёты — через API и интеграции",
        "Контур: российское облако или on-premise, политика данных, обучение сотрудников работе с ИИ",
      ],
      intro: [
        "«GPT для бизнеса» — это не подписка на чат. Эффект появляется, когда модель знает ваши данные и встроена в процесс: менеджер получает КП из CRM, юрист — проверку договора, поддержка — ответ по базе знаний. Мы делаем именно это, с любой моделью.",
        "Российские модели (YandexGPT, GigaChat) подходят для большинства офисных задач и проще по ИБ и 152-ФЗ. Открытые модели (Qwen, Llama) — когда данные не должны покидать сервер. Зарубежные API (Claude, GPT) — для сложных задач при разрешении политики данных. Выбираем по тесту на ваших примерах.",
        "Кейсы: генерация КП на LLM, интерфейс МойСклад + ChatGPT, ассистент для Kaspersky. Партнёр Yandex Cloud, Selectel, Cloud.ru.",
      ],
      howWeSolve: [
        { title: "Тест моделей на ваших задачах", text: "20–50 реальных примеров, сравнение 2–3 моделей по качеству и цене, выбор с учётом ИБ. 1–2 недели." },
        { title: "Пилот", text: "Корпоративный доступ с вашими документами или один процесс с API-интеграцией. Метрика — время задачи и качество результата." },
        { title: "Масштабирование", text: "Новые процессы, роли и лимиты, мониторинг затрат на токены, обучение сотрудников." },
      ],
      faq: [
        { q: "Сколько стоит внедрение GPT в компании?", a: "Тест моделей — от 100 000 ₽, пилот — от 300 000 ₽. Стоимость токенов/лицензий — отдельно вендору, обычно 10 000–100 000 ₽ в месяц на компанию среднего размера." },
        { q: "YandexGPT или GigaChat?", a: "Зависит от задачи: тестируем обе на ваших примерах. По опыту, для документов и КП результаты сопоставимы; разница в цене, лимитах и интеграциях." },
        { q: "Можно ли ChatGPT/Claude в российской компании?", a: "Технически — через API; юридически — зависит от данных (персональные и коммерческая тайна — нет). Для таких данных — российские или открытые модели в контуре." },
      ],
    },
    en: {
      h1: "GPT for business: rolling out YandexGPT, GigaChat, ChatGPT or an open model into company processes",
      subtitle: "We pick the model for the task and data policy, connect it to your documents, CRM and 1C, and embed it into processes: proposals, documents, support, analytics. Pilot in 3–5 weeks.",
      problems: ["Employees use personal ChatGPT — data leaks", "YandexGPT/GigaChat bought but useless in chat", "Which model does security allow?", "No metric for “implement GPT”"],
      deliverables: ["Model comparison on your tasks", "Corporate access with RAG, roles, logs, limits", "Process embedding via API", "Russian cloud or on-premise, data policy, training"],
      intro: ["Not a chat subscription: value appears when the model knows your data inside a process.", "Russian, open or foreign models — chosen by test.", "Cases: LLM proposals, MoySklad + ChatGPT, Kaspersky assistant."],
      howWeSolve: [{ title: "Model test", text: "20–50 real examples, 2–3 models, security fit." }, { title: "Pilot", text: "Corporate access or one process integration." }, { title: "Scale", text: "More processes, cost monitoring, training." }],
      faq: [{ q: "Cost?", a: "Model test, then pilot; tokens billed by vendor." }, { q: "YandexGPT or GigaChat?", a: "Test both on your examples." }, { q: "ChatGPT in Russia?", a: "Via API, only for non-sensitive data." }],
    },
  },
  {
    category: "ai",
    slug: "doobuchenie-llm",
    contentKey: "aib_llm_finetune",
    cluster: "ai-tech",
    serviceSlug: "private-llm-gigachat",
    coverImage: IMG.architecture,
    keywords: [
      "дообучение llm",
      "дообучение языковой модели",
      "обучение нейросети на своих данных",
      "fine tuning llm на заказ",
      "дообучение нейросети под бизнес",
      "обучение ии на данных компании",
      "дообучение gpt на своих данных",
      "lora дообучение",
    ],
    caseStudySlugs: ["kaspersky-ai-assistant", "kp-llm-automation"],
    related: [
      RAG,
      PRIVATE_LLM,
      { href: "/ai/gpt-dlya-biznesa", labelRu: "GPT для бизнеса", labelEn: "GPT for business" },
      { href: "/ai/mashinnoe-obuchenie-dlya-biznesa", labelRu: "Машинное обучение для бизнеса", labelEn: "ML for business" },
      { href: "/ai-kubernetes", labelRu: "AI на Kubernetes", labelEn: "AI on Kubernetes" },
      PRICING,
    ],
    ru: {
      h1: "Дообучение LLM на данных компании: когда нужен fine-tuning, а когда хватит RAG",
      subtitle:
        "Обучаем открытые модели (Qwen, Llama, Mistral, T-lite, YandexGPT через Yandex Cloud) на ваших данных: стиль, домен, формат ответа, классификация. Честно говорим, когда дообучение не нужно и задачу решает RAG + промпты. Оценка 1–2 недели, дообучение от 400 000 ₽.",
      problems: [
        "Модель «не говорит на языке» вашего домена: термины, стиль, формат документов",
        "Промпты разрослись до страниц, качество нестабильно, токены дорогие",
        "Нужна маленькая быстрая модель в контуре вместо большого API — без потери качества на вашей задаче",
        "Подрядчик предлагает «обучить нейросеть на ваших данных» там, где хватило бы поиска по документам",
      ],
      deliverables: [
        "Оценка: нужен ли fine-tuning — сравнение RAG, промптов и дообучения на вашей выборке с метриками",
        "Датасет: сбор, очистка, разметка, аугментация из ваших документов, переписки, тикетов — с учётом ПДн и коммерческой тайны",
        "Дообучение: LoRA/QLoRA или полное, на GPU в российском облаке или on-premise; оценка на holdout, сравнение с базовой моделью",
        "Развёртывание: vLLM/TGI, API, мониторинг качества, план переобучения при обновлении данных",
      ],
      intro: [
        "Дообучение LLM решает три класса задач: стиль и формат (модель пишет как ваш отдел), узкий домен (термины, сокращения, внутренние сущности) и специализация (классификация, извлечение, короткие ответы малой моделью). Для «ответов по документам» дообучение обычно не нужно — работает RAG, и мы так и скажем.",
        "Процесс: сначала baseline на RAG и промптах, затем измеряем разрыв на вашей выборке. Если разрыв есть — собираем датасет (обычно 1–10 тысяч примеров), дообучаем LoRA на открытой модели, сравниваем на holdout и в production-условиях.",
        "Инфраструктура: GPU в Yandex Cloud, Selectel, Cloud.ru или ваши серверы; модели Qwen 2.5/3, Llama 3, Mistral, T-lite/T-pro, YandexGPT Fine-tuning. Данные не покидают выбранный контур.",
      ],
      howWeSolve: [
        { title: "Оценка и baseline", text: "Выборка 100–300 примеров, RAG + промпты, метрики. Решение: дообучать или нет. 1–2 недели." },
        { title: "Датасет и обучение", text: "Сбор и разметка, LoRA/QLoRA, эксперименты, holdout. 3–6 недель." },
        { title: "Развёртывание", text: "Инференс в контуре, API, мониторинг, регламент переобучения." },
      ],
      faq: [
        { q: "Сколько стоит дообучение LLM?", a: "Оценка — от 150 000 ₽ (часто заканчивается выводом «достаточно RAG»). Дообучение с датасетом и развёртыванием — от 400 000 ₽ плюс GPU-часы." },
        { q: "Сколько данных нужно?", a: "Для стиля и формата — от 500–1 000 примеров; для классификации — от 2 000; для домена — десятки тысяч фрагментов текста. Помогаем собрать из существующих документов." },
        { q: "RAG или fine-tuning?", a: "RAG — когда нужны актуальные факты из документов. Fine-tuning — когда нужны стиль, формат, узкий домен или маленькая быстрая модель. Часто — оба вместе." },
      ],
    },
    en: {
      h1: "LLM fine-tuning on company data: when you need it and when RAG is enough",
      subtitle: "We train open models (Qwen, Llama, Mistral, T-lite, YandexGPT via Yandex Cloud) on your data: style, domain, output format, classification. We say when fine-tuning is unnecessary. Assessment 1–2 weeks.",
      problems: ["Model does not speak your domain", "Prompts grew to pages, quality unstable", "Need a small fast model in-perimeter", "Vendors sell fine-tuning where search would do"],
      deliverables: ["Assessment: RAG vs prompts vs fine-tuning with metrics", "Dataset: collection, cleaning, labelling", "LoRA/QLoRA or full training on GPU in Russian cloud or on-premise", "Deployment: vLLM/TGI, API, monitoring, retraining plan"],
      intro: ["Three task classes: style, narrow domain, specialisation. Document Q&A usually needs RAG, not fine-tuning.", "Baseline first, then measure the gap, then dataset and LoRA.", "GPU in Yandex Cloud, Selectel, Cloud.ru or your servers."],
      howWeSolve: [{ title: "Assessment", text: "100–300 examples, baseline, decision." }, { title: "Dataset and training", text: "LoRA/QLoRA, experiments, holdout." }, { title: "Deployment", text: "Inference, API, monitoring." }],
      faq: [{ q: "Cost?", a: "Assessment first; training plus GPU hours after." }, { q: "How much data?", a: "From 500–1,000 examples for style; more for domain." }, { q: "RAG or fine-tuning?", a: "Often both." }],
    },
  },
  {
    category: "ai",
    slug: "mashinnoe-obuchenie-dlya-biznesa",
    contentKey: "aib_ml_business",
    cluster: "ai-tech",
    serviceSlug: "ai-discovery-roadmap",
    coverImage: IMG.architecture,
    keywords: [
      "машинное обучение для бизнеса",
      "машинное обучение в бизнесе внедрение",
      "ml для бизнеса",
      "разработка ml моделей на заказ",
      "прогнозная аналитика для бизнеса",
      "прогнозирование спроса машинное обучение",
      "ml консалтинг",
      "data science для бизнеса",
    ],
    caseStudySlugs: ["elia-suite", "finance-ops-slack-airtable"],
    related: [
      { href: "/services/ai-consulting", labelRu: "ML и data-консультация", labelEn: "ML and data consulting" },
      { href: "/ai/ai-audit", labelRu: "AI-аудит", labelEn: "AI audit" },
      { href: "/ai/doobuchenie-llm", labelRu: "Дообучение LLM", labelEn: "LLM fine-tuning" },
      { href: "/automation/ceo-dashboard", labelRu: "Дашборд руководителя", labelEn: "CEO dashboard" },
      AI_BIZ,
      PRICING,
    ],
    ru: {
      h1: "Машинное обучение для бизнеса: прогноз спроса, отток, скоринг и аномалии на данных 1С и CRM",
      subtitle:
        "Классические ML-задачи, которые окупаются у среднего бизнеса: прогноз продаж и остатков, отток клиентов, скоринг лидов и дебиторки, поиск аномалий в платежах и производстве. Данные из 1С, CRM, Excel. Discovery 2 недели, модель в production 6–10 недель от 400 000 ₽.",
      problems: [
        "Закупки планируются «по ощущениям»: то дефицит, то замороженные деньги на складе",
        "Клиенты уходят молча — узнаёте по факту, когда возвращать уже поздно",
        "Менеджеры звонят всем лидам одинаково, хотя 20% дают 80% выручки",
        "Данные есть в 1С и CRM, но никто их не использует — отчёты только «по прошлому»",
      ],
      deliverables: [
        "Discovery: данные, гипотезы, оценка достижимой точности на исторических данных, экономика — до разработки",
        "Модели: прогноз спроса/остатков, отток, скоринг лидов и дебиторки, аномалии, рекомендации — на ваших данных из 1С, CRM, BI",
        "Внедрение в процесс: прогноз в 1С/Excel закупщику, скоринг в карточке сделки, алерты в Telegram — не «отчёт data scientist’а»",
        "Эксплуатация: переобучение по расписанию, мониторинг точности, документация, передача in-house или SLA",
      ],
      intro: [
        "«Машинное обучение для бизнеса» — это не обязательно нейросети и LLM. Для прогноза спроса, оттока и скоринга работают классические модели (градиентный бустинг, временные ряды), которым нужна история продаж и сделок из 1С и CRM — она у вас уже есть.",
        "Мы начинаем с discovery: проверяем, есть ли сигнал в данных, и считаем экономику — сколько даст +10% точности прогноза или предупреждение об оттоке за месяц. Только после этого разрабатываем модель и встраиваем её туда, где принимается решение.",
        "Стек: Python, CatBoost/LightGBM, Prophet/статистические модели, PostgreSQL, ClickHouse, Airflow, интеграции с 1С, Bitrix24, amoCRM, DataLens/Power BI. Развёртывание в российском облаке или on-premise.",
      ],
      howWeSolve: [
        { title: "Discovery (2 недели)", text: "Аудит данных, гипотезы, бэктест на истории, оценка эффекта. Решение: делать или нет, и что первым." },
        { title: "Модель и пилот", text: "Разработка, валидация на holdout, пилот в процессе (например, прогноз для 20% SKU) с измерением эффекта." },
        { title: "Production", text: "Интеграция в 1С/CRM/BI, переобучение, мониторинг, обучение аналитиков заказчика." },
      ],
      faq: [
        { q: "Сколько стоит ML-проект для бизнеса?", a: "Discovery — от 150 000 ₽, модель в production — от 400 000 ₽. Типовой проект по прогнозу спроса или оттоку — 600 000–1 200 000 ₽." },
        { q: "Сколько данных нужно?", a: "Для прогноза спроса — 1,5–2 года истории продаж по SKU; для оттока — 500+ клиентов с историей. Если данных мало — скажем на discovery." },
        { q: "Чем это отличается от BI?", a: "BI показывает, что было. ML предсказывает, что будет, и рекомендует действие: сколько закупить, кому позвонить, какой платёж проверить." },
      ],
    },
    en: {
      h1: "Machine learning for business: demand forecasting, churn, scoring and anomalies on 1C and CRM data",
      subtitle: "Classic ML that pays off for mid-size businesses: sales and stock forecasts, churn, lead and receivables scoring, anomaly detection. Data from 1C, CRM, Excel. Discovery 2 weeks, production in 6–10 weeks.",
      problems: ["Purchasing by gut feeling", "Customers leave silently", "All leads called the same way", "Data sits unused in 1C and CRM"],
      deliverables: ["Discovery: data, hypotheses, achievable accuracy, economics", "Models on your data", "Embedded where decisions are made", "Retraining, monitoring, handover"],
      intro: ["Not necessarily neural nets: gradient boosting and time series on your history.", "Discovery first: is there a signal, what is it worth.", "Python, CatBoost, Prophet, PostgreSQL, ClickHouse, Airflow, 1C, BI."],
      howWeSolve: [{ title: "Discovery", text: "Data audit, backtest, effect estimate." }, { title: "Model and pilot", text: "Validation, pilot on part of the process." }, { title: "Production", text: "Integration, retraining, monitoring." }],
      faq: [{ q: "Cost?", a: "Discovery first; production model after." }, { q: "How much data?", a: "1.5–2 years of sales history; 500+ customers for churn." }, { q: "Vs BI?", a: "BI shows the past; ML predicts and recommends." }],
    },
  },
  {
    category: "solutions",
    slug: "it-konsalting",
    contentKey: "aib_it_consulting",
    cluster: "consulting",
    serviceSlug: "ai-discovery-roadmap",
    coverImage: IMG.architecture,
    keywords: [
      "it консалтинг",
      "ит консалтинг",
      "it консалтинг для бизнеса",
      "ит аудит компании",
      "аудит it инфраструктуры компании",
      "it консалтинг москва",
      "консалтинг по автоматизации бизнеса",
      "ит стратегия для компании",
    ],
    caseStudySlugs: ["elia-suite", "crm-1c-sync"],
    related: [
      { href: "/audit", labelRu: "Аудит процессов и ИИ", labelEn: "Process and AI audit" },
      { href: "/process-review", labelRu: "Process review", labelEn: "Process review" },
      { href: "/solutions/cifrovizaciya-biznesa", labelRu: "Цифровизация бизнеса", labelEn: "Business digitalisation" },
      { href: "/for-cio", labelRu: "Для CIO", labelEn: "For CIO" },
      { href: "/ai/ai-audit", labelRu: "AI-аудит", labelEn: "AI audit" },
      PRICING,
    ],
    ru: {
      h1: "IT-консалтинг для бизнеса: аудит систем и процессов, ИТ-стратегия и план автоматизации с бюджетом",
      subtitle:
        "Практический ИТ-консалтинг от интегратора, а не от «слайдов»: аудит CRM, 1С, интеграций и инфраструктуры, карта процессов и потерь, план автоматизации и внедрения ИИ на 6–12 месяцев со сметой и приоритетами. 2–4 недели, от 150 000 ₽.",
      problems: [
        "Десяток систем (CRM, 1С, Excel, мессенджеры) не связаны — данные вводятся по 3 раза",
        "Подрядчики предлагают «внедрить всё», а бюджет ограничен: непонятно, что даст эффект первым",
        "ИТ-инфраструктура выросла стихийно: нет схемы, документации, владельцев, рисков ИБ",
        "Собственник хочет «цифровизацию и ИИ», но нет плана, метрик и ответственного",
      ],
      deliverables: [
        "Аудит ИТ-ландшафта: системы, интеграции, данные, инфраструктура, лицензии, ИБ — схема «как есть» и риски",
        "Карта процессов: где теряются часы и деньги, что автоматизировать, где нужен ИИ, а где — регламент",
        "ИТ-стратегия и дорожная карта на 6–12 месяцев: проекты, приоритеты, бюджет, сроки, метрики, ответственные",
        "Технические задания на первые проекты и критерии выбора подрядчиков — можно реализовать с нами или с другими",
      ],
      intro: [
        "IT-консалтинг полезен, когда решения принимаются на основе того, как компания реально работает, а не по презентации вендора. Мы — интегратор с production-опытом в CRM, 1С, ИИ и облаках, поэтому в дорожной карте только то, что мы сами умеем внедрять и оценивать.",
        "Формат: интервью с руководителями и ключевыми сотрудниками, доступ к системам «только чтение», разбор данных и интеграций, воркшоп по приоритетам. Результат — документ с схемой, картой потерь, планом и бюджетом, который можно отдать в работу.",
        "Для компаний 30–500 сотрудников в Москве и регионах: производство, дистрибуция, услуги, e-commerce, строительство. Работаем с CIO, COO и собственниками.",
      ],
      howWeSolve: [
        { title: "Диагностика (1–2 недели)", text: "Интервью, инвентаризация систем и интеграций, анализ данных, ИБ-риски. Схема «как есть»." },
        { title: "Проектирование (1–2 недели)", text: "Карта процессов и потерь, целевая архитектура, приоритизация проектов по эффекту и стоимости." },
        { title: "Дорожная карта и ТЗ", text: "План на 6–12 месяцев с бюджетом, ТЗ на первые проекты, критерии выбора подрядчиков, метрики." },
      ],
      faq: [
        { q: "Сколько стоит IT-консалтинг?", a: "Экспресс-аудит одной области (CRM или 1С или ИИ-готовность) — от 150 000 ₽, 2 недели. Полный ИТ-аудит с дорожной картой — от 400 000 ₽, 4 недели." },
        { q: "Обязательно ли потом внедрять с вами?", a: "Нет. ТЗ и дорожная карта — ваши, можно реализовать с любым подрядчиком. Многие продолжают с нами, потому что план уже согласован." },
        { q: "Нужен ли выезд в офис?", a: "Для компаний в Москве — 1–2 очные сессии; остальное онлайн. Для регионов — полностью удалённо или выезд по договорённости." },
      ],
    },
    en: {
      h1: "IT consulting for business: systems and process audit, IT strategy and an automation plan with budget",
      subtitle: "Practical IT consulting from an integrator: audit of CRM, 1C, integrations and infrastructure, process and loss map, a 6–12 month automation and AI roadmap with estimate and priorities. 2–4 weeks.",
      problems: ["Ten disconnected systems, triple data entry", "Vendors offer everything, budget is limited", "Infrastructure grew ad hoc", "Owner wants digitalisation and AI without a plan"],
      deliverables: ["IT landscape audit with as-is diagram and risks", "Process map: where hours and money are lost", "6–12 month roadmap with budget, timeline, metrics", "Specs for first projects and vendor criteria"],
      intro: ["Decisions based on how the company actually works.", "Interviews, read-only access, data and integration review, priority workshop.", "For companies of 30–500 employees."],
      howWeSolve: [{ title: "Diagnostics", text: "Interviews, inventory, data, security risks." }, { title: "Design", text: "Process map, target architecture, prioritisation." }, { title: "Roadmap and specs", text: "Plan, budget, specs, metrics." }],
      faq: [{ q: "Cost?", a: "Express audit of one area first; full audit with roadmap after." }, { q: "Must we implement with you?", a: "No." }, { q: "On-site?", a: "1–2 sessions in Moscow, rest online." }],
    },
  },
  {
    category: "solutions",
    slug: "cifrovizaciya-biznesa",
    contentKey: "aib_digitalisation",
    cluster: "consulting",
    serviceSlug: "business-process-automation",
    coverImage: IMG.workflow,
    keywords: [
      "цифровизация бизнеса",
      "цифровизация бизнеса компании",
      "услуги цифровой трансформации бизнеса",
      "цифровая трансформация услуги",
      "цифровизация бизнес процессов компании",
      "решения для цифровизации бизнеса",
      "цифровизация малого бизнеса",
      "автоматизация и цифровизация бизнеса",
    ],
    caseStudySlugs: ["elia-suite", "crm-1c-sync", "support-knowledge-base"],
    related: [
      { href: "/solutions/it-konsalting", labelRu: "IT-консалтинг", labelEn: "IT consulting" },
      { href: "/automation/company-automation", labelRu: "Автоматизация компании", labelEn: "Company automation" },
      { href: "/automation/processes", labelRu: "Автоматизация процессов", labelEn: "Process automation" },
      AI_BIZ,
      { href: "/integrations/crm", labelRu: "Интеграция CRM", labelEn: "CRM integration" },
      PRICING,
    ],
    ru: {
      h1: "Цифровизация бизнеса под ключ: от Excel и мессенджеров к связанным CRM, 1С и ИИ",
      subtitle:
        "Услуги цифровой трансформации для компаний 20–500 человек: аудит, единый контур данных (CRM + 1С + документы + мессенджеры), автоматизация процессов, ИИ там, где он окупается. Поэтапно, с метриками и бюджетом. Первый этап 4–8 недель от 300 000 ₽.",
      problems: [
        "Заявки в WhatsApp, сделки в Excel, счета в 1С, задачи в голове — компания держится на 3 людях",
        "Купили CRM и Битрикс24, но ими не пользуются: нет процессов и интеграций",
        "Отчёты собираются вручную неделю, решения принимаются по ощущениям",
        "«Цифровая трансформация» от консультантов закончилась презентацией на 80 слайдов",
      ],
      deliverables: [
        "Аудит и карта процессов: как работает компания сейчас, где потери, какие системы нужны (и какие — нет)",
        "Единый контур: CRM (amoCRM/Bitrix24), 1С, документы, телефония, мессенджеры, сайт — данные вводятся один раз",
        "Автоматизация процессов: заявки, согласования, документы, отчёты — роботы, интеграции, при необходимости ИИ",
        "Дашборды для руководителя и регламенты для команды; обучение и сопровождение по SLA",
      ],
      intro: [
        "Цифровизация бизнеса — это не «купить программу», а перестроить процессы так, чтобы данные вводились один раз, а решения принимались по цифрам. Мы делаем это поэтапно: сначала контур продаж и заявок, потом документы и финансы, потом аналитика и ИИ.",
        "Каждый этап — отдельный проект с результатом: например, «все заявки из 6 каналов в CRM, менеджеры работают только там, руководитель видит воронку». Метрика фиксируется до старта, бюджет — фиксированный.",
        "Стек: amoCRM, Bitrix24, 1С (УНФ/УТ/Бухгалтерия/ERP), МойСклад, RetailCRM, YCLIENTS, телефония, Telegram/WhatsApp, n8n, DataLens, YandexGPT/GigaChat. Партнёр Битрикс24, Yandex Cloud, Kaspersky.",
      ],
      howWeSolve: [
        { title: "Аудит (2 недели)", text: "Интервью, процессы, системы, данные. Карта потерь и план этапов с эффектом и бюджетом." },
        { title: "Этап 1: контур продаж и заявок", text: "CRM, каналы, телефония, 1С-обмен, регламенты. 4–8 недель. Метрика — все заявки в CRM, время реакции." },
        { title: "Этапы 2–3: документы, финансы, ИИ", text: "Документооборот и согласования, финансовые отчёты, дашборды, ИИ-ассистенты и агенты там, где есть поток." },
      ],
      faq: [
        { q: "Сколько стоит цифровизация бизнеса?", a: "Аудит — от 150 000 ₽. Первый этап (контур продаж) — 300 000–800 000 ₽. Полная программа для компании 50–200 человек — 1,5–5 млн ₽ за 6–12 месяцев, поэтапно." },
        { q: "Подходит для малого бизнеса?", a: "Да, от 10–15 сотрудников: там цифровизация — это CRM + мессенджеры + 1С и один-два автоматизированных процесса. Бюджет от 300 000 ₽." },
        { q: "Чем это отличается от «внедрения CRM»?", a: "CRM — один из элементов. Цифровизация — связанный контур, процессы, отчётность и план развития; CRM без процессов и интеграций не используется." },
      ],
    },
    en: {
      h1: "Business digitalisation: from Excel and messengers to connected CRM, 1C and AI",
      subtitle: "Digital transformation services for companies of 20–500 people: audit, unified data contour, process automation, AI where it pays off. Stage by stage with metrics and budget. First stage in 4–8 weeks.",
      problems: ["Company runs on 3 people and WhatsApp", "CRM bought but unused", "Weekly manual reports", "Transformation ended with 80 slides"],
      deliverables: ["Audit and process map", "Unified contour: CRM, 1C, documents, telephony, messengers, site", "Process automation with robots, integrations, AI", "Dashboards, rules, training, SLA"],
      intro: ["Not buying software: rebuilding processes so data is entered once.", "Each stage is a project with a result and a fixed budget.", "amoCRM, Bitrix24, 1C, MoySklad, RetailCRM, YCLIENTS, n8n, DataLens, YandexGPT/GigaChat."],
      howWeSolve: [{ title: "Audit", text: "Interviews, processes, systems, plan." }, { title: "Stage 1: sales contour", text: "CRM, channels, telephony, 1C exchange." }, { title: "Stages 2–3", text: "Documents, finance, dashboards, AI." }],
      faq: [{ q: "Cost?", a: "Audit first; stages after." }, { q: "Small business?", a: "Yes, from 10–15 employees." }, { q: "Vs CRM rollout?", a: "CRM is one element of the contour." }],
    },
  },
  {
    category: "automation",
    slug: "avtomatizaciya-sklada",
    contentKey: "aib_warehouse_automation",
    cluster: "automation-processes",
    serviceSlug: "business-process-automation",
    coverImage: IMG.workflow,
    keywords: [
      "автоматизация склада",
      "автоматизация склада 1с",
      "система автоматизации склада",
      "автоматизация складского учета",
      "автоматизация работы склада",
      "автоматизация складов товаров",
      "компании автоматизация складов",
      "автоматизация склада цена",
    ],
    caseStudySlugs: ["crm-1c-sync", "erp-moysklad-chatgpt-ux"],
    related: [
      { href: "/integrations/1c-stock", labelRu: "Остатки и заказы 1С", labelEn: "1C stock and orders" },
      { href: "/solutions/erp-moysklad", labelRu: "МойСклад", labelEn: "MoySklad" },
      { href: "/automation/inventory-requests", labelRu: "Заявки на закупку", labelEn: "Purchase requests" },
      { href: "/automation/order-processing", labelRu: "Обработка заказов", labelEn: "Order processing" },
      { href: "/ai/mashinnoe-obuchenie-dlya-biznesa", labelRu: "Прогноз спроса (ML)", labelEn: "Demand forecasting" },
      PRICING,
    ],
    ru: {
      h1: "Автоматизация склада: адресное хранение, ТСД и штрихкоды в 1С/МойСклад, связка с CRM и маркетплейсами",
      subtitle:
        "Для дистрибуторов, интернет-магазинов и производств со складом 200–20 000 SKU: учёт по местам хранения, приёмка и сборка по штрихкодам с ТСД, автоматические заказы поставщикам, остатки в CRM, на сайте и маркетплейсах в реальном времени. 4–8 недель от 300 000 ₽.",
      problems: [
        "Остатки в 1С не совпадают с фактом: пересортица, «потерянный» товар, продажи того, чего нет",
        "Сборка заказа — 20 минут поиска по складу, ошибки в отгрузках и возвраты",
        "Закупки вручную по Excel: дефицит ходовых позиций и замороженные деньги в неликвиде",
        "Остатки на сайте, в Ozon/WB и CRM обновляются вручную раз в день",
      ],
      deliverables: [
        "Адресное хранение в 1С:УТ/УНФ/ERP, WMS или МойСклад: ячейки, зоны, правила размещения",
        "ТСД и штрихкоды: приёмка, размещение, сборка, инвентаризация без бумаги; печать этикеток, Честный ЗНАК",
        "Интеграции: остатки и резервы в amoCRM/Bitrix24, на сайт, Ozon/Wildberries/Яндекс Маркет, службы доставки",
        "Автозаказ поставщикам по точке заказа или ML-прогнозу спроса; отчёты по оборачиваемости и неликвидам",
      ],
      intro: [
        "Автоматизация склада для среднего бизнеса — это порядок в учёте плюс связь с продажами. Мы не продаём WMS «с завода»: настраиваем складской контур в 1С или МойСклад, добавляем ТСД и штрихкоды, а затем связываем остатки с CRM, сайтом и маркетплейсами.",
        "Типовой проект: аудит склада и учёта → адресное хранение и штрихкоды → ТСД для приёмки и сборки → интеграции с продажами → автозаказ и отчёты. Каждый шаг даёт измеримый результат: точность остатков, время сборки, доля ошибок отгрузки.",
        "Стек: 1С:УТ 11, 1С:УНФ, 1С:ERP, 1С:WMS, МойСклад, RetailCRM, ТСД Android (Honeywell, Urovo, Zebra), Mobile SMARTS, API маркетплейсов и служб доставки. Партнёр Битрикс24 и Yandex Cloud.",
      ],
      howWeSolve: [
        { title: "Аудит склада и учёта", text: "Процессы, объёмы, ошибки, системы. Схема целевого контура, смета, метрики (точность остатков, время сборки)." },
        { title: "Внедрение складского контура", text: "Адресное хранение, штрихкоды, ТСД, инвентаризация. Обучение кладовщиков. 4–6 недель." },
        { title: "Интеграции и автозаказ", text: "CRM, сайт, маркетплейсы, доставка, поставщики; отчёты и прогноз спроса." },
      ],
      faq: [
        { q: "Сколько стоит автоматизация склада?", a: "Склад до 2 000 SKU на 1С:УНФ или МойСклад с ТСД — 300 000–600 000 ₽. Склад 5 000–20 000 SKU на 1С:УТ/ERP с адресным хранением и интеграциями — от 800 000 ₽. Оборудование — отдельно." },
        { q: "Нужна ли отдельная WMS?", a: "До ~10 000 SKU и 500 отгрузок в день обычно хватает 1С:УТ/ERP с адресным хранением и ТСД. WMS — при высокой интенсивности и сложной логистике." },
        { q: "Сколько занимает внедрение?", a: "Малый склад — 4–6 недель, средний с интеграциями — 8–12 недель. Переход без остановки склада, по зонам." },
      ],
    },
    en: {
      h1: "Warehouse automation: bin locations, mobile scanners and barcodes in 1C/MoySklad, linked to CRM and marketplaces",
      subtitle: "For distributors, e-commerce and manufacturers with 200–20,000 SKUs: location accounting, barcode receiving and picking with mobile scanners, automatic supplier orders, real-time stock in CRM, website and marketplaces. 4–8 weeks.",
      problems: ["1C stock does not match reality", "20 minutes to pick an order", "Manual purchasing in Excel", "Stock on site and marketplaces updated once a day"],
      deliverables: ["Bin locations in 1C, WMS or MoySklad", "Mobile scanners and barcodes, labels, Chestny ZNAK", "Stock in CRM, site, Ozon/WB/Yandex Market, delivery", "Auto-orders by reorder point or ML forecast"],
      intro: ["Order in accounting plus link to sales.", "Audit → locations and barcodes → scanners → integrations → auto-orders.", "1C, MoySklad, RetailCRM, Android scanners, Mobile SMARTS, marketplace APIs."],
      howWeSolve: [{ title: "Audit", text: "Processes, volumes, errors, target contour." }, { title: "Warehouse contour", text: "Locations, barcodes, scanners, training." }, { title: "Integrations", text: "CRM, site, marketplaces, suppliers, forecasts." }],
      faq: [{ q: "Cost?", a: "Small warehouse first; larger with integrations after; hardware separate." }, { q: "Separate WMS?", a: "Usually not below ~10,000 SKUs." }, { q: "Timeline?", a: "4–12 weeks without stopping the warehouse." }],
    },
  },
  {
    category: "integrations",
    slug: "integraciya-1s-s-sajtom",
    contentKey: "aib_1c_site_integration",
    cluster: "1c",
    serviceSlug: "crm-integration",
    coverImage: IMG.crm,
    keywords: [
      "интеграция 1с с сайтом",
      "интеграция сайта с 1с",
      "обмен 1с с сайтом",
      "интеграция 1с с интернет магазином",
      "синхронизация 1с и сайта",
      "интеграция 1с с сайтом цена",
      "выгрузка товаров из 1с на сайт",
      "интеграция 1с с tilda",
    ],
    caseStudySlugs: ["crm-1c-sync", "ai-sales-loop"],
    related: [
      { href: "/integrations/1c", labelRu: "Интеграция с 1С", labelEn: "1C integration" },
      { href: "/integrations/bitrix24-1c", labelRu: "1С + Битрикс24", labelEn: "1C + Bitrix24" },
      { href: "/integrations/site-to-crm", labelRu: "Сайт → CRM", labelEn: "Site → CRM" },
      { href: "/integrations/1c-stock", labelRu: "Остатки 1С на сайте", labelEn: "1C stock on site" },
      { href: "/integrations/api-integrations", labelRu: "Интеграции по API", labelEn: "API integrations" },
      PRICING,
    ],
    ru: {
      h1: "Интеграция 1С с сайтом: товары, остатки, цены и заказы в обе стороны — 1С-Битрикс, Tilda, InSales, WordPress",
      subtitle:
        "Настраиваем обмен 1С (УТ, УНФ, ERP, Розница, Бухгалтерия) с сайтом или интернет-магазином: каталог и цены на сайт, заказы и оплаты в 1С, остатки в реальном времени. Чиним сломанный обмен. 1–3 недели, от 60 000 ₽.",
      problems: [
        "Товары и цены на сайт заносятся вручную — расходятся с 1С, продаются позиции с нулевым остатком",
        "Заказы с сайта менеджер перебивает в 1С — ошибки, задержки, дубли клиентов",
        "Стандартный обмен CommerceML работает через раз, падает на больших каталогах",
        "Сайт на Tilda/WordPress/InSales — «нет типовой интеграции с 1С»",
      ],
      deliverables: [
        "Каталог из 1С на сайт: номенклатура, характеристики, цены по типам, фото, категории — по расписанию или событию",
        "Остатки и резервы: реальный остаток по складам на сайте, резерв при заказе, снятие при отмене",
        "Заказы и оплаты в 1С: клиент, состав, доставка, статус, онлайн-оплата и чеки; статусы обратно на сайт",
        "Стабильный обмен: CommerceML, REST/HTTP-сервисы 1С, очереди, логи, мониторинг и оповещения о сбоях",
      ],
      intro: [
        "Интеграция 1С с сайтом — типовая задача, которая редко работает «из коробки»: разные версии 1С, доработанные конфигурации, большие каталоги, нестандартные CMS. Мы проектируем обмен под ваш случай и сопровождаем его.",
        "CMS: 1С-Битрикс (типовой модуль + доработки), Tilda, InSales, WordPress/WooCommerce, OpenCart, Shopify, самописные сайты через API. 1С: УТ 10.3/11, УНФ, ERP, Розница, Бухгалтерия, КА. Для маркетплейсов — отдельный контур через 1С или МойСклад.",
        "Если обмен уже есть, но ломается — делаем аудит: находим причину (объём, блокировки, доработки), чиним или переписываем на HTTP-сервисы 1С с очередью и мониторингом.",
      ],
      howWeSolve: [
        { title: "Аудит и схема обмена", text: "Версии 1С и CMS, объёмы каталога, что и куда должно ходить, частота. Смета за 1–2 дня." },
        { title: "Настройка и разработка", text: "Типовой модуль или HTTP-сервисы 1С, маппинг полей, тесты на копии базы. 1–3 недели." },
        { title: "Запуск и мониторинг", text: "Перенос на production, логи, оповещения о сбоях в Telegram, сопровождение." },
      ],
      faq: [
        { q: "Сколько стоит интеграция 1С с сайтом?", a: "Типовой обмен 1С-Битрикс ↔ 1С:УТ — 60 000–120 000 ₽. Tilda/InSales/WordPress через API — 120 000–250 000 ₽. Сложные каталоги, несколько складов и доработанные 1С — от 250 000 ₽." },
        { q: "Как часто обновляются остатки?", a: "От раз в сутки до реального времени (событийный обмен при изменении в 1С). Для интернет-магазина рекомендуем 5–15 минут или событийно." },
        { q: "Можете починить существующий обмен?", a: "Да, аудит обмена — от 20 000 ₽. Чаще всего проблема в объёме выгрузки, блокировках или доработках конфигурации." },
      ],
    },
    en: {
      h1: "1C to website integration: products, stock, prices and orders both ways — Bitrix, Tilda, InSales, WordPress",
      subtitle: "We set up exchange between 1C (UT, UNF, ERP, Retail, Accounting) and a website or online store: catalogue and prices to the site, orders and payments into 1C, real-time stock. We fix broken exchanges. 1–3 weeks.",
      problems: ["Products entered by hand, out-of-stock sales", "Orders retyped into 1C", "CommerceML exchange fails on large catalogues", "No standard 1C integration for Tilda/WordPress/InSales"],
      deliverables: ["Catalogue from 1C to site", "Stock and reserves in real time", "Orders and payments into 1C, statuses back", "Stable exchange with queues, logs, monitoring"],
      intro: ["Rarely works out of the box: versions, customisations, large catalogues.", "Bitrix, Tilda, InSales, WooCommerce, OpenCart, Shopify, custom sites.", "Audit and repair of existing exchanges."],
      howWeSolve: [{ title: "Audit and scheme", text: "Versions, volumes, flows, frequency." }, { title: "Setup and development", text: "Standard module or 1C HTTP services, tests." }, { title: "Launch and monitoring", text: "Production, logs, Telegram alerts." }],
      faq: [{ q: "Cost?", a: "Standard Bitrix exchange first; API integrations and complex catalogues cost more." }, { q: "Stock frequency?", a: "From daily to real time." }, { q: "Fix existing?", a: "Yes." }],
    },
  },
  {
    category: "solutions",
    slug: "migraciya-v-oblako",
    contentKey: "aib_cloud_migration",
    cluster: "infrastructure",
    serviceSlug: "ai-discovery-roadmap",
    coverImage: IMG.architecture,
    keywords: [
      "миграция в облако",
      "миграция в облако услуги",
      "перенос инфраструктуры в облако",
      "миграция в yandex cloud",
      "миграция 1с в облако",
      "перенос серверов в облако",
      "миграция в российское облако",
      "миграция в облако стоимость",
    ],
    caseStudySlugs: ["elia-suite", "kaspersky-ai-assistant"],
    related: [
      { href: "/ai-kubernetes", labelRu: "AI на Kubernetes", labelEn: "AI on Kubernetes" },
      { href: "/secure-ai", labelRu: "Безопасный ИИ-контур", labelEn: "Secure AI contour" },
      { href: "/partners", labelRu: "Партнёры: Yandex Cloud, Selectel, Cloud.ru", labelEn: "Partners" },
      PRIVATE_LLM,
      { href: "/solutions/it-konsalting", labelRu: "IT-консалтинг", labelEn: "IT consulting" },
      PRICING,
    ],
    ru: {
      h1: "Миграция в облако: перенос серверов, 1С и данных в Yandex Cloud, Selectel или Cloud.ru без остановки бизнеса",
      subtitle:
        "Партнёр Yandex Cloud, Selectel и Cloud.ru: аудит инфраструктуры, план и смета, перенос 1С, баз данных, CRM, сайтов и ИИ-нагрузок, Kubernetes, резервное копирование, ИБ по 152-ФЗ. Миграция 2–8 недель, от 200 000 ₽.",
      problems: [
        "Серверы в офисе стареют, админ один, бэкапы «вроде делаются»",
        "Зарубежное облако — риски блокировок, оплаты и 152-ФЗ",
        "Нужны GPU для ИИ-проектов, а покупать железо на 3 миллиона нет смысла",
        "Боятся простоя при переносе 1С и баз данных",
      ],
      deliverables: [
        "Аудит и план: инвентаризация серверов, сервисов, зависимостей; целевая архитектура, расчёт стоимости облака, план переноса по волнам",
        "Перенос: 1С (серверная и файловая), PostgreSQL/MS SQL, CRM, сайты, файловые хранилища, почта, Kubernetes-нагрузки, GPU для ИИ",
        "Инфраструктура как код (Terraform), сети и VPN, резервное копирование, мониторинг, доступы и журналирование",
        "ИБ: сегментация, шифрование, 152-ФЗ, при необходимости контур Kaspersky; документация и передача админам",
      ],
      intro: [
        "Миграция в облако для среднего бизнеса — это перенос 1С, баз, CRM и сайтов в российское облако с понятной стоимостью и без простоя. Мы работаем как партнёр Yandex Cloud, Selectel и Cloud.ru и выбираем площадку под задачу: 1С, GPU для ИИ, Kubernetes, объектное хранилище.",
        "План переноса строится по волнам: сначала некритичные сервисы, потом базы и 1С в окно минимальной нагрузки с репликацией и откатом. Каждая волна — тест, переключение, наблюдение.",
        "После миграции — инфраструктура как код, мониторинг, бэкапы с проверкой восстановления и документация. Можем сопровождать по SLA или передать вашим администраторам.",
      ],
      howWeSolve: [
        { title: "Аудит и план (1–2 недели)", text: "Инвентаризация, зависимости, расчёт стоимости в 2–3 облаках, план волн, смета." },
        { title: "Миграция по волнам (2–6 недель)", text: "Подготовка среды (IaC), перенос сервисов, репликация баз, переключение в окно, откат при необходимости." },
        { title: "Стабилизация", text: "Мониторинг, бэкапы, оптимизация стоимости, документация, обучение или SLA." },
      ],
      faq: [
        { q: "Сколько стоит миграция в облако?", a: "Аудит и план — от 100 000 ₽. Миграция 3–10 серверов с 1С и базами — 200 000–600 000 ₽. Крупные ландшафты с Kubernetes и GPU — по плану. Стоимость самого облака считаем на аудите." },
        { q: "Будет ли простой 1С?", a: "Окно переключения обычно 1–4 часа ночью или в выходной, с предварительной репликацией и тестом. Файловые базы переносятся быстрее." },
        { q: "Какое облако выбрать?", a: "Yandex Cloud — управляемые сервисы и GPU, Selectel — выделенные серверы и цена, Cloud.ru — GPU и ML-платформа. Считаем под вашу нагрузку." },
      ],
    },
    en: {
      h1: "Cloud migration: moving servers, 1C and data to Yandex Cloud, Selectel or Cloud.ru without stopping the business",
      subtitle: "Partner of Yandex Cloud, Selectel and Cloud.ru: infrastructure audit, plan and estimate, migration of 1C, databases, CRM, websites and AI workloads, Kubernetes, backups, 152-FZ security. 2–8 weeks.",
      problems: ["Ageing office servers, one admin", "Foreign cloud risks", "GPU needed without buying hardware", "Fear of 1C downtime"],
      deliverables: ["Audit and wave plan with cloud cost", "Migration of 1C, databases, CRM, sites, Kubernetes, GPU", "IaC, networks, backups, monitoring", "Security, 152-FZ, documentation"],
      intro: ["Russian cloud with clear cost and no downtime.", "Waves: non-critical first, then databases and 1C in a low-load window with replication and rollback.", "IaC, monitoring, tested backups after migration."],
      howWeSolve: [{ title: "Audit and plan", text: "Inventory, dependencies, cost in 2–3 clouds." }, { title: "Waves", text: "IaC, migration, replication, switch, rollback." }, { title: "Stabilisation", text: "Monitoring, backups, cost optimisation." }],
      faq: [{ q: "Cost?", a: "Audit first; migration by size." }, { q: "1C downtime?", a: "Usually a 1–4 hour night window." }, { q: "Which cloud?", a: "Depends on workload." }],
    },
  },
  {
    category: "ai",
    slug: "ii-pomoshchnik-na-qwen",
    contentKey: "aib_qwen_assistant",
    cluster: "ai-corporate",
    serviceSlug: "enterprise-ai-assistant",
    coverImage: IMG.architecture,
    keywords: [
      "ии помощник на qwen",
      "ии ассистент на qwen",
      "qwen для бизнеса",
      "внедрение qwen",
      "qwen нейросеть для компании",
      "корпоративный ассистент qwen",
      "локальный qwen для бизнеса",
      "qwen on premise",
      "ии помощник на открытой модели",
    ],
    caseStudySlugs: ["kaspersky-ai-assistant", "kp-llm-automation", "erp-moysklad-chatgpt-ux"],
    related: [
      PRIVATE_LLM,
      { href: "/ai/gpt-dlya-biznesa", labelRu: "GPT для бизнеса", labelEn: "GPT for business" },
      { href: "/ai/ii-assistent-dlya-rukovoditelya", labelRu: "ИИ-ассистент руководителя", labelEn: "AI assistant for executives" },
      RAG,
      { href: "/ai/doobuchenie-llm", labelRu: "Дообучение LLM", labelEn: "LLM fine-tuning" },
      PRICING,
    ],
    ru: {
      h1: "ИИ-помощник на Qwen: корпоративный ассистент на открытой модели в вашем контуре",
      subtitle:
        "Внедряем ИИ-помощника на Qwen (Qwen2.5 / Qwen3) для сотрудников и клиентов: ответы по вашим документам, CRM и 1С, черновики писем и КП, поддержка в мессенджерах. On-premise или российское облако — данные не уходят в зарубежные API. Пилот 3–5 недель от 300 000 ₽.",
      problems: [
        "Нужен сильный ИИ-помощник, но ChatGPT/Claude нельзя по ИБ и 152-ФЗ — персональные и коммерческие данные",
        "Купили доступ к чату, а пользы мало: модель не знает прайсов, регламентов и сделок в CRM",
        "Хотят локальную нейросеть (Qwen), но нет инфраструктуры, RAG и интеграции с процессами",
        "Сотрудники уже гоняют запросы в публичные чаты — риск утечки и разрозненные ответы",
      ],
      deliverables: [
        "Корпоративный ИИ-помощник на Qwen: чат с ролями, лимитами и журналом; RAG по документам, базе знаний и FAQ",
        "Интеграции: CRM (Битрикс24, amoCRM), 1С, почта, Telegram/сайт — ответы и действия в процессе, не «ещё один чат»",
        "Контур: on-premise / GPU в Yandex Cloud, Selectel или Cloud.ru; политика данных, NDA, мониторинг токенов",
        "Обучение команды и приёмка по метрике: время на задачу, доля ответов с источником, эскалация к человеку",
      ],
      intro: [
        "ИИ-помощник на Qwen — это не подписка на публичный чат. Qwen хорошо держит русский язык и длинный контекст, а как открытая модель разворачивается у вас: документы и сделки остаются в контуре.",
        "Типовые сценарии: внутренний ассистент по регламентам и КП, помощник продаж с карточкой CRM, поддержка клиентов с эскалацией оператору, разбор документов. Где нужен fine-tuning — скажем честно; часто хватает RAG и инструментов.",
        "Сравниваем Qwen с YandexGPT/GigaChat на ваших примерах. Партнёр Yandex Cloud, Selectel, Cloud.ru. Кейсы: ассистент для Kaspersky, генерация КП на LLM, чат к МойСклад.",
      ],
      howWeSolve: [
        { title: "Тест на ваших задачах", text: "20–50 реальных примеров: Qwen vs альтернативы, выбор размера модели и железа. 1–2 недели." },
        { title: "Пилот помощника", text: "RAG + 1–2 интеграции (CRM/документы/мессенджер), роли и журнал. Метрика — время и качество ответа." },
        { title: "Production", text: "Все каналы, действия в системах, мониторинг, обучение, SLA или передача админам." },
      ],
      faq: [
        { q: "Сколько стоит ИИ-помощник на Qwen?", a: "Тест моделей — от 100 000 ₽, пилот помощника с RAG и одной интеграцией — от 300 000 ₽. GPU/хостинг — отдельно, считаем на аудите." },
        { q: "Почему Qwen, а не YandexGPT или GigaChat?", a: "Qwen удобен, когда данные не должны покидать сервер и нужен контроль версии модели. Российские API проще по закупке — сравниваем на ваших задачах и политике ИБ." },
        { q: "Нужен ли fine-tuning Qwen?", a: "Для ответов по документам обычно достаточно RAG. Дообучение — когда нужен узкий стиль, классификация или малая модель на edge; сначала измеряем разрыв." },
      ],
    },
    en: {
      h1: "Qwen AI assistant: corporate helper on an open model in your perimeter",
      subtitle:
        "We deploy a Qwen-based AI assistant for staff and customers: answers over your docs, CRM and 1C, drafts and support in messengers. On-prem or Russian cloud — data stays inside. Pilot in 3–5 weeks.",
      problems: [
        "Need a strong assistant but ChatGPT/Claude blocked by security",
        "Chat access bought but model does not know prices, policies or CRM deals",
        "Want local Qwen but no infra, RAG or process integration",
        "Staff already use public chats — leak risk",
      ],
      deliverables: [
        "Corporate Qwen assistant with roles, limits, logs and RAG",
        "CRM / 1C / mail / messengers integrations",
        "On-prem or Russian cloud contour, data policy, token monitoring",
        "Team training and acceptance metrics",
      ],
      intro: [
        "Not a public chat subscription: Qwen runs in your contour with your data.",
        "Typical: internal policy assistant, sales helper, support with handover, document triage.",
        "We compare Qwen with YandexGPT/GigaChat on your examples.",
      ],
      howWeSolve: [
        { title: "Task test", text: "20–50 real examples, model size and hardware." },
        { title: "Pilot", text: "RAG + 1–2 integrations, roles and logs." },
        { title: "Production", text: "All channels, system actions, monitoring, training." },
      ],
      faq: [
        { q: "Cost?", a: "Model test first, then pilot with RAG and one integration; GPU separate." },
        { q: "Why Qwen?", a: "When data must stay on your servers; we still compare with Russian APIs." },
        { q: "Fine-tuning?", a: "Usually RAG is enough; fine-tune only when metrics show a gap." },
      ],
    },
  },
];
