const en = {
  meta: {
    title: "Enterprise AI implementation partner",
    description:
      "Bober AI Systems — enterprise AI implementation partner. External AI department for software houses, CRM/ERP integrators, and companies with budgets from €10,000.",
    keywords: [
      "enterprise AI",
      "AI implementation",
      "RAG systems",
      "AI agents",
      "MLOps",
      "LLM integration",
      "AI automation",
      "B2B AI consulting",
    ],
  },
  nav: {
    services: "Solutions",
    packages: "Packages",
    portfolio: "Case studies",
    blog: "Blog",
    partners: "Partners",
    process: "Process",
    about: "About",
    reviews: "Reviews",
    contact: "Contact",
    write: "Request a quote",
    servicesPage: "All solutions",
  },
  locale: {
    switchTo: "Русский",
  },
  hero: {
    location: "Moscow · Remote · Russia & CIS",
    title: "Enterprise AI implementation partner",
    roles: ["AI architect", "Production delivery"],
    nameLine: "Pavel Stasinsky · '@'pstasinski",
    focus:
      "External AI department for software houses, CRM/ERP integrators, and companies with budgets from €10,000. RAG, agents, integrations, MLOps. Fixed scope, milestones, team handover.",
    trustLine: "★ {rating} · {reviewCount} reviews · {years} years · 12+ production deployments",
    partnersLine: "Yandex Cloud · Selectel · Cloud.ru partner",
    ctaPrimary: "Discuss your project",
    ctaSecondary: "View case studies",
    ctaTelegram: "Telegram",
    responseNote: "Response within 4 business hours · NDA available",
    legalNote: "Personal data published with the subject''s consent.",
    legalLink: "Privacy policy",
  },
  audiences: {
    title: "Who we work with",
    items: [
      {
        title: "Software houses",
        text: "White-label AI modules for your product: RAG, agents, APIs. Documentation and handover for your team.",
      },
      {
        title: "CRM/ERP integrators",
        text: "Bitrix24, amoCRM, 1C — we add the AI layer without conflicting with your client contract.",
      },
      {
        title: "Companies with budget",
        text: "Sales, documents, support automation. On-prem, cloud, compliance-ready delivery.",
      },
    ],
  },
  trust: {
    title: "Trusted for production AI",
    stats: [
      { value: "12+", label: "production deployments" },
      { value: "€25k+", label: "typical enterprise deal" },
      { value: "7 years", label: "in AI & automation" },
      { value: "NDA", label: "and on-prem on request" },
    ],
    logos: ["Kaspersky", "Yandex Cloud", "Selectel", "Cloud.ru"],
  },
  packages: {
    title: "Packages for companies",
    subtitle: "Fixed scope and deliverables — not hourly consulting",
    items: [
      {
        name: "Diagnostics",
        price: "from €1,500",
        duration: "1–2 weeks",
        forWhom: "You need a plan, architecture, and estimate before procurement",
        result: "Clear roadmap and estimate before development starts",
        includes: ["Consultation and brief", "Process and data audit", "Solution architecture", "Budget and timeline estimate"],
        detailsHref: "/services/ai-discovery-roadmap",
      },
      {
        name: "Quick launch",
        price: "from €4,000",
        duration: "from 14 days",
        forWhom: "You need an AI bot, assistant, or single-process automation",
        result: "Working solution in production with basic integration",
        includes: ["AI bot or Telegram assistant", "Single-process automation", "Basic n8n / CRM integration", "Testing and handover"],
        detailsHref: "/services/sales-ai-agent",
      },
      {
        name: "Full implementation",
        price: "from €5,000",
        duration: "4–12 weeks",
        forWhom: "Ready to deploy RAG, agents, or multiple integrations",
        result: "Production deployment with documentation and handover",
        includes: ["AI agent or CRM integration", "Document automation", "Multiple integrations", "Documentation and team handover"],
        featured: true,
        detailsHref: "/services/enterprise-ai-assistant",
      },
      {
        name: "Enterprise solution",
        price: "from €5,000",
        duration: "from 4 weeks · retainer from €2,000/mo",
        forWhom: "You need a private perimeter, RAG, and ongoing support",
        result: "Isolated infrastructure with roles, monitoring, and SLA",
        includes: ["Private perimeter and on-prem", "RAG and local LLM", "Roles, access, and guardrails", "Monitoring and support"],
        detailsHref: "/services/private-llm-gigachat",
      },
    ],
    cta: "Request a quote",
    featuredLabel: "Most chosen",
    detailsLabel: "Details",
  },
  services: {
    title: "What we deliver",
    subtitle: "Production-ready systems with team handover — not demos",
    details: "Details",
    quote: "Request a quote",
    days: "days",
    discussCta: "Discuss implementation",
    implementationAreas: [
      {
        badge: "AI agents",
        title: "AI assistants for business",
        description: "Handle inquiries, prepare documents, update CRM, and help teams with routine tasks.",
        items: ["Telegram and messengers", "Claude, OpenAI, YandexGPT", "CRM and internal APIs"],
        accent: "green",
        featured: true,
        wide: true,
        slug: "enterprise-ai-assistant",
      },
      {
        badge: "Sales",
        title: "AI agent for sales & proposals",
        description: "Commercial proposals from CRM and templates. PDF in minutes, not hours.",
        items: ["amoCRM and Bitrix24", "Proposal templates", "Automatic PDF generation"],
        accent: "blue",
        slug: "sales-ai-agent",
      },
      {
        badge: "Automation",
        title: "AI business process automation",
        description: "Documents, reports, CRM, notifications — task chains without manual routine.",
        items: ["Document processing", "Reports and notifications", "n8n and internal APIs"],
        accent: "orange",
        slug: "business-process-automation",
      },
      {
        badge: "Private LLM",
        title: "Local and private LLM",
        description: "GigaChat, on-prem and isolated cloud — no data leakage to public APIs.",
        items: ["GigaChat and YandexGPT", "On-prem and compliance", "Guardrails and monitoring"],
        accent: "violet",
        slug: "private-llm-gigachat",
      },
      {
        badge: "Discovery",
        title: "AI Discovery & Roadmap",
        description: "Audit, architecture, model selection, timeline and budget estimate before development.",
        items: ["Task and data audit", "Architecture and stack", "Roadmap and estimate"],
        accent: "cyan",
        slug: "ai-discovery-roadmap",
      },
      {
        badge: "RAG · CRM",
        title: "Knowledge base & integrations",
        description: "Corporate RAG system connected to amoCRM, Bitrix24, 1C, and Telegram.",
        items: ["Corporate knowledge base", "amoCRM, Bitrix24, 1C", "REST API and webhooks"],
        accent: "cyan",
        wide: true,
      },
    ],
    items: [
      {
        slug: "enterprise-ai-assistant",
        title: "Enterprise AI assistant",
        description: "Dialogs, workflows, CRM and messenger integrations. LLM orchestration for your processes.",
        salesNotes: "from €5,000",
        deliveryDays: 28,
      },
      {
        slug: "ai-discovery-roadmap",
        title: "AI Discovery & Roadmap",
        description: "Audit, architecture, model selection, timeline and budget estimate before development starts.",
        salesNotes: "from €1,500",
        deliveryDays: 10,
      },
      {
        slug: "private-llm-gigachat",
        title: "Private LLM environment",
        description: "GigaChat, on-prem and isolated cloud — no data leakage to public APIs.",
        salesNotes: "from €5,000",
        deliveryDays: 28,
      },
      {
        slug: "business-process-automation",
        title: "AI business process automation",
        description: "Documents, reports, CRM, notifications — task chains without manual routine.",
        salesNotes: "from €4,000",
        deliveryDays: 21,
      },
      {
        slug: "sales-ai-agent",
        title: "AI agent for sales & proposals",
        description: "Commercial proposals from CRM and templates. PDF in minutes, not hours.",
        salesNotes: "from €4,000",
        deliveryDays: 14,
      },
    ],
  },
  process: {
    title: "How we work",
    subtitle: "Transparent milestones — you know what you get at each step",
    steps: [
      { title: "Discovery", text: "Brief, data and process audit, scope and risk clarification." },
      { title: "Architecture", text: "Stack, integration diagram, estimate and phased plan." },
      { title: "PoC", text: "Validate the hypothesis on real data before full budget." },
      { title: "Production", text: "Development, deployment, monitoring, tests on your environment." },
      { title: "Handover", text: "Documentation, team training, SLA support." },
    ],
  },
  security: {
    title: "Security & compliance",
    items: [
      "On-prem and isolated cloud — data stays out of public APIs",
      "152-FZ: privacy policy, consent, processing agreement",
      "NDA before work starts — standard for enterprise",
      "Kubernetes, monitoring, logging — production-grade infrastructure",
    ],
  },
  partners: {
    badge: "For integrators & software houses",
    title: "White-label AI for partners",
    subtitle: "You face the client — we deliver architecture, code, and deployment",
    description:
      "Subcontract and revenue share. NDA, fixed timelines, documentation for your team. Bitrix24, amoCRM, 1C, REST API.",
    steps: [
      { title: "You bring the client", text: "Or we work as your AI subcontractor under NDA." },
      { title: "Fixed scope", text: "Estimate, timeline, deliverables — no surprises for your PM." },
      { title: "Handover", text: "Code, docs, training — your brand, our expertise." },
    ],
    models: [
      "Subcontract: fixed price per scope",
      "Revenue share: 10% of client advance payment",
      "White-label: no Bober AI mention in client-facing docs",
    ],
    cta: "Become a technology partner",
    commission: "'10%'",
    commissionNote: "of client advance on referral",
  },
  about: {
    title: "About",
    text: "Bober AI Systems delivers production AI for companies with real budgets. Not a freelance marketplace: fixed estimates, milestones, contracts, and handover to your team.\n\nFocus: RAG, AI agents, CRM/ERP integrations, MLOps on Kubernetes. Yandex Cloud, Selectel, Cloud.ru partner. Case studies include Kaspersky and enterprise sales/document automation.\n\nWe respond within 4 business hours. NDA before kickoff.",
    education: "Education",
    educationValue: "University of Warsaw — Physics and Neuroscience",
    schedule: "Schedule",
    scheduleValue: "Mon–Fri, response within 4h",
    collaboration: "Engagement",
    collaborationSummary: "Fixed estimate or retainer. Milestone-based delivery.",
    collaborationDetail: "Contract, NDA, IP assignment — standard for B2B.",
    skillsTitle: "Expertise",
    skills: [
      "RAG & enterprise knowledge bases",
      "Business AI agents",
      "MLOps & Kubernetes",
      "LLM integrations",
      "CRM: amoCRM, Bitrix24, 1C",
      "On-prem & compliance",
      "YandexGPT & GigaChat",
      "Yandex Cloud · Selectel",
    ],
    cta: "Request a quote",
  },
  reviews: {
    yandexTitle: "Yandex",
    yandexMeta: "Rating {rating} · {count} reviews",
    avitoTitle: "Avito reviews",
    avitoMeta: "{count} published reviews",
    kworkTitle: "Kwork reviews",
  },
  portfolio: {
    title: "Case studies",
    subtitle: "Enterprise projects with measurable outcomes",
    details: "View case study",
    priceFrom: "from",
    problemLabel: "Challenge",
    solutionLabel: "Solution",
    resultLabel: "Outcome",
    categoriesLabel: "Categories",
  },
  cta: {
    title: "Have a project? Get an estimate.",
    subtitle: "Describe your scope. Preliminary plan and estimate within 24 hours.",
    primary: "Request a quote",
    secondary: "Message on Telegram",
  },
  contact: {
    title: "Contact",
    subtitle: "Describe your task, budget, and timeline — we respond within 4 business hours.",
    email: "Email",
    telegram: "Telegram",
    phone: "Phone",
  },
  form: {
    name: "Name",
    contact: "Email or phone",
    company: "Company",
    companyPlaceholder: "Acme Inc.",
    budget: "Project budget",
    budgetPlaceholder: "Select range",
    budgetOptions: ["up to €5,000", "€5,000 – €15,000", "€15,000 – €50,000", "€50,000+"],
    companyType: "Company type",
    companyTypePlaceholder: "Select type",
    companyTypeOptions: ["End client", "Software house", "CRM/ERP integrator", "Agency", "Other"],
    service: "Task / service",
    servicePlaceholder: "e.g. RAG knowledge base",
    message: "Message",
    policy: "I have read the",
    policyLink: "privacy policy",
    consent: "I give",
    consentLink: "consent to personal data processing",
    submit: "Send request",
    submitting: "Sending…",
    success: "Request sent. We will contact you shortly.",
    errorPolicy: "You must confirm you have read the privacy policy",
    errorConsent: "You must give consent to personal data processing",
    errorSend: "Failed to send request",
    errorGeneric: "Send error",
  },
  footer: {
    legalName: "IE Pavel Stasinsky",
    privacy: "Privacy policy",
    consent: "Data processing consent",
    marketplaces: "Also on marketplaces",
  },
  banner: {
    badge: "For integrators",
    title: "White-label AI for partners",
    text: "Refer clients — {percent} of advance. Subcontract under NDA.",
    cta: "Become a partner",
    more: "Learn more",
    close: "Close",
  },
  common: {
    siteName: "Bober AI Systems",
    online: "Online",
    readMore: "Learn more",
  },
  servicePage: {
    back: "← All solutions",
    includes: "What''s included",
    deliverables: [
      "Task audit and scope agreement",
      "Development and configuration",
      "Testing and production deployment",
      "Documentation and team handover",
    ],
    timeline: "Timeline",
    days: "days",
    quote: "Request a quote",
    telegram: "Message on Telegram",
    formTitle: "Or leave a request",
    listTitle: "Enterprise AI solutions",
  },
  partnersPage: {
    title: "Partners",
    subtitle: "White-label AI for integrators and software houses",
  },
} as const;

export default en;
