const en = {
  meta: {
    title: "AI systems and automation for companies — Bober AI",
    description:
      "AI systems and automation for companies: documents, sales, support and internal processes. AI assistants, RAG, private LLMs. Integration with Bitrix24, 1C, amoCRM, CRM and ERP.",
    keywords: [
      "AI systems for companies",
      "business process automation",
      "enterprise AI implementation",
      "private LLM",
      "corporate RAG",
      "AI assistants",
      "amoCRM integration",
      "Bitrix24 integration",
      "AI on-premise",
      "document automation",
      "claude ai",
      "claude api",
    ],
  },
  nav: {
    services: "Solutions",
    automation: "Automation",
    packages: "Packages",
    portfolio: "Case studies",
    howWeWork: "How we work",
    pricing: "Pricing",
    guides: "Guides",
    blog: "Blog",
    academy: "Workshop",
    partners: "Partners",
    process: "Process",
    about: "About",
    faq: "FAQ",
    media: "Media",
    certificates: "Certificates",
    reviews: "Reviews",
    contact: "Contact",
    consultCta: "Get a preliminary estimate",
    consultCtaShort: "Estimate",
    write: "Get a preliminary estimate",
    writeShort: "Estimate",
    menuOpen: "Open menu",
    menuClose: "Close menu",
    quickContact: "Get in touch",
    call: "Call",
    telegram: "Telegram",
    servicesPage: "All solutions",
  },
  locale: {
    switchTo: "Русский",
  },
  hero: {
    location: "Moscow · Remote · Russia & CIS",
    eyebrow: "Partners: Yandex Cloud, Cloud.ru and Selectel",
    titleLine1: "We automate proposals, documents and CRM workflows with AI — no manual data copying",
    titleLine2: "",
    valueProposition:
      "For companies where managers and operators lose hours on proposals, documents and copy-paste between CRM, email and ERP.\n\nWe deploy a production AI perimeter into your systems — with a fixed estimate, NDA and full code handover.",
    differentiator: "Fixed estimate · NDA · cloud or on-premise",
    specialization: "Project estimate — 30 minutes · reply within 4 business hours",
    heroImageAlt: "Pawel Stasinski — AI architect, corporate systems and automation",
    officeGalleryLabel: "Corporate architecture and office spaces",
    trustItems: ["NDA", "CLOUD / ON-PREMISE", "MOSCOW / REMOTE"],
    title: "We automate proposals, documents and CRM workflows with AI — no manual data copying",
    roles: ["Automation architect", "Production implementation"],
    nameLine: "Pawel Stasinski · '@'pstasinski",
    focus: "AI systems, automation and integration with Bitrix24, 1C, amoCRM, CRM and ERP.",
    trustLine: "★ {rating} · {reviewCount} reviews · {years} years · 12+ production deployments",
    partnersLine: "Partners: Yandex Cloud, Cloud.ru and Selectel",
    ctaPrimary: "Get an estimate",
    ctaSecondary: "View case studies",
    ctaTelegram: "Telegram",
    responseNote: "Response within 4 business hours · NDA available",
    legalNote: "Personal data published with the subject''s consent.",
    legalLink: "Privacy policy",
  },
  philosophy: {
    title: "We don't sell AI",
    subtitle: "We improve business operations",
    items: [
      "Sometimes that means integrating a CRM.",
      "Sometimes automating documents.",
      "Sometimes redesigning a workflow.",
      "Sometimes building an AI assistant.",
    ],
    closing:
      "We recommend the solution that delivers the highest business value—not the most fashionable technology.",
  },
  whyUs: {
    label: "Difference",
    title: "A production AI perimeter: integrations, logs, roles, error control and code handover",
    text: "First we measure the current workload, then we lock pilot metrics and acceptance criteria",
    benefits: [
      "40–80% time savings on typical operations",
      "Fewer errors when data moves between CRM, email and documents",
      "Payback from 3 months — calculated from real load before the estimate",
      "Full handover to your team: code, access, documentation",
    ],
  },
  oneWindow: {
    label: "One process",
    title: "Everything you need for implementation — in one place",
    subtitle: "Whatever is blocking you now — we scope it and close it within one project.",
    items: [
      {
        q: "Processes aren't documented?",
        a: "We map how your team actually works and identify what's truly worth automating.",
      },
      {
        q: "Data lives in PDFs, Excel, email and CRM?",
        a: "We bring it into a single working perimeter.",
      },
      {
        q: "CRM and 1C aren't connected?",
        a: "We set up data exchange without manual copying.",
      },
      {
        q: "Need document processing?",
        a: "The system recognizes the request, finds the item, checks the data and prepares the document.",
      },
      {
        q: "You have security requirements?",
        a: "We deploy the solution in your cloud or on-prem environment.",
      },
      {
        q: "Not sure it will pay off?",
        a: "Before development we estimate cost, time savings and expected impact.",
      },
    ],
  },
  budgetGate: {
    label: "Engagement format",
    title: "Pilot — from €3,000",
    whyLabel: "Why:",
    reasons: [
      "We start by mapping the process and data sources",
      "We integrate with your existing systems",
      "We test on real scenarios",
      "We deploy to production",
      "We hand over documentation and access",
    ],
    note: "Budget ladder: audit from €1,500, pilot from €3,000, production implementation from €5,000.",
    cta: "Get a preliminary estimate",
  },
  homeHub: {
    label: "Sections",
    title: "Explore in detail",
    items: [
      {
        href: "/services",
        title: "Solutions",
        description: "CRM, documents, sales, support — what we implement and the business outcomes.",
      },
      {
        href: "/portfolio",
        title: "Case studies",
        description: "ELIA Suite, proposal automation, product-docs RAG — with measurement methodology.",
      },
      {
        href: "/pricing",
        title: "Pricing",
        description: "Audit from €1,500, pilot from €3,000, production implementation from €5,000.",
      },
      {
        href: "/faq",
        title: "FAQ",
        description: "Timeline, budget, NDA, CRM — answers for procurement and IT.",
      },
    ],
  },
  homeLanding: {
    proofLabel: "Results",
    proofTitle: "What we already measured on pilots",
    casesLabel: "Case studies",
    casesTitle: "Three deployments with measurable impact",
    casesSubtitle: "Before → after: production scenarios with a measurement method.",
    casesCta: "All case studies in the portfolio",
    caseBeforeLabel: "Before",
    caseAfterLabel: "After",
    caseDiscussCta: "Discuss a similar project",
    packagesMore: "Full price list, ROI and process on Pricing",
    whyTrustMore: "Publications and proof — in the Media section",
    faqMore: "All answers in FAQ",
    budgetLabel: "Budget and trust",
    budgetTitle: "A clear entry point — no hidden stages",
    budgetNote:
      "Audit — from €1,500 · pilot — from €3,000 · production implementation — from €5,000. NDA and your own perimeter — on request before sharing data.",
    budgetCta: "Get a preliminary estimate",
    roiEntryLabel: "ROI",
    roiEntryTitle: "Estimate savings before the call",
    roiEntryText:
      "ROI calculator for AI automation of CRM and documents — savings range, payback period and an audit checklist.",
    roiEntryCta: "Open calculator",
    depthLabel: "Before the call",
    depthTitle: "Explore the approach before the first meeting",
    depthSubtitle: "Short reads on format, budget and data protection — without a long email thread.",
    depthItems: [
      {
        href: "/services",
        title: "What an audit delivers",
        description: "Process map, loss points and automation priorities before development.",
      },
      {
        href: "/pricing",
        title: "How we calculate ROI and budget",
        description: "Audit, pilot and production implementation — fixed scope before kickoff.",
      },
      {
        href: "/faq",
        title: "How we protect data",
        description: "NDA, your perimeter, compliance and answers for IT and procurement.",
      },
    ],
  },
  pages: {
    services: {
      metaTitle: "Services — AI implementation and business automation",
      metaDescription: "CRM, documents, sales, support, knowledge base — AI in company operations with fixed scope.",
    },
    portfolio: {
      metaTitle: "AI implementation case studies",
      metaDescription: "Bober AI Systems portfolio: ELIA Suite, proposal automation, CRM and documents, corporate RAG assistants.",
    },
    pricing: {
      metaTitle: "AI service price list — packages and estimates",
      metaDescription: "Price list: audit from €1,500, pilot from €3,000, production implementation from €5,000. Fixed estimate before start.",
    },
    faq: {
      metaTitle: "FAQ — AI implementation for business",
      metaDescription: "Answers on budget, timeline, NDA, CRM, Claude API and on-prem deployment.",
    },
    media: {
      metaTitle: "Pawel Stasinski — publications, interviews and expert commentary",
      metaDescription:
        "FAKRO FM interview, MK commentary, Severgazbank article, Habr and Medium publications, GitHub and Stack Exchange.",
      pageTitle: "Pawel Stasinski — publications, interviews and expert commentary",
    },
    certificates: {
      metaTitle: "Certificates — Authorized Partner of Kaspersky Lab",
      metaDescription:
        "Bober AI Systems certificates: Authorized Partner of Kaspersky Lab — B2B and B2C. PDF downloads and previews.",
    },
    about: {
      metaTitle: "About — Bober AI Systems",
      metaDescription:
        "Bober AI: automation and AI for companies. Approach, expertise and Authorized Partner of Kaspersky Lab certificates.",
      pageTitle: "About",
      lead: "Design and implementation of automation and AI for companies. Partner certificates confirm status — not a product catalog.",
    },
  },
  certificates: {
    label: "Partnership",
    title: "Certificates",
    intro: "Authorized Partner of Kaspersky Lab. Documents confirm status — not a product catalog.",
    titles: {
      b2b: "B2B",
      b2c: "B2C",
    },
    openPdf: "Open PDF",
  },
  problemsWeSolve: {
    title: "Typical problems we solve",
    subtitle: "Sound familiar? Most of our clients start here.",
    items: [
      "Sales team spends hours preparing commercial offers",
      "Information is scattered across CRM, email and Telegram",
      "Employees manually copy data between systems",
      "Documents require repetitive manual processing",
      "Customer requests disappear before anyone follows up",
    ],
    solutionsIntro: "Next: how we differ from ChatGPT, case studies, and packages.",
  },
  audiences: {
    title: "Who we work with",
    items: [
      {
        title: "Owner / CEO",
        text: "You need payback and risk control — not a hype experiment.",
      },
      {
        title: "Commercial lead",
        text: "Quotes, leads and CRM without copy-paste — shorter sales cycle.",
      },
      {
        title: "Operations lead",
        text: "Documents, requests and routing without peak-load bottlenecks.",
      },
      {
        title: "IT / integrator",
        text: "Architecture, access, monitoring and handover into your perimeter.",
      },
    ],
  },
  trust: {
    title: "Companies trust us with automation implementation",
    strip: [
      "AUDIT FROM €1,500",
      "PILOT FROM €3,000",
      "PRODUCTION IMPLEMENTATION FROM €5,000",
      "NDA / YOUR PERIMETER",
    ],
    stats: [
      { value: "45→2–5 min", label: "proposal prep on a pilot" },
      { value: "+32%", label: "quote→order conversion" },
      { value: "up to −50%", label: "repeat knowledge-base questions" },
      { value: "NDA", label: "your perimeter on request" },
    ],
    budgetStats: [
      { value: "from €1.5k", label: "audit" },
      { value: "from €3k", label: "pilot" },
      { value: "from €5k", label: "production implementation" },
      { value: "NDA", label: "and your perimeter on request" },
    ],
    logos: ["Yandex Cloud", "Selectel", "Cloud.ru", "Kaspersky"],
    partnersAriaLabel: "Implementation risk reduction",
    benefits: [
      {
        title: "Yandex Cloud · Selectel · Cloud.ru",
        text: "Hosting options and infrastructure in Russia — data stays in the perimeter you need.",
      },
      {
        title: "Kaspersky — protection layer",
        text: "Linux, container and cloud workload protection as an optional AI-perimeter layer — not a standalone product pitch.",
      },
      {
        title: "Code and documentation handover",
        text: "Lower vendor lock-in: repository, access and runbook stay with you.",
      },
      {
        title: "NDA before kickoff",
        text: "Safe discussion of processes and data before sharing architecture and samples.",
      },
    ],
    partnerPrograms: {
      "yandex-cloud": "Yandex Cloud Partner",
      selectel: "Selectel Partner Program",
      cloudru: "Cloud.ru Technology Partner",
      kaspersky: "Authorized Partner of Kaspersky Lab",
    },
  },
  securedAi: {
    architectureLabel: "Architecture",
    architectureTitle: "Corporate AI perimeter, turnkey",
    architectureText:
      "Assessment, architecture, AI components, integrations with 1C / Bitrix24 / amoCRM, and go-live in the cloud or on-premise.",
    architectureSteps: [
      "Data sources",
      "Document intake and processing",
      "OCR and normalization",
      "Corporate knowledge base",
      "RAG / private LLM",
      "Integration with 1C, Bitrix24 and amoCRM",
      "Server and infrastructure protection",
      "Monitoring, logging and access control",
    ],
    ctaPrimary: "Discuss a project",
    ctaSecondary: "Estimate architecture",
  },
  packages: {
    title: "Work formats",
    subtitle:
      "One budget ladder: audit, pilot and production implementation. Fixed scope before kickoff.",
    items: [
      {
        name: "Audit",
        price: "from €1,500",
        duration: "1–2 weeks",
        forWhom: "Processes are losing money — you need a map and priorities",
        result: "Process map, loss points and automation priorities",
        includes: ["Process and data audit", "ROI calculation by scenario", "Technology recommendations"],
        tier: "audit",
        detailsHref: "/services/ai-discovery-roadmap",
      },
      {
        name: "Pilot",
        price: "from €3,000",
        duration: "2–4 weeks",
        forWhom: "Validate a scenario on real data before a full rollout",
        result: "Working pilot on one process with metrics and a scale-up plan",
        includes: ["Pilot on real scenarios", "Integration with a core system", "Metrics and production rollout plan"],
        tier: "pilot",
        detailsHref: "/services/business-process-automation",
      },
      {
        name: "Production implementation",
        price: "from €5,000",
        duration: "4–12 weeks",
        forWhom: "Automating CRM, documents, sales or support",
        result: "Production launch with documentation and team handover",
        includes: ["Development and integration", "Testing and deployment", "Documentation and team handover"],
        featured: true,
        tier: "implementation",
        detailsHref: "/services/business-process-automation",
      },
      {
        name: "Support",
        price: "from €2,000/mo",
        duration: "ongoing",
        forWhom: "Support and evolution of automation after launch",
        result: "Monitoring, iterations and priority support",
        includes: ["Monitoring and SLA", "Process iterations", "Priority support"],
        tier: "support",
        detailsHref: "/services/business-process-automation",
      },
    ],
    cta: "Get a preliminary estimate",
    featuredLabel: "CORE FORMAT",
    detailsLabel: "Details",
    auditNote: "The audit fee is credited toward the project budget if we continue to implementation.",
    urgency:
      "I typically run only a few projects at a time. The next window for a new implementation opens after the current one completes.",
  },
  microConversions: {
    label: "Next step",
    title: "Not ready for full implementation — start smaller",
    subtitle: "Choose a no-obligation format. Response within 4 business hours.",
    items: [
      {
        title: "Schedule a call",
        description: "30 minutes: we review the task, processes and expected business impact.",
        cta: "Schedule a call",
        service: "Discovery call",
      },
      {
        title: "Get an estimate",
        description: "Preliminary quote and work plan — within 24 hours after the brief.",
        cta: "Get an estimate",
        service: "Project estimate",
      },
      {
        title: "AI audit",
        description: "Process map, loss points and payback calculation — from €1,500.",
        cta: "Order an audit",
        service: "AI audit",
      },
      {
        title: "Architecture review",
        description: "Review of the current scheme, integrations and risks before scaling.",
        cta: "Assess architecture",
        service: "Architecture review",
      },
    ],
  },
  comparison: {
    label: "Comparison",
    title: "Why not ChatGPT, SaaS, or “just hire another employee”",
    subtitle: "Custom implementation gives control over data, integrations and process economics.",
    items: [
      {
        title: "ChatGPT / Claude in the browser",
        problem: "No CRM access, no audit logs, data leaves to a third-party service, employees copy and paste by hand.",
        solution: "We deploy AI in your perimeter: amoCRM, Bitrix24, 1C, documents — under NDA with fixed scope.",
      },
      {
        title: "Hiring another employee",
        problem: "Payroll grows every month, ramp-up takes months, a person doesn’t scale on peak load.",
        solution: "For processes with enough repeat volume, automation often pays back in months — we calculate from actual load before kickoff; the system runs 24/7.",
      },
      {
        title: "Off-the-shelf SaaS",
        problem: "Doesn’t fit your processes, vendor lock-in, data in someone else’s cloud.",
        solution: "We build for your stack: your perimeter, code handover, turnkey integrations.",
      },
    ],
  },
  results: {
    label: "Results",
    title: "What changes after implementation",
    items: [
      { stat: "45 min → 2–5 min", label: "proposal prep in a pilot process (client-reported)" },
      { stat: "up to 80%", label: "line items auto-recognized in procurement docs on pilot" },
      { stat: "24/7", label: "processing of new requests, no downtime" },
      { stat: "Fewer manual errors", label: "thanks to data validation at every step" },
    ],
    note: "Outcomes depend on the process — we lock metrics before kickoff and measure on the pilot; we don’t publish absolute numbers without methodology.",
  },
  problemSolution: {
    label: "Problem → solution",
    title: "What usually gets in the way — and what changes after implementation",
    subtitle: "Situations we see most often before clients start working with us.",
    items: [
      {
        title: "Employees manually re-enter data",
        problem: "Requests arrive by email and messengers, then get typed into CRM and ERP by hand. It takes hours and creates errors.",
        solution: "The system extracts the data, validates it and updates the right systems automatically.",
      },
      {
        title: "Commercial offers take too long to prepare",
        problem: "A manager searches for products, checks prices, finds substitutes and assembles the document manually.",
        solution: "The system processes the request, finds the matching items and generates a ready offer under set rules.",
      },
      {
        title: "Employees can't find information",
        problem: "Policies, instructions and contracts are scattered across folders and internal systems.",
        solution: "An employee asks in plain language and gets an answer with a link to the source.",
      },
      {
        title: "There's an AI pilot, but no one can actually use it",
        problem: "The prototype only works on ideal examples, isn't integrated with your systems and doesn't handle errors.",
        solution: "The production version runs on real data, logs every action and escalates exceptions to a person.",
      },
    ],
  },
  roiCalculator: {
    label: "ROI",
    title: "ROI calculator for AI automation of CRM and documents",
    subtitle:
      "Enter employee count, routine hours and salary — get a savings range, payback period and the data list needed for an audit.",
    employeesLabel: "People in the process",
    hoursLabel: "Repetitive hours per person / week",
    salaryLabel: "Average salary, €",
    savingsLabel: "mo",
    resultLabel: "Estimated savings",
    resultNote: "Indicative only. Exact numbers after a process and data audit.",
    paybackLabel: "Payback for implementation from €5,000",
    paybackSuffix: "mo",
    currency: "€",
    implementationFloor: "5000",
    auditDataTitle: "What we need for an accurate audit",
    auditDataItems: [
      "Process description and employee roles",
      "Systems: CRM, ERP, email, documents",
      "Weekly / monthly operation volume",
      "Current bottlenecks and errors",
      "Perimeter requirements: cloud / on-prem / NDA",
    ],
    captureCta: "Get the estimate by email / Telegram",
    gateTitle: "Where should we send the estimate",
    gateSubtitle:
      "We'll send the calculation summary and an audit checklist. No commitment — you choose the next step.",
    emailLabel: "Email",
    emailPlaceholder: "you@company.com",
    telegramLabel: "Telegram",
    telegramPlaceholder: "@username or phone",
    gateSubmit: "Send estimate",
    gateSubmitting: "Sending…",
    gateSuccessTitle: "Estimate ready to send",
    gateSuccess:
      "Your email client will open with the summary. We reply within 4 business hours — with an audit plan or a project discussion.",
    nextCtaPrimary: "Discuss a project",
    nextCtaSecondary: "Book an audit",
    cta: "Get exact calculation",
  },
  services: {
    title: "What we implement",
    subtitle: "One core competence — AI in company operations. Below are the areas where it delivers measurable results.",
    details: "Details",
    quote: "Request a quote",
    days: "days",
    discussCta: "Discuss implementation",
    implementationAreas: [
      {
        badge: "Support",
        title: "Customer service",
        description: "24/7 first line, escalation for complex cases, CRM logging — no lost requests.",
        items: ["Ticket triage", "FAQ & knowledge base", "CRM case logging"],
        layout: "wide",
        featured: true,
        slug: "enterprise-ai-assistant",
        href: "/services/ai-agent",
      },
      {
        badge: "CRM",
        title: "CRM integrations",
        description: "amoCRM, Bitrix24, 1C — data sync, pipeline automation, zero duplicate entry.",
        items: ["CRM implementation", "1C / ERP sync", "Messenger & webhooks"],
        layout: "large",
        slug: "business-process-automation",
        href: "/services/crm-integration",
      },
      {
        badge: "Documents",
        title: "Document processing",
        description: "Approvals, data extraction, routing — documents flow to CRM/ERP without manual re-entry.",
        items: ["OCR & field extraction", "Approval workflows", "CRM / 1C integration"],
        layout: "default",
        slug: "business-process-automation",
        href: "/services/document-processing",
      },
      {
        badge: "Sales",
        title: "Sales automation",
        description: "Proposals in minutes, lead routing, CRM and email follow-up — faster pipeline.",
        items: ["Proposal generation from CRM", "Lead qualification & routing", "Follow-up automation"],
        layout: "default",
        slug: "sales-ai-agent",
        href: "/services/sales-ai-agent",
      },
      {
        badge: "HR",
        title: "HR & onboarding",
        description: "Onboarding portal, policy search, employee Q&A — less load on HR and managers.",
        items: ["Onboarding checklists", "Policy & benefits Q&A", "HR system integrations"],
        layout: "compact",
        slug: "enterprise-ai-assistant",
        href: "/services/knowledge-base",
      },
      {
        badge: "Team",
        title: "Employee assistants",
        description: "Internal helpers over your documents and policies — answers with source citations.",
        items: ["Knowledge base search", "SOP & policy assistant", "Slack / Telegram integration"],
        layout: "compact",
        slug: "enterprise-ai-assistant",
        href: "/services/rag",
      },
    ],
    items: [
      {
        slug: "business-process-automation",
        title: "Business process automation",
        description: "Audit, CRM/ERP integrations, workflow — task chains without manual routine.",
        salesNotes: "from €4,000",
        deliveryDays: 21,
      },
      {
        slug: "sales-ai-agent",
        title: "Sales department automation",
        description: "Leads, CRM, proposals, follow-up — PDF in minutes, not hours.",
        salesNotes: "from €4,000",
        deliveryDays: 14,
      },
      {
        slug: "business-process-automation",
        title: "Document workflow automation",
        description: "OCR, approvals, classification, workflow — AI only where it adds advantage.",
        salesNotes: "from €4,000",
        deliveryDays: 21,
      },
      {
        slug: "enterprise-ai-assistant",
        title: "Corporate knowledge base",
        description: "Knowledge base, document search, chatbot for employees and clients.",
        salesNotes: "from €5,000",
        deliveryDays: 28,
      },
      {
        slug: "ai-discovery-roadmap",
        title: "AI & Automation Advisor",
        description: "We analyze the process, calculate ROI, choose technology, implement.",
        salesNotes: "from €1,500",
        deliveryDays: 10,
      },
      {
        slug: "enterprise-ai-assistant",
        title: "AI implementation",
        description: "LLM, agents, CRM integrations — production, not a ChatGPT pilot.",
        salesNotes: "from €5,000",
        deliveryDays: 28,
      },
    ],
  },
  process: {
    title: "Implementation timeline",
    subtitle: "Five stages from discovery to support. Technology is chosen after ROI is calculated.",
    steps: [
      { title: "Map the process", text: "Where your team loses time, where errors happen, which systems are in play." },
      { title: "Define the outcome", text: "Scenarios, metrics, timeline and project scope." },
      { title: "Connect data and systems", text: "CRM, ERP, email, documents, messengers, internal databases." },
      { title: "Ship a pilot", text: "Validate the system on real tasks and edge cases." },
      { title: "Go to production", text: "Set up monitoring, documentation and handover to your team." },
    ],
  },
  deliverables: {
    label: "Artifacts",
    title: "What the company gets",
    subtitle: "Not diplomas or certificates — working artifacts before build and after production launch.",
    beforeTitle: "Before development starts",
    afterTitle: "After go-live",
    before: [
      "Process map and loss points",
      "Loss / savings estimate",
      "Solution architecture and integration list",
      "Fixed scope and acceptance criteria",
    ],
    after: [
      "System in production on real data",
      "Code and environment access",
      "Documentation, logging and monitoring",
      "Runbooks and handover to your IT team",
      "Stabilization window after launch",
    ],
  },
  beforeAfterDemo: {
    label: "Before / After",
    title: "Proposal automation: from 45 minutes to 2–5 minutes",
    subtitle:
      "Same process — different loop. Demo of a typical flow: PDF request → catalog → document → CRM.",
    demoNote: "Demo UI fragment — not a client production screenshot",
    beforeLabel: "Before automation",
    afterLabel: "After go-live",
    beforeMetric: "~45 min",
    afterMetric: "2–5 min",
    beforeSteps: [
      { label: "Client PDF request", status: "Manual" },
      { label: "Search items in catalog", status: "Manual" },
      { label: "Copy prices and calculate VAT", status: "Excel / Word" },
      { label: "Assemble Word and send", status: "Email" },
    ],
    afterSteps: [
      { label: "PDF request ingested", status: "Input" },
      { label: "Catalog match", status: "Auto" },
      { label: "Status: exact / analog / not found", status: "Check" },
      { label: "DOCX / PDF + CRM write", status: "Output" },
    ],
    flow: ["PDF", "Catalog table", "Row statuses", "DOCX / PDF"],
  },
  auditSample: {
    label: "Audit",
    title: "AI audit sample — what the from-€1,500 package delivers",
    subtitle:
      "A miniature report: process map, losses, impact/complexity matrix, 30/60/90 plan, risks and acceptance.",
    demoNote: "Demo fragment — report structure example, not a specific client’s data",
    cards: [
      {
        title: "Process map",
        text: "Request → catalog → quote → CRM with bottlenecks and manual steps marked.",
      },
      {
        title: "Impact / complexity matrix",
        text: "Priorities: quick wins vs. longer integration cycles.",
      },
      {
        title: "30 / 60 / 90 plan",
        text: "Pilot on one process → expand → stabilize and hand over.",
      },
      {
        title: "Risks & acceptance",
        text: "Data gaps, access rights, human escalation, readiness criteria.",
      },
    ],
    tableTitle: "Sample impact table (illustrative)",
    tableHeaders: ["Process", "Hours / mo.", "Impact", "Complexity"],
    tableRows: [
      ["Proposal prep", "80", "High", "Medium"],
      ["Inbound mail triage", "40", "Medium", "Low"],
      ["PDF field extraction", "60", "High", "High"],
    ],
  },
  preLaunch: {
    label: "Before launch",
    title: "What we check before go-live",
    subtitle: "Quality and safety checklist — before production traffic.",
    acceptanceNote: "Test scenarios and acceptance criteria are defined before development starts.",
    items: [
      "Answers on real data, not ideal examples",
      "Behavior when data is missing",
      "Access rights and perimeter boundaries",
      "Prompt-injection resilience",
      "No invented prices or documents",
      "Human escalation on low confidence",
      "Action logging and cost per process",
      "Latency under load",
      "Kill switch — ability to stop automation",
    ],
  },
  architecturePlain: {
    label: "Architecture",
    title: "Architecture without magic",
    subtitle: "AI is one layer in the loop — not a black box with access to everything.",
    note: "AI does not get unrestricted access to company systems: only required sources, audit logs and write rules.",
    steps: [
      "Ingress: PDF, email, CRM, form",
      "Rules & catalog: prices, SKUs, permissions",
      "AI layer: parse, classify, draft",
      "Checks and human escalation",
      "Write to CRM / document / notification",
    ],
  },
  whereAiNotNeeded: {
    label: "Boundaries",
    title: "Where AI is not needed",
    subtitle: "Plain automation first — AI only where rules cannot cover the work.",
    items: [
      "Direct SQL sync and master-data exchange",
      "CRM rules: stages, robots, assignment",
      "Routine ERP operations without free-text parsing",
      "RPA / workflow when steps are deterministic",
    ],
  },
  exclusions: {
    label: "Out of scope",
    title: "What we don’t take on",
    items: [
      "Demo-for-demo with no path to production",
      "Projects without process/data access for acceptance",
      "“AI will fix everything” without a measurable scenario",
      "Supporting third-party code with no docs or owner",
    ],
  },
  security: {
    title: "Security and compliance",
    items: [
      "NDA before work starts — standard for every enterprise project",
      "Deployment in your perimeter — data never leaves your infrastructure",
      "152-FZ for Russian deployments: personal-data policy, consent, processing agreement",
      "Access controls, audit logs, data encryption",
      "Keys and models under client control — no contractor lock-in",
      "Monitoring, alerts and SLA support for production systems",
      "Data processing agreement and IP assignment in every B2B contract",
    ],
  },
  whyTrust: {
    label: "Why us",
    title: "Why you can trust us with the implementation",
    items: [
      "Not tied to one model — we pick the solution for the process, data and infrastructure",
      "We work with the systems you already use — Bitrix24, amoCRM, 1C, email, messengers, your API",
      "We deploy in a closed perimeter — client cloud, on-prem server, NDA",
      "We lock boundaries before development — scope, cost, risks, acceptance criteria",
      "We hand the solution over to your company — code, instructions, access, documentation",
      "I'm personally accountable for the architecture — 7 years in AI, publications, project experience: corporate RAG and AI assistants",
    ],
  },
  timeline: {
    label: "Timeline",
    title: "When you'll see results",
    items: [
      { period: "1–2 weeks", text: "audit, process mapping and data preparation" },
      { period: "3–6 weeks", text: "a working pilot" },
      { period: "6–12 weeks", text: "integration and production launch" },
      { period: "After launch", text: "measuring results and optimizing" },
    ],
    note: "The exact timeline depends less on model size than on data quality, the number of integrations and the number of edge cases in the process.",
  },
  partners: {
    badge: "For integrators and software houses",
    title: "Partnership models",
    subtitle: "You face the client, we deliver architecture, code and implementation",
    description:
      "Three collaboration formats. NDA, fixed timelines, documentation for your team. Bitrix24, amoCRM, 1C, REST API.",
    steps: [
      { title: "White-label delivery", text: "Your brand, our engineering. Architecture, code, implementation and handover under NDA." },
      { title: "Technology partnerships", text: "Joint projects with CRM/ERP integrators. Fixed estimate for your PM." },
      { title: "Referral partnerships", text: "You bring the client — we discuss terms after the brief. Transparent, no public percentages." },
    ],
    models: [
      "White-label delivery",
      "Technology partnerships",
      "Referral partnerships",
    ],
    cta: "Discuss partnership",
  },
  about: {
    title: "About the company",
    tagline: "Business transformation partner · Bober AI Systems",
    imageAlt: "Team implementing business process automation",
    text: "Bober AI Systems is a team that designs and implements automation for companies. CRM, documents, sales, support — with fixed scope, milestones, and handover to your team.\n\nNot a freelance marketplace or a ChatGPT demo. We work as an external automation department: audit → roadmap → production → support. Case studies: ELIA Suite, proposal and document automation, corporate RAG assistants.\n\nWe respond within 4 business hours. NDA before kickoff.",
    approach: "Approach",
    approachValue: "Process and ROI first, technology second. Fixed scope, milestone delivery, measurable outcomes.",
    schedule: "Schedule",
    scheduleValue: "Mon–Fri, response within 4h",
    collaboration: "Engagement",
    collaborationSummary: "Fixed estimate or ongoing support. Milestone delivery with acceptance acts.",
    collaborationDetail: "Contract, NDA, IP assignment — standard for B2B.",
    skillsTitle: "Expertise",
    skills: [
      "Business process automation",
      "CRM: amoCRM, Bitrix24, 1C",
      "Document workflow and OCR",
      "Sales and proposal automation",
      "Corporate knowledge base",
      "AI agents and assistants",
      "Your perimeter and 152-FZ",
      "Yandex Cloud · Selectel",
    ],
    techStackTitle: "Technologies",
    techStack: "GPT · Claude · Gemini · Llama · YandexGPT · GigaChat · n8n",
    cta: "Discuss a project",
  },
  reviews: {
    title: "Client reviews",
    subtitle: "28 ratings on Yandex · verified reviews on AI, ML and production implementations",
    yandexTitle: "Yandex",
    yandexMeta: "Rating {rating} · {count} reviews",
  },
  media: {
    label: "MEDIA & CREDIBILITY",
    title: "Pawel Stasinski — expert commentary and media publications",
    subtitle: "Interviews, industry commentary, technical articles and international delivery experience.",
    body: "Bober AI founder Pawel Stasinski provides expert commentary for Russian media, publishes technical articles on Habr and Medium, and delivers projects for international clients. Media presence and publications substantiate practical experience in AI implementation and business process automation.",
    proofItems: [
      "Expert commentary in the media",
      "Technical publications on Habr and Medium",
      "International delivery experience",
      "10+ years in engineering and AI",
    ],
    tabRussian: "Russian market",
    tabInternational: "International expertise",
    dossierCta: "View all publications and appearances",
    closing:
      "Publications, interviews and confirmed international delivery experience — an open basis for evaluating expertise before engagement.",
    asSeenIn: "Sources",
    videoCta: "Watch interview",
    articleCta: "Read article",
    videoAriaLabel: "Open {publisher} interview",
    articleAriaLabel: "Open {publisher} article: {title}",
    footerNote: "Available for expert commentary, interviews, and industry speaking engagements.",
    footerLinkLabel: "Suggest a topic",
  },
  portfolio: {
    title: "Case studies",
    subtitle: "Three implementation examples — measurable result first, technology second",
    allCases: "All case studies",
    metricLabel: "Key result",
    stackLabel: "Stack",
    details: "More about the project",
    priceFrom: "from",
    problemLabel: "Challenge",
    solutionLabel: "Solution",
    resultLabel: "Result",
    categoriesLabel: "Directions",
  },
  cta: {
    title: "Get an implementation estimate",
    subtitle: "Describe the task — a preliminary plan and quote within 24 hours.",
    primary: "Get an estimate",
    secondary: "Telegram",
  },
  sectionCta: {
    title: "Get an estimate in 30 minutes",
    duration: "30 minutes",
    commitment: "no commitment",
    format: "online",
    cta: "Get an estimate",
    urgency:
      "After you submit: a short brief → a preliminary plan and budget range within 4 business hours. NDA available before sharing data.",
  },
  claude: {
    label: "Claude · Anthropic",
    title: "Claude AI for business — implementation and automation",
    subtitle:
      "Claude AI, Claude API, Claude Code and Claude MCP are among the most searched terms. We don't sell a subscription or set up a personal account: we implement Claude into company processes — CRM, documents, sales, support and knowledge base.",
    popularLabel: "Popular Claude searches",
    terms: [
      "Claude AI",
      "Claude API",
      "Claude Code",
      "Claude MCP",
      "Claude Agent",
      "Claude neural network",
      "Claude Opus",
      "Claude Sonnet",
      "Claude Pro",
      "Claude in Russia",
      "Anthropic API",
      "Claude Skills",
    ],
    glossaryLink: "All Claude questions — in the glossary",
    cta: "Discuss Claude implementation",
  },
  faq: {
    label: "FAQ",
    title: "Frequently asked questions",
    subtitle: "Answers for procurement, IT and business owners.",
    items: [
      { q: "How much does AI implementation cost?", a: "Audit — from €1,500. Pilot — from €3,000. Production implementation — from €5,000. Fixed scope before development starts." },
      { q: "How long does implementation take?", a: "Discovery: 1–2 weeks. Prototype: 2–4 weeks. Production launch: 4–12 weeks — depending on integrations and data requirements." },
      { q: "Does it integrate with amoCRM, Bitrix24 and 1C?", a: "Yes. CRM/ERP is a core competency: bidirectional sync, webhooks, document flows, retry on failures." },
      { q: "Can you deploy in our own perimeter?", a: "Yes. On-prem, isolated VPC, Yandex Cloud, Selectel, Cloud.ru — data stays in your infrastructure." },
      { q: "When does AI actually make sense?", a: "When manual work is repetitive, documents are unstructured or support volume is high. We start with an ROI calculation — not hype." },
      { q: "What if the AI makes a mistake?", a: "We design human-in-the-loop, confidence thresholds, action logs and escalation to an employee. Critical operations require human confirmation." },
      { q: "Does it work with confidential data?", a: "NDA before kickoff, DPA, 152-FZ, encryption, audit logs. Keys and models stay under client control." },
      { q: "What types of companies do you work with?", a: "Mid-market and enterprise companies, CRM/ERP integrators and software houses that need production AI delivery under NDA — not one-off chatbot demos." },
      { q: "Do you sign an NDA before the first call?", a: "Yes. NDA is standard before sharing architecture, data samples or internal documentation." },
      { q: "What is a typical project budget?", a: "Audit — from €1,500, pilot — from €3,000, production implementation — from €5,000. We lock the estimate before development starts — no hidden stages." },
      { q: "How long does a rollout take?", a: "See the answer above. Timeline depends on the number of integrations and compliance requirements." },
      { q: "What LLM providers do you use?", a: "Claude, OpenAI, YandexGPT, GigaChat — by compliance, language and cost. API keys and infrastructure can stay with the client." },
      { q: "What is RAG and when do you recommend it?", a: "Retrieval-Augmented Generation connects an LLM to your documents. We recommend it for support, sales and internal knowledge bases." },
      { q: "Do you build AI agents or only chatbots?", a: "Both — but the focus is on agents that take actions: update CRM, generate documents, trigger workflows, escalate to a human." },
      { q: "Do you integrate with n8n or existing automation?", a: "Yes. We extend n8n, Zapier or your chains with an AI layer and API integrations." },
      { q: "How do you handle GDPR and 152-FZ?", a: "DPA, consents, retention policies, architecture review before go-live. Russian deployments follow 152-FZ requirements." },
      { q: "Do you provide SLA and monitoring?", a: "Yes — optional post-launch support: monitoring, alerts, iteration backlog, response-time agreements." },
      { q: "Who owns the code and IP?", a: "The client, per contract. We hand over repositories, documentation and a deployment runbook." },
      { q: "Do you offer white-label for integrators?", a: "Yes. The partner faces the client; we deliver under NDA with documentation for your PM and engineers." },
      { q: "What does the first engagement look like?", a: "30-minute discovery → AI & Automation Audit → fixed roadmap and estimate → phased implementation with acceptance acts." },
      { q: "Can you rescue a failed AI pilot?", a: "Often yes. We audit architecture, data quality and integrations, then rebuild for production with measurable KPIs." },
      { q: "Do you support voice AI and call centers?", a: "Yes — speech-to-text, voice bots, CRM logging for inbound and outbound calls." },
      { q: "What about OCR and document processing?", a: "OCR pipelines for invoices, contracts and scans with field extraction and export to 1C, CRM or ERP." },
      { q: "Do you deploy Open WebUI or self-hosted LLM?", a: "Yes. Self-hosted stacks with Open WebUI, private models, guardrails and SSO for internal teams." },
      { q: "What is MCP and do you implement it?", a: "Model Context Protocol connects LLMs to tools and data sources. We build MCP servers for CRM, databases and internal APIs." },
      { q: "Do you use LangGraph for agents?", a: "Yes, for multi-step agents with state, human-in-the-loop and observability — when complexity exceeds simple chains." },
      { q: "How do you measure ROI?", a: "Baseline manual hours, errors and conversion before launch. We report the delta after 30/60/90 days." },
      { q: "What industries have you already delivered in?", a: "Cybersecurity (Kaspersky product RAG bot for 1C staff), B2B sales, legislative monitoring, education, banking media, integrator subcontracting." },
      { q: "How fast do you respond to new requests?", a: "Within 4 business hours. Preliminary scope and estimate — within 24 hours after the discovery call." },
      {
        q: "Are you an official Kaspersky partner?",
        a: "Yes. Bober AI is an Authorized Partner of Kaspersky Lab and can officially supply Kaspersky corporate products. This is an optional add-on to AI projects — not the core focus.",
      },
      {
        q: "Can Kaspersky be included in an AI implementation project?",
        a: "Yes. Kaspersky solutions can be part of the overall project architecture to protect servers, workplaces, virtual and cloud infrastructure — when the customer needs them.",
      },
      {
        q: "Do you only implement Kaspersky products?",
        a: "No. Bober AI’s core focus is corporate AI systems, automation and integrations. Kaspersky solutions are used as part of the infrastructure stack when needed.",
      },
      {
        q: "Can you install in the customer’s perimeter?",
        a: "Yes. On-premise, Russian clouds and hybrid architectures are supported.",
      },
      {
        q: "Can we buy licenses only?",
        a: "Yes, but Bober AI’s main value is solution selection, architecture, implementation, integration and support for AI and automation.",
      },
    ],
  },
  contact: {
    title: "Get a project estimate",
    subtitle:
      "Name and contact are enough. In 30 minutes we review the task — within 4 business hours you get a preliminary plan and budget range.",
    afterSubmit:
      "After submit, your email client opens with the request. We reply within 4 business hours: clarify the process and send a timeline and budget orientation.",
    email: "Email",
    telegram: "Telegram",
    whatsapp: "WhatsApp",
    phone: "Phone",
    linkedin: "LinkedIn",
    github: "GitHub",
    modalClose: "Close",
    fabLabel: "Get an estimate",
    modalChannels: "Or reach out directly",
    modalFormDivider: "Or leave a request",
  },
  form: {
    intro:
      "Name and contact are enough for the first step. A task description is optional.",
    name: "Name",
    company: "Company",
    phone: "Phone or Telegram",
    phonePlaceholder: "+1… or @telegram",
    email: "Email",
    emailPlaceholder: "you@company.com",
    contact: "Email or phone",
    contactPlaceholder: "you@company.com or +1…",
    message: "Brief task description",
    messagePlaceholder: "e.g. PDF proposals into CRM, Bitrix24 ↔ ERP sync",
    deployment: "Where should the system run",
    deploymentOptions: ["Cloud", "On-premise", "Hybrid"],
    kasperskyNeed: "Optional infrastructure protection (Kaspersky)",
    kasperskyOptions: ["Yes", "No", "Let's discuss"],
    selectPlaceholder: "Select an option",
    optional: "(optional)",
    consentCombined: "I have read the",
    policyLink: "privacy policy",
    consentAnd: "and give",
    consentLink: "consent to personal data processing",
    submit: "Get an estimate",
    submitting: "Sending…",
    successTitle: "Request ready",
    success:
      "Your email client will open with the request. We reply within 4 business hours — with a next step and a budget orientation.",
    errorConsent: "Please confirm consent to personal data processing",
    errorSend: "Failed to send request",
    errorGeneric: "Send error",
  },
  diagnosticForm: {
    eyebrow: "Preliminary estimate",
    title: "Leave a request — we'll review your process within 4 hours",
    progressLabel: "Step {current} of {total}",
    back: "Back",
    finalCta: "Get a preliminary estimate",
    steps: [
      {
        question: "What do you want to improve?",
        options: [
          "Sales and request handling",
          "Documents and commercial offers",
          "CRM or ERP",
          "Employee support",
          "Another process",
        ],
      },
      {
        question: "Where does the work happen today?",
        options: ["Bitrix24", "amoCRM", "ERP / 1C", "Excel / Google Sheets", "Email and messengers", "Our own system"],
      },
      {
        question: "What's the main outcome you need?",
        options: [
          "Reduce manual work",
          "Speed up responses",
          "Reduce errors",
          "Track metrics",
          "Replace an existing solution",
        ],
      },
      {
        question: "Scale",
        options: ["Up to 10 employees", "10–50", "50–200", "More than 200"],
      },
      {
        question: "Estimated budget",
        options: ["Up to €5,000", "€5,000–€10,000", "€10,000–€20,000", "More than €20,000", "Need an estimate first"],
      },
    ],
  },
  footer: {
    legalName: "IE Pavel Stasinsky",
    terms: "Service terms",
    privacy: "Privacy policy",
    consent: "Data processing consent",
    profiles: "Profiles & verification",
    sectionsTitle: "Site sections",
    sqiTitle: "Yandex Site Quality Index (SQI)",
    sqiAlt: "Yandex Site Quality Index",
    presence: {
      linkedin: "LinkedIn",
      github: "GitHub",
      yandexReviews: "Yandex reviews",
      yandexMaps: "Yandex Maps",
      yandexBusiness: "Yandex Business",
      yandexCloud: "Yandex Cloud partner catalog",
      selectel: "Selectel Partner Program",
      cloudru: "Cloud.ru partner directory",
    },
  },
  banner: {
    badge: "For integrators",
    title: "White-label delivery for partners",
    text: "Your brand, our engineering. Subcontract under NDA — terms discussed per project.",
    cta: "Discuss partnership",
    more: "Learn more",
    close: "Close",
  },
  common: {
    siteName: "Bober AI Systems",
    online: "Online",
    readMore: "Learn more",
    viewCaseStudy: "View case study",
  },
  servicePage: {
    back: "All solutions",
    includes: "What''s included",
    deliverables: [
      "Task audit and scope agreement",
      "Development and configuration",
      "Testing and production deployment",
      "Documentation and team handover",
    ],
    timeline: "Timeline",
    days: "days",
    quote: "Request a quote",
    telegram: "Message on Telegram",
    formTitle: "Or leave a request",
    listTitle: "Business problem solutions",
  },
  partnersPage: {
    title: "Partners",
    subtitle: "White-label delivery · Technology partnerships · Referral partnerships",
    metaDescription:
      "Partner with Bober AI Systems: white-label automation delivery, technology and referral partnerships. Fixed scope, NDA.",
  },
  guides: {
    badge: "Guides",
    cta: "Request audit",
    telegram: "Telegram",
  },
  landing: {
    common: {
      backHome: "Home",
      cta: "Request a quote",
      telegram: "Telegram",
      service: "Package",
      serviceDetails: "Service details",
      timeline: "Timeline",
      days: "days",
      contact: "Contact",
      formTitle: "Discuss your project",
      formSubtitle: "Describe the process or integration — we reply within 4 business hours.",
      faqTitle: "FAQ",
      caseStudiesTitle: "Case studies",
      viewCaseStudy: "View case study",
      featuredCase: "Featured case",
      problemLabel: "Problem",
      solutionLabel: "Solution",
      resultLabel: "Result",
    },
    pages: {
      processes: {
        metaTitle: "Business process automation — implementation",
        metaDescription: "Business process automation for companies: audit, CRM/ERP integrations, production launch and team handover.",
        metaKeywords: [
          "business process automation",
          "workflow automation",
          "process automation company",
          "BPM implementation",
          "business automation system",
          "process optimization",
        ],
        eyebrow: "Automation",
        h1: "Business process automation for companies",
        subtitle: "We design and implement process automation — sales, documents, approvals, CRM. AI only where it removes manual work.",
        problemsTitle: "When you need this",
        problems: ["Teams duplicate the same steps across CRM, email and spreadsheets", "Processes depend on specific people", "You need implementation, not another SaaS shelfware"],
        deliverablesTitle: "Deliverables",
        deliverables: ["Process map and automation points", "CRM, ERP, messenger and document integrations", "Production launch, monitoring and handover"],
        relatedTitle: "Related",
        related: [
          { href: "/automation/documents", label: "Document automation" },
          { href: "/integrations/crm", label: "CRM implementation" },
          { href: "/ai/corporate", label: "Enterprise AI" },
        ],
        faq: [
          {
            q: "How long does process automation take?",
            a: "A typical scope is 4–6 weeks. Complex CRM, ERP and document integrations may take up to 3 months. We fix the timeline in the estimate after audit.",
          },
          {
            q: "Can you deploy on-prem?",
            a: "Yes. We deploy in your infrastructure or on Russian cloud providers — Yandex Cloud, Selectel, Cloud.ru.",
          },
          {
            q: "Which systems do you integrate with?",
            a: "amoCRM, Bitrix24, 1C, Telegram, email, Google Sheets, Confluence and custom APIs.",
          },
          {
            q: "How do you measure results?",
            a: "We agree on metrics before launch: cycle time, manual work share, lead handling speed. After go-live — monitoring and reporting.",
          },
        ],
      },
      crm: {
        metaTitle: "CRM implementation and automation",
        metaDescription: "CRM implementation, setup and pipeline automation. amoCRM, Bitrix24, ERP integrations.",
        metaKeywords: [
          "CRM implementation",
          "CRM for business",
          "CRM automation",
          "CRM setup",
          "sales pipeline automation",
          "CRM integration",
        ],
        eyebrow: "CRM",
        h1: "CRM implementation & automation",
        subtitle: "CRM is not just software selection — we configure processes, integrations and automation for your sales or ops team.",
        problemsTitle: "Typical problems",
        problems: ["CRM exists but managers work around it", "No link between CRM, documents and ERP", "You need pipeline automation, not manual reporting"],
        deliverablesTitle: "What we do",
        deliverables: ["Pipeline audit and CRM setup", "amoCRM / Bitrix24 / 1C integrations", "Task, notification and document automation"],
        relatedTitle: "Integrations",
        related: [
          { href: "/integrations/amocrm", label: "amoCRM integration" },
          { href: "/integrations/bitrix24", label: "Bitrix24" },
          { href: "/automation/sales", label: "Sales automation" },
        ],
        faq: [
          {
            q: "How much does CRM implementation cost?",
            a: "It depends on process scope and integrations. Typical projects start from €4,000. We provide a fixed estimate after the brief.",
          },
          {
            q: "Do you work with amoCRM and Bitrix24?",
            a: "Yes. We configure pipelines, automations and integrations with website, ERP, messengers and documents.",
          },
          {
            q: "How long does CRM rollout take?",
            a: "Basic setup and integrations — 3–6 weeks. Multi-system scopes — up to 2–3 months.",
          },
          {
            q: "Do you hand over to our team?",
            a: "Yes. We document architecture, run handover and leave monitoring after launch.",
          },
        ],
      },
      corporate: {
        metaTitle: "Enterprise AI implementation",
        metaDescription: "Enterprise AI implementation: production systems, integrations, compliance-ready delivery.",
        metaKeywords: [
          "enterprise AI implementation",
          "AI for business",
          "corporate AI",
          "AI automation",
          "production AI deployment",
          "private AI environment",
        ],
        eyebrow: "Enterprise AI",
        h1: "Enterprise AI implementation — production, not demos",
        subtitle: "AI where you have processes and data: documents, CRM, support, knowledge base.",
        problemsTitle: "When it makes sense",
        problems: ["ChatGPT pilot does not scale to a department", "You need corporate AI inside your perimeter", "You need implementation with team handover"],
        deliverablesTitle: "Outcome",
        deliverables: ["Architecture and model selection", "CRM, document and messenger integrations", "MLOps, monitoring, documentation"],
        relatedTitle: "Related",
        related: [
          { href: "/solutions/knowledge-base", label: "Knowledge base" },
          { href: "/automation/processes", label: "Process automation" },
          { href: "/services/private-llm-gigachat", label: "Private LLM" },
        ],
        faq: [
          {
            q: "How is enterprise AI different from ChatGPT?",
            a: "It runs on your data and infrastructure, integrates with CRM and documents, with access control and monitoring.",
          },
          {
            q: "Which models do you use?",
            a: "YandexGPT, GigaChat, Claude and open-source LLM — depending on data, language and budget requirements.",
          },
          {
            q: "How long does AI implementation take?",
            a: "Pilot — 2–4 weeks. Production scope with integrations — 6–12 weeks.",
          },
          {
            q: "Is the solution compliance-ready?",
            a: "We design for data protection requirements: on-prem, regional clouds, access boundaries.",
          },
        ],
      },
      documents: {
        metaTitle: "Document workflow automation",
        metaDescription: "Document workflow automation: approvals, data extraction, CRM and ERP integrations.",
        metaKeywords: [
          "document workflow automation",
          "document processing automation",
          "approval workflow",
          "electronic document management",
          "contract approval automation",
        ],
        eyebrow: "Documents",
        h1: "Document workflow automation",
        subtitle: "Less manual document handling: intake, approvals, client responses. AI for documents is optional.",
        problemsTitle: "Pain points",
        problems: ["Documents lost between email, CRM and file shares", "Contract approval takes days", "Templates live in scattered files"],
        deliverablesTitle: "We implement",
        deliverables: ["Approval chains and notifications", "Data extraction from PDF/scans", "CRM, ERP and knowledge base links"],
        relatedTitle: "Related",
        related: [
          { href: "/automation/processes", label: "Process automation" },
          { href: "/solutions/knowledge-base", label: "Knowledge base" },
        ],
        faq: [
          {
            q: "Which documents can be automated?",
            a: "Contracts, invoices, acts, inbound mail, approvals and proposal generation from templates.",
          },
          {
            q: "Is AI required for document automation?",
            a: "Not always. We automate routes and integrations first; AI is added for extraction and classification.",
          },
          {
            q: "Do you integrate with ERP and CRM?",
            a: "Yes. We connect document flows with amoCRM, Bitrix24, 1C and internal systems.",
          },
        ],
      },
      sales: {
        metaTitle: "Sales and proposal automation",
        metaDescription: "Sales automation, CRM for sales teams, proposal generation from templates.",
        metaKeywords: [
          "sales automation",
          "proposal automation",
          "CRM for sales",
          "commercial proposal generation",
          "sales workflow automation",
        ],
        eyebrow: "Sales",
        h1: "Sales & proposal automation",
        subtitle: "Faster deal cycle: CRM data → proposal → PDF → client. No copy-paste between spreadsheets.",
        problemsTitle: "Sales team problems",
        problems: ["Managers spend hours on proposals instead of calls", "Templates and price lists are out of sync", "CRM is not linked to documents"],
        deliverablesTitle: "Outcome",
        deliverables: ["Proposal generation from CRM", "Auto-filled pricing and terms", "amoCRM / Bitrix24 integration"],
        relatedTitle: "Related",
        related: [
          { href: "/integrations/crm", label: "CRM implementation" },
          { href: "/services/sales-ai-agent", label: "Sales AI agent" },
        ],
        faq: [
          {
            q: "How much time does proposal automation save?",
            a: "In a typical case — from 45 minutes down to 2 minutes per commercial proposal.",
          },
          {
            q: "Where do prices in proposals come from?",
            a: "Only from your catalog or CRM — no invented line items or model hallucinations.",
          },
          {
            q: "Which CRM systems do you support?",
            a: "amoCRM, Bitrix24 and custom CRM via API.",
          },
        ],
      },
      amocrm: {
        metaTitle: "amoCRM integration and automation",
        metaDescription: "amoCRM integration with website, ERP, messengers and documents.",
        metaKeywords: [
          "amoCRM integration",
          "amoCRM automation",
          "amoCRM API",
          "amoCRM setup",
          "website amoCRM integration",
        ],
        eyebrow: "amoCRM",
        h1: "amoCRM integration for your workflow",
        subtitle: "Connect amoCRM to what you already use: website, Telegram, ERP, document generation.",
        problemsTitle: "Typical request",
        problems: ["Website leads do not reach CRM", "Managers chat outside CRM", "You need website-to-amoCRM integration"],
        deliverablesTitle: "Scope",
        deliverables: ["Webhooks, API, two-way sync", "Stage and task automation", "Proposal and document links"],
        relatedTitle: "Related",
        related: [
          { href: "/integrations/crm", label: "CRM overview" },
          { href: "/integrations/bitrix24", label: "Bitrix24" },
        ],
      },
      bitrix24: {
        metaTitle: "Bitrix24 integration and automation",
        metaDescription: "Bitrix24 integration and automation: CRM, tasks, documents, AI layer.",
        metaKeywords: [
          "Bitrix24 integration",
          "Bitrix24 implementation",
          "Bitrix24 automation",
          "Bitrix24 CRM setup",
          "Bitrix24 integrator",
        ],
        eyebrow: "Bitrix24",
        h1: "Bitrix24: integration & automation",
        subtitle: "We automate CRM workflows and add AI on top.",
        problemsTitle: "When clients come",
        problems: ["Bitrix24 is installed but processes are manual", "Need ERP, telephony and document integrations", "Looking for a Bitrix24 integrator"],
        deliverablesTitle: "Deliverables",
        deliverables: ["CRM and robot setup", "REST API integrations", "AI assistant on Bitrix24"],
        relatedTitle: "Related",
        related: [
          { href: "/integrations/crm", label: "CRM overview" },
          { href: "/integrations/amocrm", label: "amoCRM" },
          { href: "/integrations/1c", label: "1C integration" },
        ],
      },
      onec: {
        metaTitle: "1C integration with CRM — amoCRM, Bitrix24",
        metaDescription: "1C integration with CRM: orders, payments, stock, counterparties. Bidirectional sync without manual duplication.",
        metaKeywords: [
          "1C CRM integration",
          "connect CRM with 1C",
          "1C amoCRM integration",
          "Bitrix24 1C integration",
          "ERP CRM sync",
        ],
        eyebrow: "1C",
        h1: "1C integration with CRM",
        subtitle: "Bidirectional exchange: deals, orders, payments, stock — without copy-paste between systems.",
        problemsTitle: "Typical pains",
        problems: ["Orders created twice in CRM and 1C", "Stock in CRM is outdated", "Payments in 1C don't close deal stages"],
        deliverablesTitle: "What we deliver",
        deliverables: ["Entity map and exchange schema", "API gateway with queue and retry", "Monitoring, reconciliation and documentation"],
        relatedTitle: "Related",
        related: [
          { href: "/integrations/crm", label: "CRM implementation" },
          { href: "/integrations/amocrm", label: "amoCRM" },
          { href: "/integrations/bitrix24", label: "Bitrix24" },
          { href: "/guides/connect-crm-with-1c", label: "Guide: connect CRM with 1C" },
        ],
      },
      knowledgeBase: {
        metaTitle: "Corporate knowledge base setup",
        metaDescription: "Knowledge base setup: document search, FAQ, AI assistant for employees.",
        metaKeywords: [
          "knowledge base setup",
          "corporate knowledge base",
          "AI knowledge base",
          "internal wiki",
          "document search for employees",
        ],
        eyebrow: "Knowledge base",
        h1: "Corporate knowledge base",
        subtitle: "One place for policies, FAQ and documents — with search and AI answers citing sources.",
        problemsTitle: "Symptoms",
        problems: ["New hires take months to onboard", "Same questions repeated across teams", "Docs scattered across tools"],
        deliverablesTitle: "Outcome",
        deliverables: ["Document indexing and smart search", "AI answers with source citations", "CRM and messenger integration"],
        relatedTitle: "Related",
        related: [
          { href: "/solutions/assistant", label: "Business chatbot" },
          { href: "/ai/corporate", label: "Enterprise AI" },
        ],
      },
      assistant: {
        metaTitle: "Business chatbot and corporate assistant",
        metaDescription: "Business chatbot for support, sales and internal processes. Employee and customer assistants.",
        metaKeywords: [
          "business chatbot",
          "website chatbot",
          "corporate assistant",
          "customer support bot",
          "AI assistant for business",
        ],
        eyebrow: "Assistant",
        h1: "Business chatbot",
        subtitle: "We build assistants for support, sales and internal ops.",
        problemsTitle: "Use cases",
        problems: ["Support drowned in repetitive questions", "Website bot must push leads to CRM", "Employees need internal policy assistant"],
        deliverablesTitle: "We deliver",
        deliverables: ["Dialogs and scenarios for your brand", "Telegram, website, CRM integration", "Knowledge base and document connection"],
        relatedTitle: "Related",
        related: [
          { href: "/solutions/knowledge-base", label: "Knowledge base" },
          { href: "/services/enterprise-ai-assistant", label: "Enterprise AI assistant" },
        ],
      },
    },
  },
  sections: {
    philosophy: "Philosophy",
    whyUs: "Difference",
    problems: "Problems",
    audience: "Who we work with",
    engagement: "Engagement",
    solutions: "What we implement",
    process: "How we work",
    about: "About",
    verified: "Reviews",
    portfolio: "Case studies",
    cta: "Get in touch",
    contact: "Contact",
  },
} as const;

export default en;
