const en = {
  meta: {
    title: "Business process automation, CRM & documents for companies",
    description:
      "Bober AI Systems — process automation, CRM, document workflows and sales automation. AI where it drives ROI. Fixed scope, production delivery, team handover.",
    keywords: [
      "business process automation",
      "CRM implementation",
      "document workflow automation",
      "sales automation",
      "knowledge base",
      "business chatbot",
      "enterprise AI implementation",
      "amoCRM integration",
      "Bitrix24 integration",
    ],
  },
  nav: {
    services: "Solutions",
    packages: "Packages",
    portfolio: "Case studies",
    blog: "Blog",
    partners: "Partners",
    process: "Process",
    about: "About",
    reviews: "Reviews",
    contact: "Contact",
    write: "Request a quote",
    writeShort: "Quote",
    menuOpen: "Open menu",
    menuClose: "Close menu",
    quickContact: "Get in touch",
    call: "Call",
    telegram: "Telegram",
    servicesPage: "All solutions",
  },
  locale: {
    switchTo: "Русский",
  },
  hero: {
    location: "Moscow · Remote · Russia & CIS",
    eyebrow: "Bober AI Systems / Business transformation partner",
    titleLine1: "BUSINESS",
    titleLine2: "PROCESS AUTOMATION",
    valueProposition: "CRM · Documents · Sales · Support.",
    specialization:
      "We deploy AI only where it genuinely speeds up work and reduces costs.",
    heroImageAlt: "Business process automation and CRM integrations",
    trustItems: [
      "12+ PRODUCTION DEPLOYMENTS",
      "€25K+ TYPICAL DEAL",
      "7 YEARS IN AI",
      "NDA / ON-PREM",
    ],
    title: "Business process automation for companies",
    roles: ["Automation architect", "Production delivery"],
    nameLine: "Pavel Stasinsky · '@'pstasinski",
    focus:
      "We design and implement business automation systems. CRM, documents, sales, support — fixed scope and team handover.",
    trustLine: "★ {rating} · {reviewCount} reviews · {years} years · 12+ production deployments",
    partnersLine: "Yandex Cloud Partner · Selectel Partner Program · Cloud.ru Technology Partner",
    ctaPrimary: "Discuss your project",
    ctaSecondary: "View case studies",
    ctaTelegram: "Telegram",
    responseNote: "Response within 4 business hours · NDA available",
    legalNote: "Personal data published with the subject''s consent.",
    legalLink: "Privacy policy",
  },
  philosophy: {
    title: "We don't sell AI",
    subtitle: "We improve business operations",
    items: [
      "Sometimes that means integrating a CRM.",
      "Sometimes automating documents.",
      "Sometimes redesigning a workflow.",
      "Sometimes building an AI assistant.",
    ],
    closing:
      "We recommend the solution that delivers the highest business value—not the most fashionable technology.",
  },
  audiences: {
    title: "Who we work with",
    items: [
      {
        title: "Companies with manual processes",
        text: "Sales, documents, tickets, support — losing time and money. Need automation with measurable ROI.",
      },
      {
        title: "CRM/ERP integrators",
        text: "Bitrix24, amoCRM, 1C — we deliver automation under your contract: white-label, NDA, fixed scope.",
      },
      {
        title: "Software houses",
        text: "Subcontract automation and AI layers: APIs, integrations, documentation and handover to your team.",
      },
    ],
  },
  trust: {
    title: "Trusted for automation delivery",
    strip: [
      "12+ PRODUCTION DEPLOYMENTS",
      "€25K+ TYPICAL DEAL",
      "7 YEARS IN AI",
      "NDA / ON-PREM",
    ],
    stats: [
      { value: "12+", label: "production deployments" },
      { value: "€25k+", label: "typical enterprise deal" },
      { value: "7 years", label: "in AI & automation" },
      { value: "NDA", label: "and on-prem on request" },
    ],
    logos: ["Kaspersky", "Yandex Cloud", "Selectel", "Cloud.ru"],
    partnersAriaLabel: "Technology and cloud partners",
    partnerPrograms: {
      "yandex-cloud": "Yandex Cloud Partner",
      selectel: "Selectel Partner Program",
      cloudru: "Cloud.ru Technology Partner",
    },
  },
  packages: {
    title: "AI & Automation Advisor",
    subtitle:
      "We analyze the process → calculate ROI → choose technology → implement. Fixed scope, not hourly consulting.",
    items: [
      {
        name: "Business audit",
        price: "from €1,500",
        duration: "1–2 weeks",
        forWhom: "You need to find where processes are losing money",
        result: "Process map, loss points and automation priorities",
        includes: ["Process and data audit", "ROI calculation by scenario", "Technology recommendations"],
        tier: "audit",
        detailsHref: "/services/ai-discovery-roadmap",
      },
      {
        name: "Automation roadmap",
        price: "from €1,500",
        duration: "1–2 weeks",
        forWhom: "You have a task — need an implementation plan before procurement",
        result: "Architecture, phased plan and estimate before development starts",
        includes: ["Architecture and stack selection", "Phased implementation plan", "PoC and production estimate"],
        tier: "roadmap",
        detailsHref: "/services/ai-discovery-roadmap",
      },
      {
        name: "Implementation",
        price: "from €5,000",
        duration: "4–12 weeks",
        forWhom: "Ready to automate CRM, documents, sales or support",
        result: "Production deployment with documentation and team handover",
        includes: ["Development and integration", "Testing and deployment", "Documentation and handover"],
        featured: true,
        tier: "implementation",
        detailsHref: "/services/business-process-automation",
      },
      {
        name: "Support",
        price: "from €2,000/mo",
        duration: "ongoing",
        forWhom: "You need ongoing support and automation evolution",
        result: "Monitoring, iterations and priority support",
        includes: ["Monitoring and SLA", "Process iterations", "Priority support"],
        tier: "support",
        detailsHref: "/services/business-process-automation",
      },
    ],
    cta: "Request a quote",
    featuredLabel: "CORE ENGAGEMENT",
    detailsLabel: "Details",
  },
  services: {
    title: "Solutions by business problem",
    subtitle: "Automation, CRM, documents, sales and AI — scoped for production delivery, not pilots.",
    details: "Details",
    quote: "Request a quote",
    days: "days",
    discussCta: "Discuss implementation",
    implementationAreas: [
      {
        badge: "Processes",
        title: "Business process automation",
        description: "End-to-end process automation: audit, CRM/ERP integrations, production launch and handover.",
        items: ["Process audit and mapping", "CRM and ERP integrations", "Workflow orchestration"],
        layout: "wide",
        slug: "business-process-automation",
        href: "/automation/processes",
      },
      {
        badge: "CRM",
        title: "CRM implementation & automation",
        description: "CRM setup, pipeline automation and integrations — amoCRM, Bitrix24, 1C.",
        items: ["CRM implementation", "Pipeline automation", "Documents and sales integrations"],
        layout: "large",
        featured: true,
        slug: "business-process-automation",
        href: "/integrations/crm",
      },
      {
        badge: "Documents",
        title: "Document workflow automation",
        description: "Documents, approvals and data extraction — AI added only when it pays off.",
        items: ["Approval workflows", "Document processing", "CRM and ERP links"],
        layout: "default",
        slug: "business-process-automation",
        href: "/automation/documents",
      },
      {
        badge: "Sales",
        title: "Sales & proposal automation",
        description: "Commercial proposals from CRM and templates. PDF in minutes, not hours.",
        items: ["Sales automation", "CRM for sales teams", "Proposal generation"],
        layout: "default",
        slug: "sales-ai-agent",
        href: "/automation/sales",
      },
      {
        badge: "Knowledge",
        title: "Corporate knowledge base",
        description: "Knowledge base, employee chatbot and document search.",
        items: ["Knowledge base setup", "Business chatbot", "Document search"],
        layout: "compact",
        slug: "enterprise-ai-assistant",
        href: "/solutions/knowledge-base",
      },
      {
        badge: "Enterprise AI",
        title: "AI implementation",
        description: "LLM, agents, private environment — when process and data are ready, not for demos.",
        items: ["Corporate AI", "Private LLM", "AI assistants"],
        layout: "compact",
        slug: "enterprise-ai-assistant",
        href: "/ai/corporate",
      },
    ],
    items: [
      {
        slug: "business-process-automation",
        title: "Business process automation",
        description: "Audit, CRM/ERP integrations, workflow — task chains without manual routine.",
        salesNotes: "from €4,000",
        deliveryDays: 21,
      },
      {
        slug: "sales-ai-agent",
        title: "Sales department automation",
        description: "Leads, CRM, proposals, follow-up — PDF in minutes, not hours.",
        salesNotes: "from €4,000",
        deliveryDays: 14,
      },
      {
        slug: "business-process-automation",
        title: "Document workflow automation",
        description: "OCR, approvals, classification, workflow — AI only where it adds advantage.",
        salesNotes: "from €4,000",
        deliveryDays: 21,
      },
      {
        slug: "enterprise-ai-assistant",
        title: "Corporate knowledge base",
        description: "Knowledge base, document search, chatbot for employees and clients.",
        salesNotes: "from €5,000",
        deliveryDays: 28,
      },
      {
        slug: "ai-discovery-roadmap",
        title: "AI & Automation Advisor",
        description: "We analyze the process, calculate ROI, choose technology, implement.",
        salesNotes: "from €1,500",
        deliveryDays: 10,
      },
      {
        slug: "enterprise-ai-assistant",
        title: "AI implementation",
        description: "LLM, agents, CRM integrations — production, not a ChatGPT pilot.",
        salesNotes: "from €5,000",
        deliveryDays: 28,
      },
    ],
  },
  process: {
    title: "How we work",
    subtitle: "From problem to ROI — technology is chosen last, not first",
    steps: [
      { title: "Business audit", text: "We analyze processes, find loss points, calculate ROI." },
      { title: "Automation roadmap", text: "Architecture, technology selection, phased plan and estimate." },
      { title: "Implementation", text: "Development, integrations, production deployment on your environment." },
      { title: "Support", text: "Monitoring, iterations, SLA support." },
    ],
  },
  security: {
    title: "Security & compliance",
    items: [
      "GDPR-oriented data processing — DPA, lawful basis, retention policies",
      "EU and regional hosting options with isolated deployment",
      "Access controls, audit logs, and encryption at rest and in transit",
      "Secrets management and client-controlled model providers",
      "NDA before work starts — standard for enterprise engagements",
      "152-FZ support for Russian deployments",
      "GDPR-oriented architecture for EU deployments",
    ],
  },
  partners: {
    badge: "For integrators & software houses",
    title: "White-label AI for partners",
    subtitle: "You face the client — we deliver architecture, code, and deployment",
    description:
      "Subcontract and revenue share. NDA, fixed timelines, documentation for your team. Bitrix24, amoCRM, 1C, REST API.",
    steps: [
      { title: "You bring the client", text: "Or we work as your AI subcontractor under NDA." },
      { title: "Fixed scope", text: "Estimate, timeline, deliverables — no surprises for your PM." },
      { title: "Handover", text: "Code, docs, training — your brand, our expertise." },
    ],
    models: [
      "Subcontract: fixed price per scope",
      "Revenue share: 10% of client advance payment",
      "White-label: no Bober AI mention in client-facing docs",
    ],
    cta: "Become a technology partner",
    commission: "'10%'",
    commissionNote: "of client advance on referral",
  },
  about: {
    title: "About the company",
    tagline: "Business transformation partner · Bober AI Systems",
    imageAlt: "Team implementing business process automation",
    text: "Bober AI Systems is a team that designs and implements automation for companies. CRM, documents, sales, support — with fixed scope, milestones, and handover to your team.\n\nNot a freelance marketplace or a ChatGPT demo. We work as an external automation department: audit → roadmap → production → support. Case studies: Kaspersky, ELIA Suite, proposal and document automation.\n\nWe respond within 4 business hours. NDA before kickoff.",
    approach: "Approach",
    approachValue: "Process and ROI first, technology second. Fixed scope, milestone delivery, measurable outcomes.",
    schedule: "Schedule",
    scheduleValue: "Mon–Fri, response within 4h",
    collaboration: "Engagement",
    collaborationSummary: "Fixed estimate or retainer. Milestone-based delivery.",
    collaborationDetail: "Contract, NDA, IP assignment — standard for B2B.",
    skillsTitle: "Expertise",
    skills: [
      "Business process automation",
      "CRM: amoCRM, Bitrix24, 1C",
      "Document workflow & OCR",
      "Sales & proposal automation",
      "Corporate knowledge bases",
      "LLM, RAG, AI assistants",
      "Security & data governance",
      "Yandex Cloud · Selectel",
    ],
    cta: "Request a quote",
  },
  reviews: {
    title: "Client reviews",
    subtitle: "28 ratings on Yandex · verified reviews on AI, ML, and production delivery",
    yandexTitle: "Yandex",
    yandexMeta: "Rating {rating} · {count} reviews",
    avitoTitle: "Avito reviews",
    avitoMeta: "{count} published reviews",
  },
  media: {
    label: "MEDIA / EXPERTISE",
    title: "Media & speaking",
    subtitle:
      "I comment on AI adoption for business and industry media, take part in interviews, and expert discussions.",
    videoCta: "Watch interview",
    articleCta: "Read article",
    videoAriaLabel: "Open {publisher} interview on YouTube",
    articleAriaLabel: "Open {publisher} article: {title}",
    footerNote: "Available for expert commentary, interviews, and industry speaking engagements.",
    footerLinkLabel: "Suggest a topic",
  },
  portfolio: {
    title: "Case studies",
    subtitle: "Problem → process → ROI → technology",
    details: "View case study",
    priceFrom: "from",
    problemLabel: "Challenge",
    solutionLabel: "Solution",
    resultLabel: "Outcome",
    categoriesLabel: "Categories",
  },
  cta: {
    title: "Have a project? Get an estimate.",
    subtitle: "Describe your scope. Preliminary plan and estimate within 24 hours.",
    primary: "Request a quote",
    secondary: "Message on Telegram",
  },
  contact: {
    title: "Contact",
    subtitle: "Name, contact, and your task — we respond within 4 hours.",
    email: "Email",
    telegram: "Telegram",
    phone: "Phone",
    linkedin: "LinkedIn",
    github: "GitHub",
    modalClose: "Close",
    fabLabel: "Request a quote",
  },
  form: {
    name: "Name",
    contact: "Email or phone",
    contactPlaceholder: "you@company.com or +1…",
    message: "Task",
    messagePlaceholder: "Briefly: what you need to automate or implement",
    optional: "(optional)",
    consentCombined: "I have read the",
    policyLink: "privacy policy",
    consentAnd: "and give",
    consentLink: "consent to personal data processing",
    submit: "Get in touch",
    submitting: "Sending…",
    successTitle: "Sent",
    success: "We received your request and will reply shortly.",
    errorConsent: "Please confirm consent to personal data processing",
    errorSend: "Failed to send request",
    errorGeneric: "Send error",
  },
  footer: {
    legalName: "IE Pavel Stasinsky",
    privacy: "Privacy policy",
    consent: "Data processing consent",
    profiles: "Profiles & verification",
    presence: {
      linkedin: "LinkedIn",
      github: "GitHub",
      yandexReviews: "Yandex reviews",
      yandexCloud: "Yandex Cloud partner catalog",
      selectel: "Selectel Partner Program",
      cloudru: "Cloud.ru partner directory",
    },
  },
  banner: {
    badge: "For integrators",
    title: "White-label AI for partners",
    text: "Refer clients — {percent} of advance. Subcontract under NDA.",
    cta: "Become a partner",
    more: "Learn more",
    close: "Close",
  },
  common: {
    siteName: "Bober AI Systems",
    online: "Online",
    readMore: "Learn more",
  },
  servicePage: {
    back: "← All solutions",
    includes: "What''s included",
    deliverables: [
      "Task audit and scope agreement",
      "Development and configuration",
      "Testing and production deployment",
      "Documentation and team handover",
    ],
    timeline: "Timeline",
    days: "days",
    quote: "Request a quote",
    telegram: "Message on Telegram",
    formTitle: "Or leave a request",
    listTitle: "Business problem solutions",
  },
  partnersPage: {
    title: "Partners",
    subtitle: "White-label AI for integrators and software houses",
  },
  landing: {
    common: {
      backHome: "← Home",
      cta: "Request a quote",
      telegram: "Telegram",
      service: "Package",
      serviceDetails: "Service details",
      timeline: "Timeline",
      days: "days",
      contact: "Contact",
      formTitle: "Discuss your project",
      formSubtitle: "Describe the process or integration — we reply within 4 business hours.",
    },
    pages: {
      processes: {
        metaTitle: "Business process automation — implementation",
        metaDescription: "Business process automation for companies: audit, CRM/ERP integrations, production launch and team handover.",
        metaKeywords: [
          "business process automation",
          "workflow automation",
          "process automation company",
          "BPM implementation",
          "business automation system",
          "process optimization",
        ],
        eyebrow: "Automation",
        h1: "Business process automation for companies",
        subtitle: "We design and implement process automation — sales, documents, approvals, CRM. AI only where it removes manual work.",
        problemsTitle: "When you need this",
        problems: ["Teams duplicate the same steps across CRM, email and spreadsheets", "Processes depend on specific people", "You need implementation, not another SaaS shelfware"],
        deliverablesTitle: "Deliverables",
        deliverables: ["Process map and automation points", "CRM, ERP, messenger and document integrations", "Production launch, monitoring and handover"],
        relatedTitle: "Related",
        related: [
          { href: "/automation/documents", label: "Document automation" },
          { href: "/integrations/crm", label: "CRM implementation" },
          { href: "/ai/corporate", label: "Enterprise AI" },
        ],
      },
      crm: {
        metaTitle: "CRM implementation and automation",
        metaDescription: "CRM implementation, setup and pipeline automation. amoCRM, Bitrix24, ERP integrations.",
        metaKeywords: [
          "CRM implementation",
          "CRM for business",
          "CRM automation",
          "CRM setup",
          "sales pipeline automation",
          "CRM integration",
        ],
        eyebrow: "CRM",
        h1: "CRM implementation & automation",
        subtitle: "CRM is not just software selection — we configure processes, integrations and automation for your sales or ops team.",
        problemsTitle: "Typical problems",
        problems: ["CRM exists but managers work around it", "No link between CRM, documents and ERP", "You need pipeline automation, not manual reporting"],
        deliverablesTitle: "What we do",
        deliverables: ["Pipeline audit and CRM setup", "amoCRM / Bitrix24 / 1C integrations", "Task, notification and document automation"],
        relatedTitle: "Integrations",
        related: [
          { href: "/integrations/amocrm", label: "amoCRM integration" },
          { href: "/integrations/bitrix24", label: "Bitrix24" },
          { href: "/automation/sales", label: "Sales automation" },
        ],
      },
      corporate: {
        metaTitle: "Enterprise AI implementation",
        metaDescription: "Enterprise AI implementation: production systems, integrations, compliance-ready delivery.",
        metaKeywords: [
          "enterprise AI implementation",
          "AI for business",
          "corporate AI",
          "AI automation",
          "production AI deployment",
          "private AI environment",
        ],
        eyebrow: "Enterprise AI",
        h1: "Enterprise AI implementation — production, not demos",
        subtitle: "AI where you have processes and data: documents, CRM, support, knowledge base.",
        problemsTitle: "When it makes sense",
        problems: ["ChatGPT pilot does not scale to a department", "You need corporate AI inside your perimeter", "You need implementation with team handover"],
        deliverablesTitle: "Outcome",
        deliverables: ["Architecture and model selection", "CRM, document and messenger integrations", "MLOps, monitoring, documentation"],
        relatedTitle: "Related",
        related: [
          { href: "/solutions/knowledge-base", label: "Knowledge base" },
          { href: "/automation/processes", label: "Process automation" },
          { href: "/services/private-llm-gigachat", label: "Private LLM" },
        ],
      },
      documents: {
        metaTitle: "Document workflow automation",
        metaDescription: "Document workflow automation: approvals, data extraction, CRM and ERP integrations.",
        metaKeywords: [
          "document workflow automation",
          "document processing automation",
          "approval workflow",
          "electronic document management",
          "contract approval automation",
        ],
        eyebrow: "Documents",
        h1: "Document workflow automation",
        subtitle: "Less manual document handling: intake, approvals, client responses. AI for documents is optional.",
        problemsTitle: "Pain points",
        problems: ["Documents lost between email, CRM and file shares", "Contract approval takes days", "Templates live in scattered files"],
        deliverablesTitle: "We implement",
        deliverables: ["Approval chains and notifications", "Data extraction from PDF/scans", "CRM, ERP and knowledge base links"],
        relatedTitle: "Related",
        related: [
          { href: "/automation/processes", label: "Process automation" },
          { href: "/solutions/knowledge-base", label: "Knowledge base" },
        ],
      },
      sales: {
        metaTitle: "Sales and proposal automation",
        metaDescription: "Sales automation, CRM for sales teams, proposal generation from templates.",
        metaKeywords: [
          "sales automation",
          "proposal automation",
          "CRM for sales",
          "commercial proposal generation",
          "sales workflow automation",
        ],
        eyebrow: "Sales",
        h1: "Sales & proposal automation",
        subtitle: "Faster deal cycle: CRM data → proposal → PDF → client. No copy-paste between spreadsheets.",
        problemsTitle: "Sales team problems",
        problems: ["Managers spend hours on proposals instead of calls", "Templates and price lists are out of sync", "CRM is not linked to documents"],
        deliverablesTitle: "Outcome",
        deliverables: ["Proposal generation from CRM", "Auto-filled pricing and terms", "amoCRM / Bitrix24 integration"],
        relatedTitle: "Related",
        related: [
          { href: "/integrations/crm", label: "CRM implementation" },
          { href: "/services/sales-ai-agent", label: "Sales AI agent" },
        ],
      },
      amocrm: {
        metaTitle: "amoCRM integration and automation",
        metaDescription: "amoCRM integration with website, ERP, messengers and documents.",
        metaKeywords: [
          "amoCRM integration",
          "amoCRM automation",
          "amoCRM API",
          "amoCRM setup",
          "website amoCRM integration",
        ],
        eyebrow: "amoCRM",
        h1: "amoCRM integration for your workflow",
        subtitle: "Connect amoCRM to what you already use: website, Telegram, ERP, document generation.",
        problemsTitle: "Typical request",
        problems: ["Website leads do not reach CRM", "Managers chat outside CRM", "You need website-to-amoCRM integration"],
        deliverablesTitle: "Scope",
        deliverables: ["Webhooks, API, two-way sync", "Stage and task automation", "Proposal and document links"],
        relatedTitle: "Related",
        related: [
          { href: "/integrations/crm", label: "CRM overview" },
          { href: "/integrations/bitrix24", label: "Bitrix24" },
        ],
      },
      bitrix24: {
        metaTitle: "Bitrix24 integration and automation",
        metaDescription: "Bitrix24 integration and automation: CRM, tasks, documents, AI layer.",
        metaKeywords: [
          "Bitrix24 integration",
          "Bitrix24 implementation",
          "Bitrix24 automation",
          "Bitrix24 CRM setup",
          "Bitrix24 integrator",
        ],
        eyebrow: "Bitrix24",
        h1: "Bitrix24: integration & automation",
        subtitle: "We automate CRM workflows and add AI on top.",
        problemsTitle: "When clients come",
        problems: ["Bitrix24 is installed but processes are manual", "Need ERP, telephony and document integrations", "Looking for a Bitrix24 integrator"],
        deliverablesTitle: "Deliverables",
        deliverables: ["CRM and robot setup", "REST API integrations", "AI assistant on Bitrix24"],
        relatedTitle: "Related",
        related: [
          { href: "/integrations/crm", label: "CRM overview" },
          { href: "/integrations/amocrm", label: "amoCRM" },
        ],
      },
      knowledgeBase: {
        metaTitle: "Corporate knowledge base setup",
        metaDescription: "Knowledge base setup: document search, FAQ, AI assistant for employees.",
        metaKeywords: [
          "knowledge base setup",
          "corporate knowledge base",
          "AI knowledge base",
          "internal wiki",
          "document search for employees",
        ],
        eyebrow: "Knowledge base",
        h1: "Corporate knowledge base",
        subtitle: "One place for policies, FAQ and documents — with search and AI answers citing sources.",
        problemsTitle: "Symptoms",
        problems: ["New hires take months to onboard", "Same questions repeated across teams", "Docs scattered across tools"],
        deliverablesTitle: "Outcome",
        deliverables: ["Document indexing and smart search", "AI answers with source citations", "CRM and messenger integration"],
        relatedTitle: "Related",
        related: [
          { href: "/solutions/assistant", label: "Business chatbot" },
          { href: "/ai/corporate", label: "Enterprise AI" },
        ],
      },
      assistant: {
        metaTitle: "Business chatbot and corporate assistant",
        metaDescription: "Business chatbot for support, sales and internal processes. Employee and customer assistants.",
        metaKeywords: [
          "business chatbot",
          "website chatbot",
          "corporate assistant",
          "customer support bot",
          "AI assistant for business",
        ],
        eyebrow: "Assistant",
        h1: "Business chatbot",
        subtitle: "We build assistants for support, sales and internal ops.",
        problemsTitle: "Use cases",
        problems: ["Support drowned in repetitive questions", "Website bot must push leads to CRM", "Employees need internal policy assistant"],
        deliverablesTitle: "We deliver",
        deliverables: ["Dialogs and scenarios for your brand", "Telegram, website, CRM integration", "Knowledge base and document connection"],
        relatedTitle: "Related",
        related: [
          { href: "/solutions/knowledge-base", label: "Knowledge base" },
          { href: "/services/enterprise-ai-assistant", label: "Enterprise AI assistant" },
        ],
      },
    },
  },
  sections: {
    philosophy: "Philosophy",
    audience: "01 · Audience",
    engagement: "02 · Engagement",
    solutions: "03 · Solutions",
    process: "04 · Process",
    about: "05 · About",
    verified: "Verified",
    portfolio: "Portfolio",
    cta: "Engagement",
    contact: "Contact",
  },
} as const;

export default en;
