const ru = {
  meta: {
    title: "Внедрение AI и автоматизация для бизнеса",
    description:
      "Bober AI Systems — внедрение AI и автоматизация для бизнеса. Внешний AI-отдел для software house, интеграторов CRM/ERP и компаний с бюджетом от 500 000 ₽.",
    keywords: [
      "внедрение AI",
      "разработка AI под ключ",
      "корпоративный ИИ",
      "RAG системы",
      "AI-агенты для бизнеса",
      "интеграция LLM",
      "MLOps",
      "автоматизация бизнеса",
      "GigaChat внедрение",
      "Yandex Cloud",
      "Selectel",
      "AI консалтинг Москва",
      "внедрение искусственного интеллекта",
    ],
  },
  nav: {
    services: "Решения",
    packages: "Пакеты",
    portfolio: "Кейсы",
    blog: "Блог",
    partners: "Партнёрам",
    process: "Процесс",
    about: "О нас",
    reviews: "Отзывы",
    contact: "Контакт",
    write: "Оставить заявку",
    servicesPage: "Все решения",
  },
  locale: {
    switchTo: "English",
  },
  hero: {
    location: "Москва · Онлайн · Россия и СНГ",
    title: "Внедрение AI и автоматизация для бизнеса",
    roles: ["AI-архитектор", "Внедрение в production"],
    nameLine: "Павел Стасиньский · '@'pstasinski",
    focus:
      "Внешний AI-отдел для software house, интеграторов CRM/ERP и компаний с бюджетом от 500 000 ₽. RAG, агенты, интеграции, MLOps. Фиксированная смета, этапы, передача команде.",
    trustLine: "★ {rating} · {reviewCount} отзывов · {years} лет · 12+ production внедрений",
    partnersLine: "Партнёр Yandex Cloud · Selectel · Cloud.ru",
    ctaPrimary: "Обсудить проект",
    ctaSecondary: "Посмотреть кейсы",
    ctaTelegram: "Telegram",
    responseNote: "Ответ в течение 4 рабочих часов · NDA по запросу",
    legalNote: "Персональные данные размещены с согласия субъекта.",
    legalLink: "Политика обработки ПДн",
  },
  audiences: {
    title: "Для кого",
    items: [
      {
        title: "Software house",
        text: "White-label AI-модули в ваш продукт: RAG, агенты, API. Документация и handover для вашей команды.",
      },
      {
        title: "Интеграторы CRM/ERP",
        text: "Bitrix24, amoCRM, 1С — внедряем AI-слой без конфликта с вашим контрактом с клиентом.",
      },
      {
        title: "Компании с бюджетом",
        text: "Автоматизация продаж, документов, поддержки. On-prem, облако, 152-ФЗ.",
      },
    ],
  },
  trust: {
    title: "Нам доверяют production-проекты",
    stats: [
      { value: "12+", label: "внедрений в production" },
      { value: "300k+", label: "средний чек enterprise" },
      { value: "7 лет", label: "в AI и автоматизации" },
      { value: "NDA", label: "и on-prem по запросу" },
    ],
    logos: ["Kaspersky", "Yandex Cloud", "Selectel", "Cloud.ru"],
  },
  packages: {
    title: "Пакеты для компаний",
    subtitle: "Не почасовая консультация — фиксированный scope и deliverables",
    items: [
      {
        name: "Диагностика",
        price: "от 150 000 ₽",
        duration: "1–2 недели",
        forWhom: "Нужен план, архитектура и оценка до закупки",
        result: "Понятный roadmap и смета до старта разработки",
        includes: ["Консультация и бриф", "Аудит процессов и данных", "Архитектура решения", "Оценка бюджета и сроков"],
        detailsHref: "/services/ai-discovery-roadmap",
      },
      {
        name: "Быстрый запуск",
        price: "от 400 000 ₽",
        duration: "от 14 дней",
        forWhom: "Нужен AI-бот, ассистент или автоматизация одного процесса",
        result: "Рабочее решение в production с базовой интеграцией",
        includes: ["AI-бот или Telegram-ассистент", "Автоматизация одного процесса", "Базовая интеграция n8n / CRM", "Тестирование и передача"],
        detailsHref: "/services/sales-ai-agent",
      },
      {
        name: "Внедрение под ключ",
        price: "от 500 000 ₽",
        duration: "4–12 недель",
        forWhom: "Готовы внедрять RAG, агентов или несколько интеграций",
        result: "Production deployment с документацией и handover",
        includes: ["AI-агент или CRM-интеграция", "Автоматизация документов", "Несколько интеграций", "Документация и передача команде"],
        featured: true,
        detailsHref: "/services/enterprise-ai-assistant",
      },
      {
        name: "Корпоративное решение",
        price: "от 500 000 ₽",
        duration: "от 4 недель · retainer от 200 000 ₽/мес",
        forWhom: "Нужен приватный контур, RAG и сопровождение",
        result: "Изолированная инфраструктура с ролями, мониторингом и SLA",
        includes: ["Приватный контур и on-prem", "RAG и локальная LLM", "Роли, доступы и guardrails", "Мониторинг и сопровождение"],
        detailsHref: "/services/private-llm-gigachat",
      },
    ],
    cta: "Запросить смету",
    featuredLabel: "Чаще выбирают",
    detailsLabel: "Подробнее",
  },
  services: {
    title: "Что внедряем",
    subtitle: "Production-ready решения с передачей команде — не демо и не прототипы",
    details: "Подробнее",
    quote: "Запросить смету",
    days: "дн.",
    discussCta: "Обсудить внедрение",
    implementationAreas: [
      {
        badge: "AI-агенты",
        title: "AI-ассистенты для бизнеса",
        description: "Обрабатывают обращения, готовят документы, обновляют CRM и помогают сотрудникам выполнять рутинные задачи.",
        items: ["Telegram и мессенджеры", "Claude, OpenAI, YandexGPT", "CRM и внутренние API"],
        accent: "green",
        featured: true,
        wide: true,
        slug: "enterprise-ai-assistant",
      },
      {
        badge: "Продажи",
        title: "AI-агент для продаж и КП",
        description: "Сбор коммерческих предложений из CRM и шаблонов. PDF за минуты, не за часы.",
        items: ["amoCRM и Bitrix24", "Шаблоны КП и прайсы", "Автоматическая генерация PDF"],
        accent: "blue",
        slug: "sales-ai-agent",
      },
      {
        badge: "Автоматизация",
        title: "Автоматизация процессов с AI",
        description: "Документы, отчёты, CRM, уведомления — цепочки задач без ручной рутины.",
        items: ["Обработка документов", "Отчёты и уведомления", "n8n и внутренние API"],
        accent: "orange",
        slug: "business-process-automation",
      },
      {
        badge: "Приватный LLM",
        title: "Локальные и приватные LLM",
        description: "GigaChat, on-prem и изолированное облако — без утечки данных во внешние сервисы.",
        items: ["GigaChat и YandexGPT", "On-prem и 152-ФЗ", "Guardrails и мониторинг"],
        accent: "violet",
        slug: "private-llm-gigachat",
      },
      {
        badge: "Discovery",
        title: "AI Discovery & Roadmap",
        description: "Аудит, архитектура, выбор моделей, оценка сроков и бюджета до старта разработки.",
        items: ["Аудит задачи и данных", "Архитектура и стек", "Roadmap и смета"],
        accent: "cyan",
        slug: "ai-discovery-roadmap",
      },
      {
        badge: "RAG · CRM",
        title: "База знаний и интеграции",
        description: "Корпоративная RAG-система и связка с amoCRM, Bitrix24, 1С и Telegram.",
        items: ["Корпоративная база знаний", "amoCRM, Bitrix24, 1С", "REST API и webhooks"],
        accent: "cyan",
        wide: true,
      },
    ],
    items: [
      {
        slug: "enterprise-ai-assistant",
        title: "Корпоративный AI-ассистент",
        description: "Диалоги, сценарии, интеграции с CRM и мессенджерами. LLM + оркестрация под ваши процессы.",
        salesNotes: "от 500 000 ₽",
        deliveryDays: 28,
      },
      {
        slug: "ai-discovery-roadmap",
        title: "AI Discovery & Roadmap",
        description: "Аудит, архитектура, выбор моделей, оценка сроков и бюджета до старта разработки.",
        salesNotes: "от 150 000 ₽",
        deliveryDays: 10,
      },
      {
        slug: "private-llm-gigachat",
        title: "Приватный LLM-контур",
        description: "GigaChat, on-prem и изолированное облако — без утечки данных во внешние сервисы.",
        salesNotes: "от 500 000 ₽",
        deliveryDays: 28,
      },
      {
        slug: "business-process-automation",
        title: "Автоматизация процессов с AI",
        description: "Документы, отчёты, CRM, уведомления — цепочки задач без ручной рутины.",
        salesNotes: "от 400 000 ₽",
        deliveryDays: 21,
      },
      {
        slug: "sales-ai-agent",
        title: "AI-агент для продаж и КП",
        description: "Сбор коммерческих предложений из CRM и шаблонов. PDF за минуты, не за часы.",
        salesNotes: "от 400 000 ₽",
        deliveryDays: 14,
      },
    ],
  },
  process: {
    title: "Как мы работаем",
    subtitle: "Прозрачные этапы — вы знаете, что получите на каждом шаге",
    steps: [
      { title: "Discovery", text: "Бриф, аудит данных и процессов, уточнение scope и рисков." },
      { title: "Architecture", text: "Стек, схема интеграций, смета и план по этапам." },
      { title: "PoC", text: "Проверяем гипотезу на реальных данных до полного бюджета." },
      { title: "Production", text: "Разработка, деплой, мониторинг, тесты на вашей среде." },
      { title: "Handover", text: "Документация, обучение команды, поддержка по SLA." },
    ],
  },
  security: {
    title: "Безопасность и compliance",
    items: [
      "On-prem и изолированное облако — данные не уходят в публичные API",
      "152-ФЗ: политика ПДн, согласие, договор обработки",
      "NDA до начала работ — стандарт для enterprise",
      "Kubernetes, мониторинг, логирование — production-grade инфраструктура",
    ],
  },
  partners: {
    badge: "Для integrators & software house",
    title: "White-label AI для интеграторов",
    subtitle: "Вы — лицо для клиента, мы — архитектура, код и внедрение",
    description:
      "Subcontract и revenue share. NDA, фиксированные сроки, документация для вашей команды. Bitrix24, amoCRM, 1С, REST API.",
    steps: [
      { title: "Вы приводите клиента", text: "Или мы работаем как ваш AI-подрядчик под NDA." },
      { title: "Фиксируем scope", text: "Смета, сроки, deliverables — без сюрпризов для вашего PM." },
      { title: "Handover", text: "Код, docs, обучение — ваш бренд, наша экспертиза." },
    ],
    models: [
      "Subcontract: фиксированная цена за scope",
      "Revenue share: 10% от аванса клиента",
      "White-label: без упоминания Bober AI в документах клиента",
    ],
    cta: "Стать технологическим партнёром",
    commission: "'10%'",
    commissionNote: "от аванса клиента при referral",
  },
  about: {
    title: "О нас",
    text: "Bober AI Systems — внедрение AI в production для компаний с бюджетом. Не фриланс-маркетплейс: фиксированные сметы, этапы, договор, передача решения вашей команде.\n\nСпециализация: RAG, AI-агенты, интеграции CRM/ERP, MLOps на Kubernetes. Партнёр Yandex Cloud, Selectel, Cloud.ru. Кейсы: Kaspersky, enterprise-автоматизация продаж и документов.\n\nОтвет на заявку — в течение 4 рабочих часов. NDA — до старта.",
    education: "Образование",
    educationValue: "University of Warsaw — Physics and Neuroscience",
    schedule: "График",
    scheduleValue: "Пн–Пт, ответ в течение 4 ч",
    collaboration: "Сотрудничество",
    collaborationSummary: "Фиксированная смета или retainer. Поэтапная сдача с актами.",
    collaborationDetail: "Договор, NDA, IP assignment — стандарт для B2B.",
    skillsTitle: "Экспертиза",
    skills: [
      "RAG и корпоративная база знаний",
      "AI-агенты для бизнеса",
      "MLOps и Kubernetes",
      "LLM-интеграции",
      "CRM: amoCRM, Bitrix24, 1С",
      "On-prem и 152-ФЗ",
      "YandexGPT и GigaChat",
      "Yandex Cloud · Selectel",
    ],
    cta: "Оставить заявку",
  },
  reviews: {
    yandexTitle: "Yandex",
    yandexMeta: "Рейтинг {rating} · {count} оценок",
    avitoTitle: "Отзывы Авито",
    avitoMeta: "{count} опубликованных отзывов",
    kworkTitle: "Отзывы Kwork",
  },
  portfolio: {
    title: "Кейсы",
    subtitle: "Enterprise-проекты с измеримым результатом",
    details: "Подробнее о проекте",
    priceFrom: "от",
    problemLabel: "Задача",
    solutionLabel: "Решение",
    resultLabel: "Результат",
    categoriesLabel: "Направления",
  },
  cta: {
    title: "Есть задача — есть смета",
    subtitle: "Опишите проект. Предварительный план и оценка — в течение 24 часов.",
    primary: "Оставить заявку",
    secondary: "Написать в Telegram",
  },
  contact: {
    title: "Связаться",
    subtitle: "Опишите задачу, бюджет и сроки — ответим в течение 4 рабочих часов.",
    email: "Email",
    telegram: "Telegram",
    phone: "Телефон",
  },
  form: {
    name: "Имя",
    contact: "Email или телефон",
    company: "Компания",
    companyPlaceholder: "ООО Пример",
    budget: "Бюджет проекта",
    budgetPlaceholder: "Выберите диапазон",
    budgetOptions: ["до 500 000 ₽", "500 000 – 1 500 000 ₽", "1 500 000 – 5 000 000 ₽", "5 000 000+ ₽"],
    companyType: "Тип компании",
    companyTypePlaceholder: "Выберите тип",
    companyTypeOptions: ["Конечный клиент", "Software house", "Интегратор CRM/ERP", "Агентство", "Другое"],
    service: "Задача / услуга",
    servicePlaceholder: "Например: RAG по базе знаний",
    message: "Сообщение",
    policy: "Я ознакомлен(а) с",
    policyLink: "политикой обработки персональных данных",
    consent: "Я даю",
    consentLink: "согласие на обработку персональных данных",
    submit: "Отправить заявку",
    submitting: "Отправляем…",
    success: "Заявка отправлена. Свяжемся в ближайшее время.",
    errorPolicy: "Необходимо подтвердить ознакомление с политикой обработки персональных данных",
    errorConsent: "Необходимо дать согласие на обработку персональных данных",
    errorSend: "Не удалось отправить заявку",
    errorGeneric: "Ошибка отправки",
  },
  footer: {
    legalName: "ИП Стасиньски Павел Кшиштоф",
    privacy: "Политика обработки ПДн",
    consent: "Согласие на обработку ПДн",
    marketplaces: "Также на маркетплейсах",
  },
  banner: {
    badge: "Для integrators",
    title: "White-label AI для партнёров",
    text: "Приводите клиентов — {percent} от аванса. Subcontract под NDA.",
    cta: "Стать партнёром",
    more: "Подробнее",
    close: "Закрыть",
  },
  common: {
    siteName: "Bober AI Systems",
    online: "Онлайн",
    readMore: "Подробнее",
  },
  servicePage: {
    back: "← Все решения",
    includes: "Что входит",
    deliverables: [
      "Аудит задачи и согласование ТЗ",
      "Разработка и настройка решения",
      "Тестирование и production-деплой",
      "Документация и передача команде",
    ],
    timeline: "Срок",
    days: "дн.",
    quote: "Запросить смету",
    telegram: "Написать в Telegram",
    formTitle: "Или оставьте заявку",
    listTitle: "Enterprise AI solutions",
  },
  partnersPage: {
    title: "Партнёрам",
    subtitle: "White-label AI для integrators и software house",
  },
} as const;

export default ru;
