const ru = {
  meta: {
    title: "Внедрение AI и автоматизация для бизнеса",
    description:
      "Bober AI Systems — внедрение AI и автоматизация для бизнеса. Внешний AI-отдел для software house, интеграторов CRM/ERP и компаний с бюджетом от 500 000 ₽.",
    keywords: [
      "внедрение AI",
      "разработка AI под ключ",
      "корпоративный ИИ",
      "RAG системы",
      "AI-агенты для бизнеса",
      "интеграция LLM",
      "MLOps",
      "автоматизация бизнеса",
      "GigaChat внедрение",
      "Yandex Cloud",
      "Selectel",
      "AI консалтинг Москва",
      "внедрение искусственного интеллекта",
    ],
  },
  nav: {
    services: "Решения",
    packages: "Пакеты",
    portfolio: "Кейсы",
    blog: "Блог",
    partners: "Партнёрам",
    process: "Процесс",
    about: "О нас",
    reviews: "Отзывы",
    contact: "Контакт",
    write: "Оставить заявку",
    writeShort: "Заявка",
    menuOpen: "Открыть меню",
    menuClose: "Закрыть меню",
    quickContact: "Связаться с нами",
    call: "Позвонить",
    telegram: "Telegram",
    servicesPage: "Все решения",
  },
  locale: {
    switchTo: "English",
  },
  hero: {
    location: "Москва · Онлайн · Россия и СНГ",
    eyebrow: "Bober AI Systems / Корпоративный ИИ",
    titleLine1: "ПАРТНЁР ПО",
    titleLine2: "ВНЕДРЕНИЮ КОРПОРАТИВНОГО ИИ",
    valueProposition:
      "Проектируем и внедряем AI-системы для компаний, которым недостаточно демонстрационного прототипа.",
    specialization: "RAG · AI-агенты · приватный LLM · MLOps · интеграции",
    portraitRole: "AI-архитектор · промышленное внедрение",
    trustItems: [
      "12+ ВНЕДРЕНИЙ В PRODUCTION",
      "ОТ 300 000 ₽ СРЕДНИЙ ЧЕК",
      "7 ЛЕТ В ИИ",
      "NDA / ON-PREM",
    ],
    title: "Внедрение AI и автоматизация для бизнеса",
    roles: ["AI-архитектор", "Промышленное внедрение"],
    nameLine: "Павел Стасиньский · '@'pstasinski",
    focus:
      "Внешний AI-отдел для software house, интеграторов CRM/ERP и компаний с бюджетом от 500 000 ₽. RAG, агенты, интеграции, MLOps. Фиксированная смета, этапы, передача команде.",
    trustLine: "★ {rating} · {reviewCount} отзывов · {years} лет · 12+ внедрений в production",
    partnersLine: "Партнёр Yandex Cloud · Selectel · Cloud.ru",
    ctaPrimary: "Обсудить проект",
    ctaSecondary: "Посмотреть кейсы",
    ctaTelegram: "Telegram",
    responseNote: "Ответ в течение 4 рабочих часов · NDA по запросу",
    legalNote: "Персональные данные размещены с согласия субъекта.",
    legalLink: "Политика обработки ПДн",
  },
  audiences: {
    title: "Для кого",
    items: [
      {
        title: "Студия разработки ПО",
        text: "White-label AI-модули в ваш продукт: RAG, агенты, API. Документация и передача команде.",
      },
      {
        title: "Интеграторы CRM/ERP",
        text: "Bitrix24, amoCRM, 1С — внедряем AI-слой без конфликта с вашим контрактом с клиентом.",
      },
      {
        title: "Компании с бюджетом",
        text: "Автоматизация продаж, документов, поддержки. On-prem, облако, 152-ФЗ.",
      },
    ],
  },
  trust: {
    title: "Нам доверяют промышленные проекты",
    strip: [
      "12+ ВНЕДРЕНИЙ В PRODUCTION",
      "ОТ 300 000 ₽ СРЕДНИЙ ЧЕК",
      "7 ЛЕТ В ИИ",
      "NDA / ON-PREM",
    ],
    stats: [
      { value: "12+", label: "внедрений в production" },
      { value: "300k+", label: "средний чек enterprise" },
      { value: "7 лет", label: "в ИИ и автоматизации" },
      { value: "NDA", label: "и on-prem по запросу" },
    ],
    logos: ["Kaspersky", "Yandex Cloud", "Selectel", "Cloud.ru"],
  },
  packages: {
    title: "Пакеты для компаний",
    subtitle: "Не почасовая консультация — фиксированный объём работ и результаты",
    items: [
      {
        name: "Исследование и архитектура",
        price: "от 150 000 ₽",
        duration: "1–2 недели",
        forWhom: "Нужен план, архитектура и оценка до закупки",
        result: "Понятная дорожная карта и смета до старта разработки",
        includes: ["Аудит задачи и данных", "Архитектура и выбор стека", "Дорожная карта и смета PoC/Production"],
        tier: "discovery",
        detailsHref: "/services/ai-discovery-roadmap",
      },
      {
        name: "Внедрение",
        price: "от 500 000 ₽",
        duration: "4–12 недель",
        forWhom: "Готовы внедрять RAG, агентов или интеграции",
        result: "Промышленный запуск с документацией и передачей команде",
        includes: ["Разработка и интеграция", "Тестирование и деплой", "Документация и передача команде"],
        featured: true,
        tier: "implementation",
        detailsHref: "/services/enterprise-ai-assistant",
      },
      {
        name: "AI-сопровождение",
        price: "от 200 000 ₽/мес",
        duration: "постоянно",
        forWhom: "Нужен внешний AI-отдел на поддержке",
        result: "MLOps, итерации и приоритетная поддержка",
        includes: ["MLOps и мониторинг", "Итерации моделей", "Приоритетная поддержка"],
        tier: "retainer",
        detailsHref: "/services/private-llm-gigachat",
      },
    ],
    cta: "Запросить смету",
    featuredLabel: "ОСНОВНОЙ ФОРМАТ",
    detailsLabel: "Подробнее",
  },
  services: {
    title: "Что внедряем",
    subtitle: "Готовые к production решения с передачей команде — не демо и не прототипы",
    details: "Подробнее",
    quote: "Запросить смету",
    days: "дн.",
    discussCta: "Обсудить внедрение",
    implementationAreas: [
      {
        badge: "Корпоративный ИИ",
        title: "Корпоративный AI-ассистент",
        description: "Диалоги, сценарии, интеграции с CRM и мессенджерами. LLM + оркестрация под ваши процессы.",
        items: ["Telegram и мессенджеры", "Claude, OpenAI, YandexGPT", "CRM и внутренние API"],
        layout: "wide",
        slug: "enterprise-ai-assistant",
      },
      {
        badge: "Приватный LLM",
        title: "Приватный LLM-контур",
        description: "GigaChat, on-prem и изолированное облако — без утечки данных во внешние сервисы.",
        items: ["GigaChat и YandexGPT", "On-prem и 152-ФЗ", "Guardrails и мониторинг"],
        layout: "large",
        featured: true,
        slug: "private-llm-gigachat",
      },
      {
        badge: "Исследование",
        title: "AI Discovery и дорожная карта",
        description: "Аудит, архитектура, выбор моделей, оценка сроков и бюджета до старта разработки.",
        items: ["Аудит задачи и данных", "Архитектура и стек", "Дорожная карта и смета"],
        layout: "compact",
        slug: "ai-discovery-roadmap",
      },
      {
        badge: "Автоматизация",
        title: "Автоматизация процессов с AI",
        description: "Документы, отчёты, CRM, уведомления — цепочки задач без ручной рутины.",
        items: ["Обработка документов", "Отчёты и уведомления", "n8n и внутренние API"],
        layout: "default",
        slug: "business-process-automation",
      },
      {
        badge: "ИИ для продаж",
        title: "AI-агент для продаж и КП",
        description: "Сбор коммерческих предложений из CRM и шаблонов. PDF за минуты, не за часы.",
        items: ["amoCRM и Bitrix24", "Шаблоны КП и прайсы", "Автоматическая генерация PDF"],
        layout: "default",
        slug: "sales-ai-agent",
      },
    ],
    items: [
      {
        slug: "enterprise-ai-assistant",
        title: "Корпоративный AI-ассистент",
        description: "Диалоги, сценарии, интеграции с CRM и мессенджерами. LLM + оркестрация под ваши процессы.",
        salesNotes: "от 500 000 ₽",
        deliveryDays: 28,
      },
      {
        slug: "ai-discovery-roadmap",
        title: "AI Discovery и дорожная карта",
        description: "Аудит, архитектура, выбор моделей, оценка сроков и бюджета до старта разработки.",
        salesNotes: "от 150 000 ₽",
        deliveryDays: 10,
      },
      {
        slug: "private-llm-gigachat",
        title: "Приватный LLM-контур",
        description: "GigaChat, on-prem и изолированное облако — без утечки данных во внешние сервисы.",
        salesNotes: "от 500 000 ₽",
        deliveryDays: 28,
      },
      {
        slug: "business-process-automation",
        title: "Автоматизация процессов с AI",
        description: "Документы, отчёты, CRM, уведомления — цепочки задач без ручной рутины.",
        salesNotes: "от 400 000 ₽",
        deliveryDays: 21,
      },
      {
        slug: "sales-ai-agent",
        title: "AI-агент для продаж и КП",
        description: "Сбор коммерческих предложений из CRM и шаблонов. PDF за минуты, не за часы.",
        salesNotes: "от 400 000 ₽",
        deliveryDays: 14,
      },
    ],
  },
  process: {
    title: "Как мы работаем",
    subtitle: "Прозрачные этапы — вы знаете, что получите на каждом шаге",
    steps: [
      { title: "Исследование", text: "Бриф, аудит данных и процессов, уточнение объёма работ и рисков." },
      { title: "Архитектура", text: "Стек, схема интеграций, смета и план по этапам." },
      { title: "PoC", text: "Проверяем гипотезу на реальных данных до полного бюджета." },
      { title: "Production", text: "Разработка, деплой, мониторинг, тесты на вашей среде." },
      { title: "Передача", text: "Документация, обучение команды, поддержка по SLA." },
    ],
  },
  security: {
    title: "Безопасность и соответствие требованиям",
    items: [
      "On-prem и изолированное облако — данные не уходят в публичные API",
      "152-ФЗ: политика ПДн, согласие, договор обработки",
      "NDA до начала работ — стандарт для enterprise",
      "Kubernetes, мониторинг, логирование — инфраструктура production-уровня",
    ],
  },
  partners: {
    badge: "Для интеграторов и студий разработки",
    title: "White-label AI для интеграторов",
    subtitle: "Вы — лицо для клиента, мы — архитектура, код и внедрение",
    description:
      "Субподряд и revenue share. NDA, фиксированные сроки, документация для вашей команды. Bitrix24, amoCRM, 1С, REST API.",
    steps: [
      { title: "Вы приводите клиента", text: "Или мы работаем как ваш AI-подрядчик под NDA." },
      { title: "Фиксируем объём работ", text: "Смета, сроки, результаты — без сюрпризов для вашего PM." },
      { title: "Передача", text: "Код, документация, обучение — ваш бренд, наша экспертиза." },
    ],
    models: [
      "Субподряд: фиксированная цена за объём работ",
      "Revenue share: 10% от аванса клиента",
      "White-label: без упоминания Bober AI в документах клиента",
    ],
    cta: "Стать технологическим партнёром",
    commission: "'10%'",
    commissionNote: "от аванса клиента при рекомендации",
  },
  about: {
    title: "О нас",
    text: "Bober AI Systems — внедрение AI в production для компаний с бюджетом. Не фриланс-маркетплейс: фиксированные сметы, этапы, договор, передача решения вашей команде.\n\nСпециализация: RAG, AI-агенты, интеграции CRM/ERP, MLOps на Kubernetes. Партнёр Yandex Cloud, Selectel, Cloud.ru. Кейсы: Kaspersky, корпоративная автоматизация продаж и документов.\n\nОтвет на заявку — в течение 4 рабочих часов. NDA — до старта.",
    education: "Образование",
    educationValue: "Варшавский университет — физика и нейронаука",
    schedule: "График",
    scheduleValue: "Пн–Пт, ответ в течение 4 ч",
    collaboration: "Сотрудничество",
    collaborationSummary: "Фиксированная смета или сопровождение. Поэтапная сдача с актами.",
    collaborationDetail: "Договор, NDA, передача прав на код — стандарт для B2B.",
    skillsTitle: "Экспертиза",
    skills: [
      "RAG и корпоративная база знаний",
      "AI-агенты для бизнеса",
      "MLOps и Kubernetes",
      "LLM-интеграции",
      "CRM: amoCRM, Bitrix24, 1С",
      "On-prem и 152-ФЗ",
      "YandexGPT и GigaChat",
      "Yandex Cloud · Selectel",
    ],
    cta: "Оставить заявку",
  },
  reviews: {
    title: "Отзывы клиентов",
    subtitle: "28 оценок на Яндексе · проверенные отзывы по ИИ, ML и промышленным внедрениям",
    yandexTitle: "Yandex",
    yandexMeta: "Рейтинг {rating} · {count} оценок",
    avitoTitle: "Отзывы Авито",
    avitoMeta: "{count} опубликованных отзывов",
  },
  media: {
    label: "СМИ / ЭКСПЕРТИЗА",
    title: "СМИ и выступления",
    subtitle:
      "Комментирую внедрение искусственного интеллекта для деловых и отраслевых СМИ, участвую в интервью и экспертных дискуссиях.",
    videoCta: "Смотреть интервью",
    articleCta: "Читать материал",
    videoAriaLabel: "Открыть интервью {publisher} на YouTube",
    articleAriaLabel: "Открыть материал {publisher}: {title}",
    footerNote: "Открыт для экспертных комментариев, интервью и отраслевых выступлений.",
    footerLinkLabel: "Предложить тему",
  },
  portfolio: {
    title: "Кейсы",
    subtitle: "Корпоративные проекты с измеримым результатом",
    details: "Подробнее о проекте",
    priceFrom: "от",
    problemLabel: "Задача",
    solutionLabel: "Решение",
    resultLabel: "Результат",
    categoriesLabel: "Направления",
  },
  cta: {
    title: "Есть задача — есть смета",
    subtitle: "Опишите проект. Предварительный план и оценка — в течение 24 часов.",
    primary: "Оставить заявку",
    secondary: "Написать в Telegram",
  },
  contact: {
    title: "Связаться",
    subtitle: "Имя, контакт и задача — ответим в течение 4 часов.",
    email: "Эл. почта",
    telegram: "Telegram",
    phone: "Телефон",
    modalClose: "Закрыть",
    fabLabel: "Оставить заявку",
  },
  form: {
    name: "Имя",
    contact: "Эл. почта или телефон",
    contactPlaceholder: "you@company.ru или +7…",
    message: "Задача",
    messagePlaceholder: "Кратко: что нужно автоматизировать или внедрить",
    optional: "(необязательно)",
    consentCombined: "Я ознакомлен(а) с",
    policyLink: "политикой обработки персональных данных",
    consentAnd: "и даю",
    consentLink: "согласие на обработку персональных данных",
    submit: "Связаться",
    submitting: "Отправляем…",
    successTitle: "Отправлено",
    success: "Получили заявку — ответим в ближайшее время.",
    errorConsent: "Подтвердите согласие на обработку персональных данных",
    errorSend: "Не удалось отправить заявку",
    errorGeneric: "Ошибка отправки",
  },
  footer: {
    legalName: "ИП Стасиньски Павел Кшиштоф",
    privacy: "Политика обработки ПДн",
    consent: "Согласие на обработку ПДн",
    marketplaces: "Также на маркетплейсах",
  },
  banner: {
    badge: "Для интеграторов",
    title: "White-label AI для партнёров",
    text: "Приводите клиентов — {percent} от аванса. Субподряд под NDA.",
    cta: "Стать партнёром",
    more: "Подробнее",
    close: "Закрыть",
  },
  common: {
    siteName: "Bober AI Systems",
    online: "Онлайн",
    readMore: "Подробнее",
  },
  servicePage: {
    back: "← Все решения",
    includes: "Что входит",
    deliverables: [
      "Аудит задачи и согласование ТЗ",
      "Разработка и настройка решения",
      "Тестирование и production-деплой",
      "Документация и передача команде",
    ],
    timeline: "Срок",
    days: "дн.",
    quote: "Запросить смету",
    telegram: "Написать в Telegram",
    formTitle: "Или оставьте заявку",
    listTitle: "Корпоративные AI-решения",
  },
  partnersPage: {
    title: "Партнёрам",
    subtitle: "White-label AI для интеграторов и студий разработки",
  },
  sections: {
    audience: "01 · Аудитория",
    engagement: "02 · Форматы работы",
    solutions: "03 · Решения",
    process: "04 · Процесс",
    about: "05 · О компании",
    verified: "Проверенные отзывы",
    portfolio: "Портфолио",
    cta: "Сотрудничество",
    contact: "Контакт",
  },
} as const;

export default ru;
