const ru = {
  meta: {
    title: "Автоматизация бизнес-процессов, CRM и документов для компаний",
    description:
      "Bober AI Systems — внедрение автоматизации процессов, CRM, документооборота и продаж. AI там, где даёт ROI. Фиксированная смета, production, передача команде. От 300 000 ₽.",
    keywords: [
      "автоматизация бизнес процессов",
      "автоматизация документооборота",
      "внедрение crm",
      "crm автоматизация",
      "amocrm интеграция",
      "bitrix24 интеграция",
      "автоматизация продаж",
      "создание базы знаний",
      "чат бот для бизнеса",
      "внедрение ии в бизнес",
      "ai автоматизация",
      "корпоративный ии",
      "автоматизация коммерческих предложений",
    ],
  },
  nav: {
    services: "Решения",
    packages: "Пакеты",
    portfolio: "Кейсы",
    blog: "Блог",
    partners: "Партнёрам",
    process: "Процесс",
    about: "О нас",
    reviews: "Отзывы",
    contact: "Контакт",
    write: "Оставить заявку",
    writeShort: "Заявка",
    menuOpen: "Открыть меню",
    menuClose: "Закрыть меню",
    quickContact: "Связаться с нами",
    call: "Позвонить",
    telegram: "Telegram",
    servicesPage: "Все решения",
  },
  locale: {
    switchTo: "English",
  },
  hero: {
    location: "Москва · Онлайн · Россия и СНГ",
    eyebrow: "Bober AI Systems / Партнёр по трансформации бизнеса",
    titleLine1: "АВТОМАТИЗАЦИЯ",
    titleLine2: "БИЗНЕС-ПРОЦЕССОВ",
    valueProposition: "CRM · Документы · Продажи · Поддержка.",
    specialization:
      "Внедряем AI только там, где он действительно ускоряет работу и снижает расходы.",
    portraitRole: "Архитектор автоматизации · production",
    trustItems: [
      "12+ ВНЕДРЕНИЙ В PRODUCTION",
      "ОТ 300 000 ₽ СРЕДНИЙ ЧЕК",
      "7 ЛЕТ В ИИ",
      "NDA / ON-PREM",
    ],
    title: "Автоматизация бизнес-процессов для компаний",
    roles: ["Архитектор автоматизации", "Production-внедрение"],
    nameLine: "Павел Стасиньский · '@'pstasinski",
    focus:
      "Проектируем и внедряем системы автоматизации бизнеса. CRM, документы, продажи, поддержка — с фиксированной сметой и передачей команде.",
    trustLine: "★ {rating} · {reviewCount} отзывов · {years} лет · 12+ внедрений в production",
    partnersLine: "Партнёр Yandex Cloud · Партнёрская программа Selectel · Технологический партнёр Cloud.ru",
    ctaPrimary: "Обсудить проект",
    ctaSecondary: "Посмотреть кейсы",
    ctaTelegram: "Telegram",
    responseNote: "Ответ в течение 4 рабочих часов · NDA по запросу",
    legalNote: "Персональные данные размещены с согласия субъекта.",
    legalLink: "Политика обработки ПДн",
  },
  philosophy: {
    title: "Мы не продаём AI",
    subtitle: "Мы улучшаем бизнес-операции",
    items: [
      "Иногда это интеграция CRM.",
      "Иногда автоматизация документов.",
      "Иногда перестройка workflow.",
      "Иногда — AI-ассистент.",
    ],
    closing:
      "Рекомендуем решение с максимальной бизнес-ценностью — а не самую модную технологию.",
  },
  audiences: {
    title: "Для кого",
    items: [
      {
        title: "Компании с ручными процессами",
        text: "Продажи, документы, заявки, поддержка — теряют время и деньги. Нужна автоматизация с измеримым ROI.",
      },
      {
        title: "Интеграторы CRM/ERP",
        text: "Bitrix24, amoCRM, 1С — внедряем автоматизацию под ваш контракт: white-label, NDA, фиксированная смета.",
      },
      {
        title: "Студии разработки",
        text: "Субподряд на автоматизацию и AI-слой: API, интеграции, документация и передача вашей команде.",
      },
    ],
  },
  trust: {
    title: "Нам доверяют внедрение автоматизации",
    strip: [
      "12+ ВНЕДРЕНИЙ В PRODUCTION",
      "ОТ 300 000 ₽ СРЕДНИЙ ЧЕК",
      "7 ЛЕТ В ИИ",
      "NDA / ON-PREM",
    ],
    stats: [
      { value: "12+", label: "внедрений в production" },
      { value: "300k+", label: "средний чек enterprise" },
      { value: "7 лет", label: "в ИИ и автоматизации" },
      { value: "NDA", label: "и on-prem по запросу" },
    ],
    logos: ["Kaspersky", "Yandex Cloud", "Selectel", "Cloud.ru"],
    partnersAriaLabel: "Технологические и облачные партнёры",
    partnerPrograms: {
      "yandex-cloud": "Партнёр Yandex Cloud",
      selectel: "Партнёрская программа Selectel",
      cloudru: "Технологический партнёр Cloud.ru",
    },
  },
  packages: {
    title: "AI & Automation Advisor",
    subtitle:
      "Анализируем процесс → считаем ROI → выбираем технологию → внедряем. Фиксированный объём работ, не почасовая консультация.",
    items: [
      {
        name: "Бизнес-аудит",
        price: "от 150 000 ₽",
        duration: "1–2 недели",
        forWhom: "Нужно найти, где процессы теряют деньги",
        result: "Карта процессов, точки потерь и приоритеты автоматизации",
        includes: ["Аудит процессов и данных", "Расчёт ROI по сценариям", "Рекомендации по технологиям"],
        tier: "audit",
        detailsHref: "/services/ai-discovery-roadmap",
      },
      {
        name: "Дорожная карта автоматизации",
        price: "от 150 000 ₽",
        duration: "1–2 недели",
        forWhom: "Есть задача — нужен план внедрения до закупки",
        result: "Архитектура, поэтапный план и смета до старта разработки",
        includes: ["Архитектура и выбор стека", "Поэтапный план внедрения", "Смета PoC и production"],
        tier: "roadmap",
        detailsHref: "/services/ai-discovery-roadmap",
      },
      {
        name: "Внедрение",
        price: "от 500 000 ₽",
        duration: "4–12 недель",
        forWhom: "Готовы автоматизировать CRM, документы, продажи или поддержку",
        result: "Production-запуск с документацией и передачей команде",
        includes: ["Разработка и интеграция", "Тестирование и деплой", "Документация и передача команде"],
        featured: true,
        tier: "implementation",
        detailsHref: "/services/business-process-automation",
      },
      {
        name: "Сопровождение",
        price: "от 200 000 ₽/мес",
        duration: "постоянно",
        forWhom: "Нужна поддержка и развитие автоматизации",
        result: "Мониторинг, итерации и приоритетная поддержка",
        includes: ["Мониторинг и SLA", "Итерации процессов", "Приоритетная поддержка"],
        tier: "support",
        detailsHref: "/services/business-process-automation",
      },
    ],
    cta: "Запросить смету",
    featuredLabel: "ОСНОВНОЙ ФОРМАТ",
    detailsLabel: "Подробнее",
  },
  services: {
    title: "Решения под реальный спрос",
    subtitle: "Страницы собраны по Wordstat: от задач бизнеса — процессы, CRM, документы — а не от технологий ради технологий",
    details: "Подробнее",
    quote: "Запросить смету",
    days: "дн.",
    discussCta: "Обсудить внедрение",
    implementationAreas: [
      {
        badge: "5269 запросов/мес",
        title: "Автоматизация бизнес-процессов",
        description: "Внедрение автоматизации процессов для компаний: от аудита до production и передачи команде.",
        items: ["Автоматизация бизнес процессов внедрение", "Система автоматизации процессов", "Интеграции с CRM и 1С"],
        layout: "wide",
        slug: "business-process-automation",
        href: "/automation/processes",
      },
      {
        badge: "1376 запросов/мес",
        title: "Внедрение и автоматизация CRM",
        description: "CRM для бизнеса, настройка, автоматизация воронки и интеграции — amoCRM, Bitrix24, 1С.",
        items: ["Внедрение CRM системы", "CRM автоматизация", "Интеграция с документами и продажами"],
        layout: "large",
        featured: true,
        slug: "business-process-automation",
        href: "/integrations/crm",
      },
      {
        badge: "2069 запросов/мес",
        title: "Автоматизация документооборота",
        description: "Документы, согласования, извлечение данных — без ручной рутины. AI подключаем по необходимости.",
        items: ["Система автоматизации документооборота", "Обработка документов компании", "ИИ для документов"],
        layout: "default",
        slug: "business-process-automation",
        href: "/automation/documents",
      },
      {
        badge: "1863 запросов/мес",
        title: "Автоматизация продаж и КП",
        description: "Коммерческие предложения из CRM и шаблонов. PDF за минуты, не за часы.",
        items: ["Автоматизация продаж", "CRM для отдела продаж", "Генерация КП"],
        layout: "default",
        slug: "sales-ai-agent",
        href: "/automation/sales",
      },
      {
        badge: "860 запросов/мес",
        title: "Корпоративная база знаний",
        description: "База знаний, чат-бот для сотрудников и клиентов, поиск по документам.",
        items: ["Создание базы знаний", "Чат-бот для бизнеса", "Поиск по документам"],
        layout: "compact",
        slug: "enterprise-ai-assistant",
        href: "/solutions/knowledge-base",
      },
      {
        badge: "6254 запросов/мес",
        title: "Внедрение AI",
        description: "LLM, агенты, приватный контур — когда процесс и данные готовы, а не ради демо.",
        items: ["Корпоративный ИИ", "Приватный LLM", "AI-ассистенты"],
        layout: "compact",
        slug: "enterprise-ai-assistant",
        href: "/ai/corporate",
      },
    ],
    items: [
      {
        slug: "business-process-automation",
        title: "Автоматизация бизнес-процессов",
        description: "Аудит, интеграции CRM/1С, workflow — цепочки задач без ручной рутины.",
        salesNotes: "от 400 000 ₽",
        deliveryDays: 21,
      },
      {
        slug: "sales-ai-agent",
        title: "Автоматизация отдела продаж",
        description: "Лиды, CRM, коммерческие предложения, follow-up — PDF за минуты, не за часы.",
        salesNotes: "от 400 000 ₽",
        deliveryDays: 14,
      },
      {
        slug: "business-process-automation",
        title: "Автоматизация документооборота",
        description: "OCR, согласования, классификация, workflow — AI только там, где даёт преимущество.",
        salesNotes: "от 400 000 ₽",
        deliveryDays: 21,
      },
      {
        slug: "enterprise-ai-assistant",
        title: "Корпоративная база знаний",
        description: "База знаний, поиск по документам, чат-бот для сотрудников и клиентов.",
        salesNotes: "от 500 000 ₽",
        deliveryDays: 28,
      },
      {
        slug: "ai-discovery-roadmap",
        title: "AI & Automation Advisor",
        description: "Анализируем процесс, считаем ROI, выбираем технологию, внедряем.",
        salesNotes: "от 150 000 ₽",
        deliveryDays: 10,
      },
      {
        slug: "enterprise-ai-assistant",
        title: "Внедрение AI",
        description: "LLM, агенты, интеграции с CRM — production, не пилот на ChatGPT.",
        salesNotes: "от 500 000 ₽",
        deliveryDays: 28,
      },
    ],
  },
  process: {
    title: "Как мы работаем",
    subtitle: "От проблемы к ROI — технология выбирается в конце, не в начале",
    steps: [
      { title: "Бизнес-аудит", text: "Анализируем процессы, находим точки потерь, считаем ROI." },
      { title: "Дорожная карта", text: "Архитектура, выбор технологий, поэтапный план и смета." },
      { title: "Внедрение", text: "Разработка, интеграции, production-деплой на вашей среде." },
      { title: "Сопровождение", text: "Мониторинг, итерации, поддержка по SLA." },
    ],
  },
  security: {
    title: "Безопасность и соответствие требованиям",
    items: [
      "On-prem и изолированное облако — данные не уходят в публичные API",
      "152-ФЗ: политика ПДн, согласие, договор обработки",
      "NDA до начала работ — стандарт для enterprise",
      "Kubernetes, мониторинг, логирование — инфраструктура production-уровня",
    ],
  },
  partners: {
    badge: "Для интеграторов и студий разработки",
    title: "White-label AI для интеграторов",
    subtitle: "Вы — лицо для клиента, мы — архитектура, код и внедрение",
    description:
      "Субподряд и revenue share. NDA, фиксированные сроки, документация для вашей команды. Bitrix24, amoCRM, 1С, REST API.",
    steps: [
      { title: "Вы приводите клиента", text: "Или мы работаем как ваш AI-подрядчик под NDA." },
      { title: "Фиксируем объём работ", text: "Смета, сроки, результаты — без сюрпризов для вашего PM." },
      { title: "Передача", text: "Код, документация, обучение — ваш бренд, наша экспертиза." },
    ],
    models: [
      "Субподряд: фиксированная цена за объём работ",
      "Revenue share: 10% от аванса клиента",
      "White-label: без упоминания Bober AI в документах клиента",
    ],
    cta: "Стать технологическим партнёром",
    commission: "'10%'",
    commissionNote: "от аванса клиента при рекомендации",
  },
  about: {
    title: "О нас",
    founderName: "Павел Стасиньский",
    founderRole: "Архитектор автоматизации · основатель Bober AI Systems",
    linkedinLabel: "LinkedIn профиль",
    githubLabel: "GitHub",
    text: "Bober AI Systems — партнёр по трансформации бизнеса. Проектируем и внедряем системы автоматизации: CRM, документы, продажи, поддержка. Используем AI только там, где он действительно приносит ROI.\n\nНе фриланс-маркетплейс: фиксированные сметы, этапы, договор, передача решения вашей команде. Кейсы: Kaspersky, ELIA Suite, автоматизация КП и документов.\n\nОтвет на заявку — в течение 4 рабочих часов. NDA — до старта.",
    education: "Образование",
    educationValue: "Варшавский университет — физика и нейронаука",
    schedule: "График",
    scheduleValue: "Пн–Пт, ответ в течение 4 ч",
    collaboration: "Сотрудничество",
    collaborationSummary: "Фиксированная смета или сопровождение. Поэтапная сдача с актами.",
    collaborationDetail: "Договор, NDA, передача прав на код — стандарт для B2B.",
    skillsTitle: "Экспертиза",
    skills: [
      "Автоматизация бизнес-процессов",
      "CRM: amoCRM, Bitrix24, 1С",
      "Документооборот и OCR",
      "Автоматизация продаж и КП",
      "Корпоративная база знаний",
      "LLM, RAG, AI-ассистенты",
      "On-prem и 152-ФЗ",
      "Yandex Cloud · Selectel",
    ],
    cta: "Оставить заявку",
  },
  reviews: {
    title: "Отзывы клиентов",
    subtitle: "28 оценок на Яндексе · проверенные отзывы по ИИ, ML и промышленным внедрениям",
    yandexTitle: "Yandex",
    yandexMeta: "Рейтинг {rating} · {count} оценок",
  },
  media: {
    label: "СМИ / ЭКСПЕРТИЗА",
    title: "СМИ и выступления",
    subtitle:
      "Комментирую внедрение искусственного интеллекта для деловых и отраслевых СМИ, участвую в интервью и экспертных дискуссиях.",
    videoCta: "Смотреть интервью",
    articleCta: "Читать материал",
    videoAriaLabel: "Открыть интервью {publisher} на YouTube",
    articleAriaLabel: "Открыть материал {publisher}: {title}",
    footerNote: "Открыт для экспертных комментариев, интервью и отраслевых выступлений.",
    footerLinkLabel: "Предложить тему",
  },
  portfolio: {
    title: "Кейсы",
    subtitle: "Проблема → процесс → ROI → технология",
    details: "Подробнее о проекте",
    priceFrom: "от",
    problemLabel: "Задача",
    solutionLabel: "Решение",
    resultLabel: "Результат",
    categoriesLabel: "Направления",
  },
  cta: {
    title: "Есть задача — есть смета",
    subtitle: "Опишите проект. Предварительный план и оценка — в течение 24 часов.",
    primary: "Оставить заявку",
    secondary: "Написать в Telegram",
  },
  contact: {
    title: "Связаться",
    subtitle: "Имя, контакт и задача — ответим в течение 4 часов.",
    email: "Эл. почта",
    telegram: "Telegram",
    phone: "Телефон",
    linkedin: "LinkedIn",
    github: "GitHub",
    modalClose: "Закрыть",
    fabLabel: "Оставить заявку",
  },
  form: {
    name: "Имя",
    contact: "Эл. почта или телефон",
    contactPlaceholder: "you@company.ru или +7…",
    message: "Задача",
    messagePlaceholder: "Кратко: что нужно автоматизировать или внедрить",
    optional: "(необязательно)",
    consentCombined: "Я ознакомлен(а) с",
    policyLink: "политикой обработки персональных данных",
    consentAnd: "и даю",
    consentLink: "согласие на обработку персональных данных",
    submit: "Связаться",
    submitting: "Отправляем…",
    successTitle: "Отправлено",
    success: "Получили заявку — ответим в ближайшее время.",
    errorConsent: "Подтвердите согласие на обработку персональных данных",
    errorSend: "Не удалось отправить заявку",
    errorGeneric: "Ошибка отправки",
  },
  footer: {
    legalName: "ИП Стасиньски Павел Кшиштоф",
    privacy: "Политика обработки ПДн",
    consent: "Согласие на обработку ПДн",
    profiles: "Профили и верификация",
    presence: {
      linkedin: "LinkedIn",
      github: "GitHub",
      yandexReviews: "Отзывы на Яндексе",
      yandexCloud: "Каталог партнёров Yandex Cloud",
      selectel: "Партнёрская программа Selectel",
      cloudru: "Каталог партнёров Cloud.ru",
    },
  },
  banner: {
    badge: "Для интеграторов",
    title: "White-label AI для партнёров",
    text: "Приводите клиентов — {percent} от аванса. Субподряд под NDA.",
    cta: "Стать партнёром",
    more: "Подробнее",
    close: "Закрыть",
  },
  common: {
    siteName: "Bober AI Systems",
    online: "Онлайн",
    readMore: "Подробнее",
  },
  servicePage: {
    back: "← Все решения",
    includes: "Что входит",
    deliverables: [
      "Аудит задачи и согласование ТЗ",
      "Разработка и настройка решения",
      "Тестирование и production-деплой",
      "Документация и передача команде",
    ],
    timeline: "Срок",
    days: "дн.",
    quote: "Запросить смету",
    telegram: "Написать в Telegram",
    formTitle: "Или оставьте заявку",
    listTitle: "Решения по задачам бизнеса",
  },
  partnersPage: {
    title: "Партнёрам",
    subtitle: "White-label AI для интеграторов и студий разработки",
  },
  demand: {
    title: "Страницы под спрос Wordstat",
    subtitle: "P1/P2 — популярные и похожие запросы с коммерческим intent",
    volumeLabel: "показов/мес",
    intentLabels: {
      commercial_high: "Коммерческий · высокий",
      commercial_medium: "Коммерческий · средний",
    },
    items: [
      { href: "/automation/processes", title: "Автоматизация бизнес-процессов", volume: "5269", intent: "commercial_medium", priority: "P1" },
      { href: "/integrations/crm", title: "Внедрение CRM", volume: "1376", intent: "commercial_high", priority: "P1" },
      { href: "/ai/corporate", title: "Внедрение ИИ в бизнес", volume: "6254", intent: "commercial_high", priority: "P1" },
      { href: "/automation/documents", title: "Автоматизация документооборота", volume: "2069", intent: "commercial_medium", priority: "P2" },
      { href: "/automation/sales", title: "Автоматизация продаж", volume: "1863", intent: "commercial_medium", priority: "P2" },
      { href: "/integrations/amocrm", title: "amoCRM интеграция", volume: "692", intent: "commercial_medium", priority: "P2" },
      { href: "/integrations/bitrix24", title: "Bitrix24 интеграция", volume: "173", intent: "commercial_medium", priority: "P2" },
      { href: "/solutions/knowledge-base", title: "Создание базы знаний", volume: "860", intent: "commercial_medium", priority: "P2" },
      { href: "/solutions/assistant", title: "Чат-бот для бизнеса", volume: "899", intent: "commercial_medium", priority: "P2" },
    ],
  },
  landing: {
    common: {
      backHome: "← На главную",
      cta: "Запросить смету",
      telegram: "Telegram",
      priority: "Приоритет SEO",
      service: "Пакет",
      serviceDetails: "Подробнее об услуге",
      timeline: "Срок",
      days: "дн.",
      contact: "Контакт",
      formTitle: "Обсудить задачу",
      formSubtitle: "Опишите процесс или интеграцию — вернёмся с планом и оценкой в течение 4 часов.",
    },
    pages: {
      processes: {
        metaTitle: "Автоматизация бизнес-процессов — внедрение под ключ",
        metaDescription:
          "Внедрение автоматизации бизнес-процессов для компаний: аудит, интеграции CRM/1С, production и передача команде. От 400 000 ₽.",
        metaKeywords: ["автоматизация бизнес процессов", "автоматизация бизнес процессов внедрение", "система автоматизации бизнес процессов"],
        eyebrow: "Автоматизация · P1",
        h1: "Автоматизация бизнес-процессов для компаний",
        subtitle:
          "Проектируем и внедряем автоматизацию процессов — продажи, документы, согласования, CRM. AI подключаем там, где он сокращает ручной труд, а не ради buzzword.",
        volumeLabel: "Wordstat · популярные",
        volumeValue: "5269",
        intentLabel: "Intent",
        intentValue: "Коммерческий · средний/высокий",
        problemsTitle: "Когда это нужно",
        problems: [
          "Сотрудники дублируют одни и те же шаги в CRM, почте и таблицах",
          "Процессы завязаны на конкретных людей — масштабирование буксует",
          "Нужна автоматизация бизнес процессов внедрение, а не «ещё один SaaS»",
        ],
        deliverablesTitle: "Что получите",
        deliverables: [
          "Карта процессов и точки автоматизации",
          "Интеграции CRM, 1С, мессенджеры, документы",
          "Production-запуск, мониторинг и передача команде",
        ],
        keywordsTitle: "Популярные и похожие запросы",
        keywords: ["автоматизация бизнес процессов компания", "система автоматизации бизнес процессов", "технологии автоматизации бизнес процессов", "ai автоматизация"],
        relatedTitle: "Смежные направления",
        related: [
          { href: "/automation/documents", label: "Автоматизация документооборота" },
          { href: "/integrations/crm", label: "Внедрение CRM" },
          { href: "/ai/corporate", label: "Внедрение ИИ в бизнес" },
        ],
      },
      crm: {
        metaTitle: "Внедрение CRM и CRM-автоматизация для бизнеса",
        metaDescription: "Внедрение CRM системы, настройка и автоматизация воронки. amoCRM, Bitrix24, интеграция с 1С и документами.",
        metaKeywords: ["внедрение crm", "crm для бизнеса", "crm автоматизация", "внедрение crm системы"],
        eyebrow: "CRM · P1",
        h1: "Внедрение и автоматизация CRM",
        subtitle: "CRM для бизнеса — это не только выбор системы. Настраиваем процессы, интеграции и автоматизацию под ваш отдел продаж или операций.",
        volumeLabel: "Wordstat · популярные",
        volumeValue: "1376",
        intentLabel: "Intent",
        intentValue: "Коммерческий · высокий",
        problemsTitle: "Типичные задачи",
        problems: [
          "CRM внедрили, но менеджеры работают мимо системы",
          "Нет связки CRM с документами, 1С и мессенджерами",
          "Нужна crm автоматизация процессов, а не ручная отчётность",
        ],
        deliverablesTitle: "Что делаем",
        deliverables: [
          "Аудит воронки и настройка CRM",
          "Интеграции amoCRM / Bitrix24 / 1С",
          "Автоматизация задач, уведомлений и документов",
        ],
        keywordsTitle: "Популярные и похожие запросы",
        keywords: ["crm для малого бизнеса", "crm системы для бизнеса", "настройка crm", "crm для продаж"],
        relatedTitle: "Интеграции",
        related: [
          { href: "/integrations/amocrm", label: "amoCRM интеграция" },
          { href: "/integrations/bitrix24", label: "Bitrix24 интеграция" },
          { href: "/automation/sales", label: "Автоматизация продаж" },
        ],
      },
      corporate: {
        metaTitle: "Внедрение ИИ и корпоративный ИИ для бизнеса",
        metaDescription: "Внедрение искусственного интеллекта в бизнес: корпоративный ИИ, ai автоматизация, production и 152-ФЗ.",
        metaKeywords: ["внедрение ии в бизнес", "внедрение искусственного интеллекта", "корпоративный ии", "ai автоматизация"],
        eyebrow: "Корпоративный ИИ · P1",
        h1: "Внедрение ИИ в бизнес — production, не демо",
        subtitle: "Внедрение искусственного интеллекта там, где есть процесс и данные: документы, CRM, поддержка, база знаний.",
        volumeLabel: "Wordstat · популярные",
        volumeValue: "6254",
        intentLabel: "Intent",
        intentValue: "Коммерческий · высокий",
        problemsTitle: "Когда имеет смысл",
        problems: [
          "Пилот с ChatGPT не масштабируется на отдел",
          "Нужен корпоративный ии в контуре компании",
          "Требуется разработка и внедрение искусственного интеллекта с передачей команде",
        ],
        deliverablesTitle: "Результат",
        deliverables: [
          "Архитектура и выбор моделей (YandexGPT, GigaChat, Claude)",
          "Интеграции с CRM, документами, мессенджерами",
          "MLOps, мониторинг, документация",
        ],
        keywordsTitle: "Популярные и похожие запросы",
        keywords: ["нейросети для бизнеса", "ai для бизнеса", "внедрение технологий искусственного интеллекта", "ии для документов"],
        relatedTitle: "Смежные решения",
        related: [
          { href: "/solutions/knowledge-base", label: "База знаний" },
          { href: "/automation/processes", label: "Автоматизация процессов" },
          { href: "/services/private-llm-gigachat", label: "Приватный LLM" },
        ],
      },
      documents: {
        metaTitle: "Автоматизация документооборота для компаний",
        metaDescription: "Автоматизация документооборота и работы с документами: согласования, извлечение данных, интеграция с CRM и 1С.",
        metaKeywords: ["автоматизация документооборота", "система автоматизации документооборота", "автоматизация работы с документами"],
        eyebrow: "Документы · P2",
        h1: "Автоматизация документооборота",
        subtitle: "Сокращаем ручную обработку документов: входящие, согласования, ответы клиентам. ИИ для документов — опция, не обязательный вход.",
        volumeLabel: "Wordstat · популярные",
        volumeValue: "2069",
        intentLabel: "Intent",
        intentValue: "Коммерческий · средний",
        problemsTitle: "Боли",
        problems: [
          "Документы теряются между почтой, CRM и файловыми шарами",
          "Согласование договоров занимает дни",
          "Нужна автоматизация создания документов из шаблонов",
        ],
        deliverablesTitle: "Что внедряем",
        deliverables: [
          "Цепочки согласования и уведомления",
          "Извлечение данных из PDF/сканов",
          "Связка с CRM, 1С, базой знаний",
        ],
        keywordsTitle: "Популярные и похожие запросы",
        keywords: ["кадровый документооборот", "ии для документов", "обработка документов компании", "автоматизация создания документов"],
        relatedTitle: "Смежное",
        related: [
          { href: "/automation/processes", label: "Автоматизация процессов" },
          { href: "/solutions/knowledge-base", label: "База знаний" },
        ],
      },
      sales: {
        metaTitle: "Автоматизация продаж и коммерческих предложений",
        metaDescription: "Автоматизация продаж, CRM для отдела продаж, генерация КП из шаблонов и CRM.",
        metaKeywords: ["автоматизация продаж", "crm для отдела продаж", "автоматизация коммерческих предложений"],
        eyebrow: "Продажи · P2",
        h1: "Автоматизация продаж и КП",
        subtitle: "Ускоряем цикл сделки: данные из CRM → коммерческое предложение → PDF → клиент. Без копипаста между таблицами.",
        volumeLabel: "Wordstat · популярные",
        volumeValue: "1863",
        intentLabel: "Intent",
        intentValue: "Коммерческий · средний",
        problemsTitle: "Задачи отдела продаж",
        problems: [
          "Менеджеры тратят часы на КП вместо звонков",
          "Шаблоны и прайсы разъехались по файлам",
          "CRM не связана с документами и КП",
        ],
        deliverablesTitle: "Результат",
        deliverables: [
          "Генерация КП из CRM и шаблонов",
          "Автозаполнение прайсов и условий",
          "Интеграция amoCRM / Bitrix24",
        ],
        keywordsTitle: "Популярные и похожие запросы",
        keywords: ["crm для продаж", "система для коммерческих предложений", "автоматизация коммерческие предложения"],
        relatedTitle: "Смежное",
        related: [
          { href: "/integrations/crm", label: "Внедрение CRM" },
          { href: "/services/sales-ai-agent", label: "AI-агент для продаж" },
        ],
      },
      amocrm: {
        metaTitle: "amoCRM интеграция и автоматизация",
        metaDescription: "Интеграция amoCRM с сайтом, 1С, мессенджерами и документами. amoCRM API, автоматизация воронки.",
        metaKeywords: ["amocrm интеграция", "amocrm автоматизация", "настройка amocrm", "amocrm api"],
        eyebrow: "amoCRM · P2",
        h1: "amoCRM интеграция под ваш процесс",
        subtitle: "Связываем amoCRM с тем, что уже работает: сайт, Telegram, 1С, генерация документов и база знаний.",
        volumeLabel: "Wordstat · популярные",
        volumeValue: "692",
        intentLabel: "Intent",
        intentValue: "Коммерческий · средний",
        problemsTitle: "Типичный запрос",
        problems: [
          "Заявки с сайта не попадают в CRM автоматически",
          "Нужна интеграция сайта с amocrm",
          "Менеджеры ведут переписку вне CRM",
        ],
        deliverablesTitle: "Что настраиваем",
        deliverables: [
          "Вебхуки, API, двусторонняя синхронизация",
          "Автоматизация стадий и задач",
          "Связка с КП и документами",
        ],
        keywordsTitle: "Популярные и похожие запросы",
        keywords: ["настройка интеграции amocrm", "интеграция сайта с amocrm", "amocrm api", "автоматизация amocrm"],
        relatedTitle: "Смежное",
        related: [
          { href: "/integrations/crm", label: "Внедрение CRM" },
          { href: "/integrations/bitrix24", label: "Bitrix24" },
        ],
      },
      bitrix24: {
        metaTitle: "Bitrix24 внедрение, интеграция и автоматизация",
        metaDescription: "Bitrix24 интеграция и автоматизация: CRM, задачи, документы, AI-слой для вашего контура.",
        metaKeywords: ["bitrix24 интеграция", "bitrix24 внедрение", "bitrix24 автоматизация", "bitrix 24"],
        eyebrow: "Bitrix24 · P2",
        h1: "Bitrix24: интеграция и автоматизация",
        subtitle: "Bitrix 24 — частый запрос в похожих фразах. Внедряем CRM-контур и автоматизацию, подключаем AI к вашим процессам.",
        volumeLabel: "Wordstat · похожие",
        volumeValue: "3479",
        intentLabel: "Intent",
        intentValue: "Коммерческий · средний",
        problemsTitle: "Когда обращаются",
        problems: [
          "Bitrix24 стоит, но процессы не автоматизированы",
          "Нужна интеграция с 1С, телефонией, документами",
          "Ищут интегратора bitrix24 под конкретную задачу",
        ],
        deliverablesTitle: "Что делаем",
        deliverables: [
          "Настройка CRM и роботов",
          "REST API интеграции",
          "AI-ассистент поверх Bitrix24",
        ],
        keywordsTitle: "Популярные и похожие запросы",
        keywords: ["bitrix 24", "внедрение bitrix24", "автоматизация bitrix24", "интегратор bitrix24"],
        relatedTitle: "Смежное",
        related: [
          { href: "/integrations/crm", label: "CRM общее" },
          { href: "/integrations/amocrm", label: "amoCRM" },
        ],
      },
      knowledgeBase: {
        metaTitle: "Создание корпоративной базы знаний",
        metaDescription: "Создание базы знаний и корпоративной базы знаний: поиск по документам, FAQ, AI-ассистент для сотрудников.",
        metaKeywords: ["создание базы знаний", "корпоративная база знаний", "база знаний компании", "база знаний с ии"],
        eyebrow: "База знаний · P2",
        h1: "Корпоративная база знаний",
        subtitle: "Единое место для регламентов, FAQ и документов — с поиском и AI-ответами со ссылкой на источник.",
        volumeLabel: "Wordstat · популярные",
        volumeValue: "860",
        intentLabel: "Intent",
        intentValue: "Коммерческий · средний",
        problemsTitle: "Симптомы",
        problems: [
          "Новые сотрудники месяцами входят в курс дела",
          "Один и тот же вопрос задают десяткам коллег",
          "Документы разбросаны по Confluence, PDF и чатам",
        ],
        deliverablesTitle: "Что получите",
        deliverables: [
          "Индексация документов и умный поиск",
          "AI-ответы с цитатами из ваших файлов",
          "Интеграция с CRM и мессенджерами",
        ],
        keywordsTitle: "Популярные и похожие запросы",
        keywords: ["база знаний компании", "системы для создания базы знаний", "база знаний с ии", "rag система"],
        relatedTitle: "Смежное",
        related: [
          { href: "/solutions/assistant", label: "Чат-бот для бизнеса" },
          { href: "/ai/corporate", label: "Внедрение ИИ" },
        ],
      },
      assistant: {
        metaTitle: "Чат-бот для бизнеса и корпоративный ассистент",
        metaDescription: "Чат-бот для бизнеса и сайта: поддержка, продажи, база знаний. ИИ-бот для сотрудников и клиентов.",
        metaKeywords: ["чат бот для бизнеса", "чат бот для сайта", "ии бот", "корпоративный чат бот"],
        eyebrow: "Ассистент · P2",
        h1: "Чат-бот для бизнеса",
        subtitle: "Люди ищут «ии бот» и «чат-бот» — не «AI agent». Делаем ассистентов для поддержки, продаж и внутренних процессов.",
        volumeLabel: "Wordstat · популярные + похожие",
        volumeValue: "899 / 101273",
        intentLabel: "Intent",
        intentValue: "Коммерческий · средний",
        problemsTitle: "Сценарии",
        problems: [
          "Поддержка завалена однотипными вопросами",
          "Нужен бот для сайта с передачей лида в CRM",
          "Сотрудникам нужен внутренний помощник по регламентам",
        ],
        deliverablesTitle: "Что внедряем",
        deliverables: [
          "Диалоги и сценарии под ваш бренд",
          "Интеграция Telegram, сайт, CRM",
          "Подключение базы знаний и документов",
        ],
        keywordsTitle: "Популярные и похожие запросы",
        keywords: ["чат боты для бизнеса", "ии бот", "ai чат бот для сайта", "корпоративный чат бот", "бизнес ассистент"],
        relatedTitle: "Смежное",
        related: [
          { href: "/solutions/knowledge-base", label: "База знаний" },
          { href: "/services/enterprise-ai-assistant", label: "Корпоративный AI-ассистент" },
        ],
      },
    },
  },
  sections: {
    philosophy: "Философия",
    audience: "01 · Аудитория",
    engagement: "02 · Форматы работы",
    solutions: "03 · Решения",
    process: "04 · Процесс",
    about: "05 · О компании",
    verified: "Проверенные отзывы",
    portfolio: "Портфолио",
    demand: "Wordstat · спрос",
    cta: "Сотрудничество",
    contact: "Контакт",
  },
} as const;

export default ru;
